flatcar/scripts

- build_library/qemu_template.sh
- build_library/test_image_content.sh
- jenkins/packages.sh
- jenkins/sdk.sh
- jenkins/toolchains.sh
This merges the changes from the `flatcar-master` branch to `flatcar-master-edge`. The most important commit is the change of the Ignition variable name.
> merge flatcar-master to -edge

- build_library/catalyst_toolchains.sh
- build_library/toolchain_util.sh
Merge flatcar-master to flatcar-master-edge, to include fixes for cross-builds.
> Merge flatcar-master to flatcar-master-edge 2019-12-03

- README.md
Signed-off-by: Vincent Batts <vbatts@kinvolk.io>
have the desire to read the docs, from looking at this repo
click the link
> README: point to the current flatcar docs

- set_version
Note: Pick for the `flatcar-2513` branch
> set_version: Document new naming scheme for nightly builds

- build_packages
Signed-off-by: Vincent Batts <vbatts@kinvolk.io>
> build_packages: export build host information

- build_library/release_util.sh
- build_library/vm_image_util.sh
- jenkins/vm.sh
This PR adds the Azure Premium OEM and selective upload the premium image to GCS as a private object
This commit would upload the image to GCS as a private object and then mantle would take over the process.
> Add Azure OEM and selective private upload

- build_library/vm_image_util.sh
- jenkins/vm.sh
> build_library: Rename the images to use pro instead of premium

- build_library/release_util.sh
- build_library/vm_image_util.sh
- jenkins/vm.sh
This cherrypicks the Flatcar Pro for Azure changes to the flatcar-2632 branch
> Add new Azure Pro OEM type

- build_library/build_image_util.sh
- build_library/catalyst.sh
- build_library/dev_container_util.sh
- build_library/qemu_template.sh
- build_library/toolchain_util.sh
- build_library/vm_image_util.sh
- build_packages
- common.sh
- contrib/create-basic-configdrive
- jenkins/packages.sh
- update_chroot
This is a requirement for the user space update:
*  https://github.com/kinvolk/portage-stable/pull/130
* https://github.com/kinvolk/coreos-overlay/pull/715
> Update flatcar 2605 scripts to latest Alpha release

- build_library/build_image_util.sh
When a license file is newly added, portage may not yet have it in the
shared folder and the license inclusion step fails.
Fall back to the source repositories and look for the license file
there, too. Print a warning if not found instead of failing to build.
[Test](http://localhost:9091/job/os/job/manifest/1848/)
> Fall back to source repository license files if not in portage

- bootstrap_sdk
It makes it a bit easier to read and clearer what the script is doing
without all that repetition. No functional changes.
> bootstrap_sdk: Put image, contents and digests paths into variables

- jenkins/kola/packet.sh
The Linux 5.10 stable kernel introduced a regression that we didn't
catch because we only run kola on one hardware type in Equinix Metal.
Validate that a simple network test works on various instance types of
the current hardware generation.
Port to all active channel branches
[Ongoing](http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/3689/cldsv/)
> jenkins: run simple network test on different hardware

- jenkins/manifest.sh
This is some old commit I made in October to clean up the ref-as-PR-number detection and extend it also to scripts repo.
CI: http://localhost:9091/job/os/job/manifest/4405/cldsv/
> jenkins/manifest: Accept PR numbers also for scripts

- sdk_lib/sdk_container_common.sh
In [bce3bd9031fa78c79173f29bcac5bc49c81a03b4](https://github.com/flatcar-linux/scripts/pull/199), we added support for podman for building and running the SDK container. The presence of podman is auto-detected in sdk_container_common.sh. However, podman is preverred over docker, requiring users to use *sudo* (which podman requires and
docker does not).
This change uses docker when present, podman otherwise. It also improves podman detection - 'podman' uses argv[0] in its version string, so if 'docker' is a symlink to 'podman', 'podman --version' output uses 'docker'. This broke the SDK container on hosts which have a 'docker' symlink to 'podman' since 'podman' is then run w/o 'sudo'.
This should be cherry-picked to flatcar-3033 and flatcar-3066, too.
Host has docker and podman installed. …
> sdk_container: better docker / podman detection

- jenkins/kola/packet.sh
Follow up of: https://github.com/flatcar-linux/mantle/pull/281
> equinixmetal: use metro instead of facility

- ci-automation/vendor-testing/qemu.sh
- ci-automation: print kola command line
For running kola manually and knowing which parameters where set, it
helps to print the kola command line in the job.
None
> ci-automation: print kola command line

- ci-automation/vms.sh
The kola test scripts are named by the platforms. The image naming is
also quite difficult to know and remember, e.g., whether "ami" or
"ami_vmdk" is needed for AWS tests and whether it's "vmware" or
"vmware_ova".
To address these problems the vms build	stage now accepts the platform
names as format	input, and for each platform it	will automatically 
generate the needed image types	to run the tests.
This will allow us to run the vmware, aws, and azure vendor tests in the CI.
[here](http://192.168.42.7:8080/job/container/job/vms/123/console)
> ci-automation/vms: handle platform names and generate the image formats

- ci-automation/vms.sh
Tested there: http://jenkins.infra.kinvolk.io:8080/job/container/job/vms/125/cldsv/
> ci-automation/vm: build PXE if Equinix Metal is built

- ci-automation/ci-config.env
- ci-automation/vendor-testing/equinix_metal.sh
<hr>
Closes: https://github.com/flatcar-linux/Flatcar/issues/671
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/vms/125/cldsv/
> ci-container/test: add equinix-metal test script

- ci-automation/ci-config.env
- ci-automation/test.sh
- ci-automation/vendor-testing/aws.sh
- ci-automation/vendor_test.sh
Add a AWS test script and AWS env variables.
WIP, untested.
Feel free to take this PR and update it to make the AWS CI automation work correctly.
Closes https://github.com/flatcar-linux/Flatcar/issues/667
Not tested.
> ci-container/test: add AWS test script for CI automation

- ci-automation/vendor-testing/gce.sh
The logic we had in some tests for covering different instance types
now got more easy to reuse for testing the GVNIC mode in GCE.
Align the GCE test with AWS and DigitalOcean to test an additional
"instance type" (here just changing the NIC) and break the retest spin
case it gets called for arm64.
port to all channels
[here](http://192.168.42.7:8080/job/container/job/test/557/consoleFull)
> ci-automation/vendor-testing/gce.sh: Test GVNIC and break retest cycle

- ci-automation/vendor-testing/equinix_metal.sh
The test framework from the AWS PR allows us to align the logic which
also addresses some bugs we had here.
Port the Equinix Metal test over to the new framework (and also use
different test basenames per architecture while at it which could
otherwise result in clashes).
backport
[ongoing](http://192.168.42.7:8080/job/container/job/test/558/consoleFull)
The s3.xlarge.x86 instance fails which is a known issue and cl.locksmith.cluster also fails which I'm not sure we have seen before.
A problem seems to be that the test for n2.xlarge.x86 gets re-run even though it didn't fail.
Maybe the job also hangs at the end, as I see no new output for a while now.←Eventually there was progress, so all good.
> ci-automation/vendor-testing/equinix_metal.sh: Use test framework

- ci-automation/vendor-testing/azure.sh
Fix some comments, quote some variables.
> ci-automation/vendor-testing/azure.sh: Small fixes

- ci-automation/ci-config.env
- ci-automation/vendor-testing/azure.sh
Please see the commits for the fixes.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/test/1608/
> Fixes for azure vendor test

- ci-automation/packages.sh
- ci-automation/vendor-testing/qemu.sh
- run_sdk_container
Please see the commits for the explanations. Tested locally.
> ci-automation: Fixes

- ci-automation/test.sh
- ci-automation/vendor-testing/qemu_update.sh
CI running: http://jenkins.infra.kinvolk.io:8080/job/container/job/test_dispatcher/11/cldsv/
> Small cleanups in tests

- build_library/toolchain_util.sh
This was a place I missed where /etc/portage is set up. Because of it, user patches for sys-devel/gcc were not picked up.
Also stop using deprecated PORTDIR and PORTDIR_OVERLAY getters. We still set those variables, but we will drop them eventually.
It's pretty much standalone, but it's needed for https://github.com/flatcar/portage-stable/pull/409 and https://github.com/flatcar/coreos-overlay/pull/2404.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk_container/416/cldsv/
> build_library/toolchain_util: Set up symlink for user patches

- build_library/build_image_util.sh
- build_library/gen_tmpfiles.py
CI: (tested as a part of the weekly updates PR) http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1720/cldsv/
We used to create a base_image_var.conf tmpfiles config file that
contained information about directories under /var that weren't
covered by any other tmpfiles config file. Recently some package
update started installing a directory under /var that belonged to a
user/group not found directly in passwd/group file in /etc. This
user/group was defined in passwd/group in /usr/share/baselayout, but
at the early boot, these are not yet checked for user/group
information, so systemd-tmpfiles running inside initrd failed when
trying to create such an entry using the base_image_var.conf tmpfiles
config file.
Split the base_image_var.conf into two files - …
> build_library: Split `base_image_var.conf` into two config files

- ci-automation/test.sh
Forwarding parameters to another bash invocation through a string interpreted as a bash script is a bit troublesome. It is not enough to wrap a parameter like 'foo bar' in escaped double quotes (\") to avoid it being split into two parameters by bash executing the script string. It mostly works, but there's always a risk of having a path where this breaks. It's rare
Wrapping into escaped quotes, be them double or single, also won't work for passing an array of parameters, so it's even easier here to trigger globbing or bracket expansion or another unwanted splitting of supposedly one parameter into multiple. Globbing can be temporarily disabled with 'set -f' or 'set -o noglob', but this still leaves all the other special bash characters unescaped. So each parameter in the array should be …
> ci-automation: Properly escape parameters passed to bash

- build_library/update_chroot_util.sh
- update_chroot
Please see commit messages for description.
Seems to be working (search for "Maybe removing some hard blocks"):
CI with error messages: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages/3320/consoleText
CI with error messages gone: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages/3328/consoleText
> update_chroot: Fix some non-fatal error noise

- changelog/changes/2023-09-12-qcow2-compression.md
Add missing changelog of https://github.com/flatcar/scripts/pull/1132. See also https://github.com/flatcar/Flatcar/issues/1135.
> changelog: add changelog for qcow2 inline compression

- changelog/security/2023-10-13-curl-backport.md
- sdk_container/src/third_party/coreos-overlay/coreos/user-patches/net-misc/curl/CVE-2023-38545_7.87.0.patch
- sdk_container/src/third_party/coreos-overlay/coreos/user-patches/net-misc/curl/CVE-2023-38545_8.2.0.patch
- sdk_container/src/third_party/coreos-overlay/coreos/user-patches/net-misc/curl/CVE-2023-38546.patch
> Backport curl CVE fixes to alpha

- .github/workflows/containerd-apply-patch.sh
The containerd auto-updater script needs to be updated as we are now basing containerd on upstream ebuilds.
Test action run for the change: https://github.com/flatcar/scripts/actions/runs/6747181933/job/18342745813
PR generated by the change's action run: https://github.com/flatcar/scripts/pull/1336
Test build of that PR: https://github.com/flatcar/scripts/actions/runs/6747213855/job/18391083099?pr=1336
> containerd-apply-patch: updated to work with upstream ebuilds

- build_dev_binpkgs
- build_packages
- ci-automation/push_pkgs.sh
This is PR https://github.com/flatcar/scripts/pull/1491 back-ported to flatcar-3760. Some manual conflict resolution was required for `build_packages`.
> flatcar 3760 backport build dev packages

- build_dev_binpkgs
- build_packages
- ci-automation/push_pkgs.sh
This is PR https://github.com/flatcar/scripts/pull/1491 back-ported to flatcar-3602. Some manual conflict resolution was required for `build_packages`.
> flatcar-3602: backport build dev packages

- .github/workflows/kernel-apply-patch.sh
One more place where we were mentioning app-emulation/hv-daemons unconditionally.
> .github: Follow-up fix for missing app-emulation/hv-daemons

- build_library/set_lsb_release
> set_lsb_release: Update OS_CODENAME to LTS 2024

- ci-automation/vendor-testing/azure.sh
This follows the breakage arising from #2676.
We still perform some tests using Gen 1 on amd64. Standard_D2s_v6 does not support this, but v5 will presumably be the last version that does, so hardcode that case.
For Gen 2, you need to set the SKU for amd64 to work, and it has to use the gallery like arm64 already does.
Using the gallery is possibly slightly slower, so ideally we would only upload the image once like we do for AWS, but let's just get it working for now.
Run the Azure tests in CI.
I ran these changes against a recent nightly. The [amd64 run](http://jenkins.infra.kinvolk.io:8080/job/container/job/test/34236/) failed, but seemingly only because of flakiness and capacity, not the outright failures we were seeing before. The [arm64 …
> ci-automation: Set the right parameters for Hyper-V Gen 1/2 on Azure

- changelog/security/2025-04-29-python.md
It was fixed in https://github.com/flatcar/scripts/pull/2826.
Closes https://github.com/flatcar/Flatcar/issues/1648
> changelog: Add a missing entry for python security fix

- ci-automation/image_changes.sh
It's a recent addition - nvidia sysexts are amd64-only for now, so the EXTRA_SYSEXTS variable got some new fields to indicate that. Make use of them for filtering which extra sysexts changes to report.
Tested together with the weekly updates - the nvidia drivers extra sysexts reports do not show any more in arm64 image changes reports.
old arm64 reports with messages about failing to download listings for nvidia drivers sysexts: http://jenkins.infra.kinvolk.io:8080/job/container/job/image_changes/10961/
new arm64 reports without reports for nvidia drivers sysexts:
http://jenkins.infra.kinvolk.io:8080/job/container/job/image_changes/10976/
Downloaded the plaintext outputs for old and new reports, saved them as `{amd,arm}64{old,new}.txt` then run the following bash
```bash
for f in *.txt; …
```
> ci-automation: Filter extra sysexts by architecture

- sdk_container/src/third_party/coreos-overlay/sys-fs/overlaybd/overlaybd-9999.ebuild
I accidentally forgot to stage this change when committing the fix in #3183. 🤦‍♂️
> sys-fs/overlaybd: Actually pin TCMU this time

- sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
- sdk_container/src/third_party/coreos-overlay/profiles/coreos/targets/sdk/package.accept_keywords
CI http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/6691/cldsv/
> sys-apps/systemd: Bump systemd v257.7 in base image

- ci-automation/release.sh
The upload to R2 was added experimentally and we now want to make use of it. The CHANNEL variable wasn't defined and it failed because of that.
Do the upload for all channels and set the variable up first. Existing releases should get synced from the current Origin server via a FUSE mount that we anyway want to rely on for the directory listing that Caddy creates. Left to decide is how we manage the "current" version but that is done manually anyway as of now.
none
> ci-automation/release.sh: Fix upload to R2
