- common.sh
We are now using Flatcar's own GCE account. Switch to the new bucket.
> *: switch GCE bucket name

- build_library/disk_layout.json
Since the developer container image is only 3G in size for its rootfs, it's hard for users to do specific work there, for example, to build kernel modules.
Let's increase the size of rootfs to 6G.
> build_library: enlarge rootfs size to 6G for dev container

- build_library/release_util.sh
There has been an issue with vagrant json files where `url` field is set to an invalid URL. For example, in https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_production_vagrant.json, `url` is `gs://flatcar-jenkins/alpha/amd64-usr/2023.0.0/flatcar_production_vagrant.box`. It should be actually https://alpha.release.flatcar-linux.net/amd64-usr/2023.0.0/flatcar_production_vagrant.box.
Its reason is, the function `download_image_url()` in release_util.sh simply assumes that the input variable `download_root` includes `gs://builds.release.core-os.net/alpha` in `GS_RELEASE_ROOT` of resource variables. That's true only for Container Linux. In case of Flatcar, the `download_root` is actually `gs://flatcar-jenkins/alpha`.
What we should do here is to check for `flatcar-jenkins` in …
> build_library: fix Flatcar-specific download path from GCS

- build_library/release_util.sh
`${download_path}` gets initialized only if `${FLAGS_download_path}` is given by the user. If not given, that becomes simply an empty string. So it does not make sense to check if that includes `gs://`. Let's simply remove the if statement.
That's why the vagrant json file still has a wrong URL like `https://flatcar-jenkins/alpha/...`.
Tested with the following test script.
```
download_path=""
download_root="gs://flatcar-jenkins/alpha"
if [[ -n "${FLAGS_download_path}" ]]; then
download_path="${download_path%%/}"
elif [[ "${download_root}" == *flatcar-jenkins* ]]; then
download_channel="${download_root##*/}"
download_root="gs://${download_channel}.release.flatcar-linux.net"
download_path="${download_root%%/}/amd64-usr/2065.0.0"
else …
```
> build_library: set download_path even if its input is empty

- signing/sign.sh
This reverts commit 6025fd01eb0cc2ad3332f2efeb88ff27f901d471.
In the past we reverted fero-related changes from upstream, to avoid unexpected results.
Let's enable fero again to be in sync with upstream.
> signing: Re-add "signing/sign: pass user signatures to core_sign_update"

- build_library/disk_util
Sometimes we see such failures during Jenkins runs.
```
losetup: /mnt/host/source/tmp/...../disk_image.bin: failed to set up loop device: Resource temporarily unavailable
```
It's really hard to know which race condition it is.
To work around it, in case that losetup fails, make it retry up to 10 seconds, once in every second.
That could reduce the number of the loopback device errors in the build chain.
Inspired by https://chromium-review.googlesource.com/c/chromiumos/platform/crosutils/+/264063/
> build_library: retry losetup up to 10 seconds

- build_torcx_store
To get docker 18.09 included in the edge channel, we need to also update `build_torcx_store`.
It should be merged together with https://github.com/flatcar-linux/coreos-overlay/pull/46.
> build_torcx_store: bump docker to 18.09

- build_torcx_store
Now that we exclude old versions of Docker, we should exclude Docker 1.12 & 17.03 from the torcx store.
This PR should be merged together with https://github.com/flatcar-linux/coreos-overlay/pull/51.
(For edge)
> remove docker 1.12 17.03 from the torcx store

- build_torcx_store
So far build_torcx_store has not included any selinux context in the tarball, because it ran without `--selinux` option.
Let's add the option to fix that.
This PR should be merged after the PR https://github.com/flatcar-linux/coreos-overlay/pull/55 was merged, and a new Flatcar SDK was released from it.
> build_torcx_store: get selinux context included in torcx tarballs

- build_torcx_store
Now that docker was upgraded to 19.03.1, we need to update docker version in `build_torcx_store`.
This PR should be merged together with https://github.com/flatcar-linux/coreos-overlay/pull/62.
_for Flatcar edge_
> build_torcx_store: bump docker to 19.03

- build_library/qemu_template.sh
To fix a wrong key name when running a qemu VM with ignition, we need to replace `opt/com.coreos` with `opt/org.flatcar-linux`.
See also https://github.com/flatcar-linux/ignition/issues/2
> build_library: fix qemu key name to org/flatcar-linux

- build_library/test_image_content.sh
Since we don't need to rely on old Golang, we can remove Golang-related GLSA entries completely.
Also add a polkit-related GLSA entry, as its security patches are backported.
> build_library: remove golang from GLSA whitelist, add polkit

- build_library/test_image_content.sh
- jenkins/packages.sh
- jenkins/sdk.sh
- jenkins/toolchains.sh
Merge upstream `master` to `flatcar-master`, mainly to avoid merge conflicts around disk layout.
> Merge upstream 2019-08-30

- build_library/test_image_content.sh
Since we already backported a security patch to sys-apps/dbus 1.10, we should whitelist GLSA 201909-08 for now.
This PR should be merged together with https://github.com/flatcar-linux/coreos-overlay/pull/74.
> build_library: whitelist 201909-08 for D-BUS

- build_library/test_image_content.sh
Since we reverted perl to 5.26, we should whitelist 201909-1 for now.
> build_library: whitelist GLSA 201909-01 for perl

- build_library/test_image_content.sh
Merge upstream master to flatcar-master, to be in sync with upstream.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/13 and https://github.com/flatcar-linux/coreos-overlay/pull/95.
> Merge upstream 2019-10-17

- build_library/qemu_template.sh
The QEMU boot script has the `-i` option to provide an Ignition configuration.
For PXE images or images that have been booted already, an additional kernel command line parameter is needed for Ignition to work: `flatcar.first_boot=1`. Document this in the usage information of the script.
> build_library: Document when Ignition needs flatcar.first_boot=1, and also document flatcar.autologin

- build_library/catalyst_toolchains.sh
To make `packages-matrix` build rust sources for `arm64-usr`, we need to make toolchain include the rust target for arm.
Unfortunately, catalyst does not support the cross-build rust target by default.
We also cannot add `dev-lang/rust` to `$TOOLCHAIN_PKGS`, because then catalyst would tries to build a `cross-*/rust` package, which does not exist.
So we need to manually run emerge for rust, without `--newuse -u` options. If the `--newuse -u` options are given, the rust will not be installed at all.
> build_library: make toolchain build rust for cross-builds

- build_library/disk_layout.json
- build_library/disk_util
To make GPT partition type strings include `flatcar-` strings instead of `coreos-`, we need to change the disk layout file.
This PR should be merged after https://github.com/flatcar-linux/seismograph/pull/1 was merged.
> build_library: replace coreos with flatcar in disk layout

- build_torcx_store
Bump docker target to 19.03 for the new docker version 19.03.5.
This PR should be merged together with https://github.com/flatcar-linux/coreos-overlay/pull/133.
> build_torcx_store: bump docker to 19.03.5 for alpha 2345

- build_library/toolchain_util.sh
To set up the cross-compilation toolchain also install the Rust binary package from the toolchain build (which includes the aarch64 target) or build Rust again from source.
> build_library/toolchain_util.sh: Install Rust from cross-compilation toolchain

- jenkins/formats-arm64-usr.txt
The `image-matrix.groovy` script reads the list of image formats for ARM, from `formats-arm64-usr.txt`.
So we need to also add `ami_vmdk` to the list to publish AWS ARM images.
> jenkins: add ami_vmdk to format list for ARM

- build_library/disk_layout.json
- build_library/disk_util
To make GPT partition type strings include `flatcar-` strings instead of `coreos-`, we need to change the disk layout file as well as disk_util.
We are able to do it because Edge 2345.99.0 was released with its corresponding changes in seismograph.
> build_library: replace coreos with flatcar in disk layout for edge

- build_library/set_lsb_release
- signing/transfer.sh
Nebraska supports an additional arch
variable to distinguish both boards.
Note: Needed also for edge and alpha.
> Use same APPID for arm64 and amd64

- build_library/dev_container_util.sh
When running `emerge-gitclone` in a developer container, it still tries to fetch from coreos repos.
We should make it fetch from flatcar-linux repos.
This PR should be merged together with https://github.com/flatcar-linux/dev-util/pull/1 , https://github.com/flatcar-linux/coreos-overlay/pull/159.
> build_library: fix sync URI under Gentoo env for developer containers

- build_image
- build_library/prod_image_util.sh
- jenkins/images.sh
Create a tar ball with the contents of the / and /usr partitions
to be used as follows with systemd-nspawn (via machinectl):
machinectl import-tar flatcar-container.tar.gz flatcar-container
machinectl start flatcar-container
machinectl shell flatcar-container
or with docker by converting it to an OCI image:
docker import -c "CMD /bin/bash" flatcar-container.tar.gz flatcar-container
Since the new "prodtar" command relies on the results of the "prod" command,
it bundles it so that "prod prodtar" and "prodtar" is the same.
Note: Document how to use the tars on the website. Automatically push docker images to a repository.
> build_image: Add prodtar command to build a tar ball

- build_library/template_vmware.ovf
For the Ignition variables to be usable they need to be
specified in the OVF.
Call out that the CoreOS variables are deprecated to
reduce confusion when both are displayed besides each other.
Note: Pick for alpha and edge.
> build_library/template_vmware.ovf: Use Ignition OVF vars

- build_library/vm_image_util.sh
Write out an iPXE script file for Packet.
The script uses relative URLs to refer to
the other PXE files and thus can be copied
along with the files to any server.
This is useful because it saves the creation
of an iPXE script for a release/channel on a
third-party service. For CI testing it is
also helpful because the script does not only
end up on the release server but also already
on the Google buckets, refering to unpublished
PXE payloads.
Note: Pick for alpha and edge.
> build_library/vm_image_util.sh: Generate iPXE script

- build_library/template_vmware.ovf
There was a logical mistake in Ignition that caused ignition.config.*
only to work when it was part of the ovfenv. Thus they were added but
the old CoreOS variables marked deprecated and kept. With both as OVF
variables each of them worked but directly specifying ignition.config.*
as guest variable still didn't because of the logical mistake.
Now there is a fix and both work well when specified directly as guest
variable (https://github.com/flatcar-linux/ignition/pull/11).
Delete the old CoreOS OVF variables because they just clutter the UI
and only the Ignition variables should be used in the UI.
First set `380801d9899cceb9edd4b494fa2a9dd8b158c390` as commit in `sys-apps/ignition/ignition-9999.ebuild`.
```
$ emerge-amd64-usr -1 ignition
$ emerge-amd64-usr -1 coreos-kernel
$ ./build_image …
```
> build_library/template_vmware.ovf: Remove old CoreOS OVF variables

- build_library/template_vmware.ovf
The configuration variables for the Ignition configuration also serve as
data source for coreos-cloudinit config data (which includes plain scripts).
Document them properly and also call out that the networking variables only
work if coreos-cloudinit data is used.
For some use cases, too few networking variables were available. Add secondary
routing variables for the main network interface and add a second interface.
The variables are shown in the ESXi web UI or in VMware Workstation Player when a new VM is created from a `.ova` file.
None
Note: Pick for all channels.
> build_library/template_vmware.ovf: Document and add cloud-init OVF vars

- build_library/dev_container_util.sh
The BINHOST was still configured to be the CoreOS CL upstream location
which does not work for independent Flatcar CL releases. This broke
binary package installation in the development container.
Use the correct BINHOST to fix installation of binary packages in the
development container.
Fixes https://github.com/flatcar-linux/Flatcar/issues/106
Build the development container through `./build_image container` in the SDK.
I ensured that https://docs.flatcar-linux.org/os/kernel-modules/ works by manually replacing the URLs in `/etc/portage/make.conf` with the correct ones after running the [development container](https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.bin.bz2) through systemd-nspawn.
**Note:** Pick for all channels.
> build_library/dev_container_util.sh: Use correct BINHOST URLs

- build_library/toolchain_util.sh
- build_toolchains
Two Flatcar versions were used in /etc/portage/make.conf both in the SDK
and in the boards.
Use only a single version by default to get the expected results and not
something else when using binary packages.
The Rust crossdev package was never uploaded to /sdk/ and always
had to be compiled again.
Upload it in a separate directory because /Packages in /crossdev
doesn't refer to the Rust package and its use flags.
Create a fresh SDK with the last Alpha release manifest. Then enter it and check out this `scripts` branch. Test to build both boards. Only Rust for the arm64 board would be recompiled because it is not uploaded yet to the bucket.
Not tested on Jenkins yet.
Note: Pick for all channels.
> Reuse correct binary packages for a Flatcar version

- build_packages
- jenkins/packages.sh
When the ebuild file changed but not its version nor its cross-workon
commit, the binary package would be used. Also some dependencies are not
encoded to trigger a rebuild of depending packages.
Allow to exclude some binary packages so that we can be sure that they
are rebuilt.
In the packages-matrix job in Jenkins or local:
```
./build_packages --usepkg-exclude="package/a package/b"
```
None
> build_packages: Add flag to ignore some binary packages

- build_toolchains
The Rust arm64 crossdev toolchain package was uploaded to
toolchain-arm64/rust… instead of toolchain-arm64/dev-lang/rust….
Upload the complete dev-lang folder as only Rust will be fetched
from there anyway.
Jenkins test not done yet
> build_toolchains: Fix upload path for toolchain-arm64 package

- build_library/qemu_template.sh
The qemu wrapper template still uses `CoreOS` in some places. This change updates the naming to `Flatcar`. 
Straightforward 3-line naming change. A code review should suffice.
Reviewed the change (diff to flatcar-master).
> qemu_template.sh: update naming CoreOS -> Flatcar

- build_library/set_lsb_release
Ported from upstream.
Note: Cherry-pick for all channels and `flatcar-build-2513.0.0`.
> set_lsb_release: update codename

- build_library/grub.cfg
If a user or old software creates the flag file on the old CoreOS location,
nothing would happen.
Check the old location, too, so that Ignition is rerun.
Requires https://github.com/flatcar-linux/bootengine/pull/13 and https://github.com/flatcar-linux/update_engine/pull/5
Build available here:
```
$ wget 'https://storage.googleapis.com/flatcar-jenkins/developer/boards/amd64-usr/2345.3.1+dev-flatcar-master-449/flatcar_production_qemu.sh'
$ chmod +x flatcar_production_qemu.sh
$ wget 'https://storage.googleapis.com/flatcar-jenkins/developer/boards/amd64-usr/2345.3.1+dev-flatcar-master-449/flatcar_production_qemu_image.img.bz2'
```
1. Boot up without an Ignition config: `./flatcar_production_qemu.sh`
2. Create the flag file and shutdown via SSH `mkdir /boot/coreos; touch …
> Support the /boot/coreos/first_boot flag file

- build_library/test_image_content.sh
Includes https://github.com/coreos/scripts/pull/894 https://github.com/coreos/scripts/pull/893 https://github.com/coreos/scripts/pull/892
Note: For all channels and `flatcar-build-2513.0.0`.
> Port CoreOS upstream PRs

- contrib/create-coreos-vdi
Fixed a grammar based line at `Line 47`:
`echo "$0: Target path (${DEST}) do not exists." >&2` -> `echo "$0: Target path (${DEST}) does not exist." >&2`
The PR changes a simple line of grammar for the error message you get when creating a template by running this script.
As this is not an actual technical change this change does not require a description imho
Not applicable
commands you issued as well as the output you got.]
Tested the script and got a proper reply in the error message (`does not exist` instead of `do not exists`
> Update create-coreos-vdi - grammar change

- build_library/build_image_util.sh
- build_library/dev_container_util.sh
- build_library/ebuild_aci_util.sh
- build_library/oem_aci_util.sh
- build_library/prod_image_util.sh
The license JSON file did only include the package names but not
any other metadata. Also since the file was not on the image itself,
it had to be downloaded.
Add more metadata to the license JSON and store it on the image.
Assuming a VM was build from it:
```
$ less /usr/share/licenses/INFO
$ less /usr/share/licenses/licenses.json.bz2
$ ls /usr/share/licenses/common/
Apache-2.0.gz BSD-2.gz BSD-4.gz BSD-with-attribution.gz BSD.gz BZIP2.gz CC-BY-3.0.gz CC-BY-SA-3.0.gz CPL-1.0.gz FDL-1.3+.gz GPL-1.gz GPL-2+.gz GPL-2.gz GPL-3+.gz GPL-3.gz HPND.gz ISC.gz Info-ZIP.gz LGPL-2+.gz LGPL-2.1+.gz LGPL-2.1.gz LGPL-2.gz LGPL-3+.gz LGPL-3.gz MIT.gz MPL-2.0.gz NPL-1.1.gz OPENLDAP.gz PCRE.gz RSA.gz ZLIB.gz freedist.gz inner-net.gz lsof.gz metapackage.gz openafs-krb5-a.gz openssl.gz public-domain.gz rc.gz …
```
> build_library: Enhance license info and store it on the image

- build_library/build_image_util.sh
- build_library/dev_container_util.sh
- build_library/ebuild_aci_util.sh
- build_library/oem_aci_util.sh
- build_library/prod_image_util.sh
Pick the license metadata changes for the Alpha hotfix release.
Needs a `coreos-overlay` update for the `coreos-devel/mantle` ebuild file to use the correct license name.
> Updates for Alpha 2514.1.1

- build_library/build_image_util.sh
- build_library/dev_container_util.sh
- build_library/ebuild_aci_util.sh
- build_library/oem_aci_util.sh
- build_library/prod_image_util.sh
Pick the license metadata changes for the Stable hotfix release.
These changes will also be picked for the `flatcar-build-2513.2.1` Beta release branch.
Needs a `coreos-overlay` update for the `coreos-devel/mantle` ebuild file to use the correct license name.
> Updates for Stable 2512.3.1

- build_library/build_image_util.sh
For some unicode characters in ca-certificates file names "rev" complains
about an "invalid or incomplete multibyte or wide character"
and gives no output.
Filter out any unexpected characters for "rev" and replace them with "?"
so that "ls some?name" will still resolve the original name.
> Filter out unicode characters in package content list

- build_library/catalyst.sh
- build_library/catalyst_toolchains.sh
- build_library/toolchain_util.sh
Install `virtual/rust` to avoid version conflicts that happen in case of rust versions in the SDK being different from those in the new ebuilds.
`/usr/share/catalyst/targets/stage1/stage1-chroot.sh` installs gcc and its dependencies, including `dev-lang/rust`, while `virtual/rust` does not get updated. That results in version conflicts between `virtual/rust` and `dev-lang/rust`.
To avoid such an issue, we should update also `virtual/rust` when building stage1. Since `virtual/rust` automatically pulls in `dev-lang/rust`, we do not need to explicitly specify `dev-lang/rust` here.
Also deal with both virtual/rust and dev-lang/rust.
Toolchain utils have installed only `dev-lang/rust`. It could result in version mismatch between `virtual/rust` and `dev-lang/rust`, because `dev-lang/rust` does …
> build_library/catalyst: Update virtual/rust during catalyst stage1 for alpha

- bootstrap_sdk
- build_library/catalyst_default_stage4.sh
- build_library/catalyst_sdk.sh
- build_library/catalyst_toolchains.sh
- build_library/toolchain_util.sh
- build_toolchains
- common.sh
- jenkins/sdk.sh
Before, we were relying on the toolchains job to build and upload packages that were part of the SDK. With this change, all packages that should be part of the SDK are built and uploaded by the SDK job. The toolchains job only builds toolchain packages specific for the release.
This change includes several adjustments done to both the SDK and the toolchains jobs to make this work:
* Make the SDK job build all cross toolchains, including Rust
* Stop building Rust in the toolchains job and use the one in the SDK instead.
* In `toolchain_util.sh`: detect when the symlink folder for crossdev packages is missing and run crossdev to create it during `update_chroot` setup.
* Make it possible to build the SDK starting from stage 4 instead of stage 1, to make the SDK building faster for PR …
> bootstrap_sdk: build and upload SDK toolchain pkgs

- build_library/template_vmware.ovf
The VM hardware and OS type versions were outdated and resulted in
features not being available by default.
Choose a newer ESXi host version (requires 6.5) and set the guest
OS type to Linux 3.x 64 bit.
See https://github.com/flatcar-linux/Flatcar/issues/154
Boot a VMware VM in the ESXi web interface or via ovftool/kola or in VMware Player.
Ran kola tests on ESXi and tested manually using the ESXi web interface.
> build_library/template_vmware.ovf: Newer OS type and hardware version

- common.sh
- set_version
The environment variables FLATCAR_DEV_BUILDS and FLATCAR_DEV_BUILDS_SDK
define where the base URL for the binary package store of the board
packages and the SDK packages. To set it, they were either exported in
the chroot or passed each time as parameter but this was only available
for the SDK packages in the tricky order
"update_chroot --dev_builds_sdk URL" (or --binhost) and then
"./build_packages --skip_chroot_upgrade".
The defining information for binary package URL comes from version.txt
but it lacks the base URL for a convenient use. Add the base URLs for
SDK and board packages there to be able to get binary packages without
manual tricks and errors. Any changes to
~/trunk/.repo/manifests/version.txt will directly be picked up
from ./build_packages and friends to set the correct …
> common: Support reading the package URL env vars from version.txt

- set_version
The SDK package URL is constructed from FLATCAR_DEV_BUILDS in
build_library/toolchain_util.sh which caused the --dev-board flag
also to imply --dev-sdk. Using --no-dev-sdk didn't help.
Document this and work around it by setting the SDK URL explicitly
with --no-dev-sdk.
```
./set_version --dev-board --board-version amd64-usr/CHANNEL-nightly --no-dev-sdk --sdk-version 2513.1.0
```
Using the above I was able to fetch SDK packages.
Note: Pick for all channels
> set_version: Set SDK URL to allow a release SDK with a dev board

- build_library/catalyst.sh
The default update seed command does only specify gcc which leads to
an error because »The short ebuild name "gcc" is ambiguous«.
Choose the standard package name instead of the cross compiler packages
under the assumption that it doesn't really matter at this point, but
if needed we can add the other package names later, too.
Run the manifest job with `sdk-full` as downstream.
The failing part now succeeded but the build failed due to other issues.
> build_library/catalyst.sh: Specify which gcc package to rebuild

- update_ebuilds
The metadata/md5-cache is not required and we stop using it because
this machine-generated content is a common cause for merge conflicts
and has no benefits.
`./update_ebuilds PKG`
Downloaded a newer glib package
> update_ebuilds: Do not generate metadata/md5-cache files

- build_library/toolchain_util.sh
The SDK now includes a Rust version with the aarch64 cross-compilation
libraries and the toolchain job doesn't build it anymore. Yet it was 
still recompiled because the path had changed.
Remove the adjustment of the download URL and any automatic building
of Rust. Just issue a warning so that any problem can be spotted easily.
This change does not affect the SDK bootstrapping (full or just stage4)
but affects ./build_packages and the toolchains job. For the toolchains
job the crossdev setup is missing anyway and rebuilding wouldn't help
but only downloading, yet since in stage4 there are no binary package
URLs at all, it's best to remove this step and if it is needed later,
the warning will help.
Build the toolchains job with a new SDK and see that no Rust recompilation happens.
[Tested …
> build_library/toolchain_util.sh: Remove old download code for Rust

- build_library/grub.cfg
Our GRUB configuration is currently probing all devices in search of a device with UUID 00000000-0000-0000-0000-000000000001. This is causing trouble on Packet c3.medium.x86 and m2.xlarge.x86 machines, where this probing leads to the machine hanging on GRUB for almost half an hour and then not mounting the disks correctly. See flatcar-linux/Flatcar#155 for more information.
This code removes the probing from GRUB. An equivalent check will be added to bootengine to be performed during initramfs.
Building an image with this change leads to GRUB booting successfully on a c3.medium.x86 machine.  Without the corresponding bootengine change, the disk UUID stays at 0x01. With the corresponding change, it gets randomized after initramfs is done running.
WIP notice: Due to issues with current …
> Stop probing for UUID 00000000-0000-0000-0000-000000000001 in GRUB

- set_version
The nightly SDK builds can be used as source for binary packages for
the SDK chroot which helps to reduce local build times.
Add support for resolving the latest nightly SDK in the set_version
script the same way as resolving board nightly builds.
```
./set_version --dev-board --board-version amd64-usr/main-nightly --sdk-version sdk-main-nightly [--dev-sdk]
```
Note: Pick for flatcar-2592 and flatcar-2513
> set_version: Support resolving nightly SDKs

- contrib/create-basic-configdrive
When making an ISO locally, there are unit files I would like to specify without editing this script everytime. :smile_cat: 
And ran this script through `shellcheck` for linting.
> contrib: allow newer ssh keys, and user-provided template

- build_library/qemu_template.sh
Signed-off-by: Vincent Batts <vbatts@kinvolk.io>
Used `shellcheck`, and also switched to `nproc` for counting cpus, as it's on most ever linux these days.
as normal
ensured it still works. All clear there
> qemu_template: shell lint and update

- jenkins/formats-amd64-usr.txt
Trigger a Jenkins build and let it should automatically pick Azure Pro 
None done yet.
> Add Azure Pro to the list of amd64 format list

- build_library/vm_image_util.sh
Fix flatcar-linux/Flatcar#71
This PR should be merged with flatcar-linux/coreos-overlay#636
```
emerge-amd64-usr oem-qemu
./build_image
./image_to_vm.sh --format=qemu
```
Built a local image, and created a QEMU image. Verified in `/usr/share/oem/{grub.cfg|oem-release}`
> Add OEM package for QEMU

- build_library/catalyst.sh
- build_library/toolchain_util.sh
- jenkins/packages.sh
- update_chroot
Setting the invalid `CCACHE_` variables resulted in strange failure in projects depending on meson, newer version like 0.55.3.
For example systemd build fails like the following errors:
```
* ACCESS DENIED:  utimes:       /mnt/host/source/ccache
* ACCESS DENIED:  utimes:       /mnt/host/source/ccache
F: utimes
S: deny
P: /mnt/host/source/ccache
A: /mnt/host/source/ccache
R: /mnt/host/source/ccache
C: ccache cc /build/amd64-usr/var/tmp/portage/sys-apps/systemd-246/work/systemd-246-abi_x86_64.amd64/meson-private/sanitycheckc.c -o /build/amd64-usr/var/tmp/portage/sys-apps/systemd-246/work/systemd-246-abi_x86_64.amd64/meson-private/sanitycheckc.exe -O1 -pipe -pipe -D_FILE_OFFSET_BITS=64
```
We should not set up ccache at all, as it has been already disabled in coreos-overlay repo.
CI passed
> jenkins: do not configure ccache variables

- build_library/check_root
Kernel source tree started to have a broken link `tools/testing/selftests/powerpc/copyloops/memcpy_mcsafe_64.S`.
Especially in case of Kernel 5.8.18, like:
```
broken link: /usr/src/linux-5.8.18-coreos/tools/testing/selftests/powerpc/copyloops/memcpy_mcsafe_64.S
ERROR   build_packages: test_image_content: Failed symlink check
```
Ignore the symlink when checking broken symlinks.
```
```
Local builds with https://github.com/kinvolk/coreos-overlay/pull/667.
> build_library: Ignore broken symlink in Kernel source tree

- build_library/build_image_util.sh
- build_packages
- common.sh
This change fixes an issue with builds that use a gcc-9.3.0 SDK. `gcc-config` in that SDK version creates a symlink in binutils' libs directory to gcc's `liblto` since some packages expect binutils to ship that library. The wrong symlink is created for chroot environments however, which makes a health check fail in the `build_packages` and `build_image` script. We fix this by correcting the symlink with a new custom function in `common.sh`.
This change is required in order to build the packages and image with the gcc-9.3.0 SDK.
> build_packages, build_image_util.sh: fix up liblto symlink

- build_library/dev_container_util.sh
- build_library/vm_image_util.sh
This commit updates the azure pro package reference to the oem-azure-pro. This commit also fixes the BINHOST URL for the developer container portage conf file
```
./build_image
./image_to_vm --format=azure_pro
```
A Jenkins developer build which successfully picked the right oem package. The URL was verified in a developer container.
This need to be picked into the `flatcar-2643` branch
To be merged with kinvolk/coreos-overlay#710
> Update the azure pro package reference to the oem-azure-pro

- build_library/dev_container_util.sh
The build_image script invokes the create_dev_container function and
passes the `FLAGS_group` as param. Use the param, to generate the
binhost URL instead of using the DEFAULT_GROUP which stays as developer
always.
Fixes: kinvolk/Flatcar#298
Note: Pick the patch to `flatcar-2605` and `flatcar-2705`
```
./build_image --group=stable container
```
Built a test container locally with the `--group` parameter and verified the `/etc/portage/make.conf`
> dev_container_util.sh: Use the shflags group instead of the default flag

- build_library/vm_image_util.sh
- jenkins/formats-amd64-usr.txt
- jenkins/vm.sh
This is the initial creation of an AWS Pro image coming with support,
and features added on top of it.
*Note:* Pick for 2605 and 2705
Built image and ran kola tests
> Add AWS Pro OEM type

- build_library/qemu_template.sh
add some logic to provide more CPUs (than hardcoded '1') for ARM.
But don't hog all `VM_NCPUS`, as we are still emulating them
Signed-off-by: Vincent Batts <vbatts@kinvolk.io>
This script will end up in the release artifacts, so I tested this diff running the most recent arm build (2605.1.0)
```shell
core@flatcar-local ~ $ cat /etc/os-release 
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=2605.1.0
VERSION_ID=2605.1.0
BUILD_ID=2020-08-31-1924
PRETTY_NAME="Flatcar Container Linux by Kinvolk 2605.1.0 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar-linux.org/"
BUG_REPORT_URL="https://issues.flatcar-linux.org"
FLATCAR_BOARD="arm64-usr"
core@flatcar-local ~ $ lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line …
```
> qemu_template: use more cpus for ARM if available

- build_library/vm_image_util.sh
- jenkins/formats-amd64-usr.txt
- jenkins/vm.sh
This adds gce_pro as one of the valid formats, currently it installs the `oem-gce` package.
Built image and run kola tests (vm-matrix 1896, kola/gce 366)
> Add GCE Pro OEM type

- build_library/build_image_util.sh
- build_library/dev_container_util.sh
The repos were moved to kinvolk. Redirects still work, but it's better
not to rely on them.
> build_library: Fix git URLs

- build_library/vm_image_util.sh
When building the ec2-compat package for the ami_vmdk_pro image format, use the new aws_pro flag instead of the existing one.
It should be merged together with https://github.com/kinvolk/coreos-overlay/pull/794
> vm_image_util: Use new aws_pro flag for ec2-compat

- setup_board
eselect calls "portage get_repo_path /build/amd64-usr coreos" at some
point. Before updating portage, portageq seemed to take all the
information not from /build/amd64-usr (which at the time contained no
repo information at all), but rather from /. The newer version of
portageq seems to respect the passed root now, so it actually tries to
consult the nonexistent repos configuration in /build/amd64-usr and
fails. To avoid the failure, perform the copying of the configuration
files earlier.
Test build: http://localhost:9091/job/os/job/manifest/1953/cldsv/ (arm64 failed at packages matrix because of some nvidia stuff)
> setup_board: Copy repos.conf earlier

- build_library/catalyst.sh
I have no idea how this thing worked before - the repos never were in
/usr/portage nor in /usr/local/portage… But the newer version of
portage seems to be pretty picky about the validity of repos location,
so fix them.
This fixes some issues appearing during the stage4/fsscript of the catalyst build with updated portage.
Test build: http://localhost:9091/job/os/job/manifest/1951/cldsv (arm64 packages matrix failed because of some nvidia stuff)
> build_library/catalyst.sh: Fix paths to ebuild repos

- bootstrap_sdk
- build_toolchains
ROOT_OVERLAY variable is defined in terms of TEMPDIR. The TEMPDIR
variable is set to an empty value by catalyst.sh, which the two
scripts import. So ROOT_OVERLAY always ended up being located in
toplevel directory (i.e. `/`). But the TEMPDIR variable gets a
meaningful value after calling the catalyst_init function, so define
the ROOT_OVERLAY after the function is called.
This doesn't fix any failure, but makes sure that this directory is placed somewhere within the directory with the rest of the catalyst stuff resides.
Test build: http://localhost:9091/job/os/job/manifest/1954/cldsv/ (arm64 failed at packages matrix due to some nvidia stuff, unrelated to this PR)
> bootstrap_sdk, build_toolchains: Move the ROOT_OVERLAY variable

- build_torcx_store
Now that Docker 1.12 is gone, we need to also exclude docker 1.12 from the list of torcx stores.
This PR should be merged together with https://github.com/kinvolk/coreos-overlay/pull/826.
```
```
CI passed: http://localhost:9091/job/os/job/manifest/1960/cldsv/
> torcx: delete docker 1.12

- build_packages
The `break_dep_loop` function is updated to take pairs of package name and multiple USE flags to be disabled, and makes sure all the packages in pairs are rebuilt. That way it's more robust against package build ordering.
In our case the issue was that we had a dependency cycle like `sys-apps/systemd` -> `sys-fs/cryptsetup` -> `virtual/udev` -> `sys-apps/systemd`. We were breaking the cycle at the first arrow, thus not building `sys-fs/cryptsetup` in dependency-cycle-breaking emerge as it was not pulled by anything else as a dependency. When doing the rest-of-the-packages-building emerge, `sys-fs/cryptsetup` was built and `sys-apps/systemd` was rebuilt, in that order. But after updating portage to a newer version, the order was reversed and `sys-apps/systemd` failed during the configure …
> Improve the dependency cycle breaking logic

- build_docker_aci
- build_library/vm_image_util.sh
- build_oem_aci
`build_docker_aci` and `build_oem_aci` at some point call the `emerge_to_image` function which uses the `$FLAGS_jobs` variable in `emerge` parameter `--jobs=$FLAGS_jobs`. But the scripts did not define such a flag, which resulted in calling `emerge` with `--jobs=`. Apparently updated portage didn't like that (it interpreted empty value as a string and was later throwing an exception when portage tried to compare a string to number with `<`).
Tested during release.
> Fix missing jobs parameter

- image_to_vm.sh
Now, in the oem aci creation step, we make use of the jobs param.
Without this flag, an empty string is passed to emerge which results
in failure.
```bash
./build_image
./image_to_vm.sh --from=.......... --board=amd64-usr --format=gce
```
Locally tested.
> image_to_vm.sh: Explicity mention the jobs param in image_to_vm step

- jenkins/vm.sh
One Jenkins jobs for each image format caused a large overhead.
Allow to build multiple image formats in one job.
> jenkins/vm: expect a FORMATS parameter which has a list of formats

- bootstrap_sdk
- build_library/catalyst.sh
- build_library/catalyst_sdk.sh
This change updates the stage1 SDK bootstrap build to use local
("known good") package ebuilds only, preventing updated package ebuilds
to apply in stage 1. This fixes SDK build breakage we observed when
upgrading core libraries like readline.
The change also removes the seed update from stage 1 as it should not
be needed anymore now that we postpone any package updates to stage 2.
The following package ebuild repos are used for stage 1:
- for portage-stable, we simply copy /var/gentoo/repos/gentoo
from the SDK root.
- coreos-overlay is more complicated since ebuilds are missing from
the SDK. So we grok the version the SDK was built with from
/mnt/host/source/.repo/manifests/default.xml
and then we create a local stage 1 clone of
https://github.com/kinvolk/coreos-overlay.git
in which we …
> Fix SDK bootstrap in bootstrap_sdk: no package updates in stage 1

- bootstrap_sdk
- jenkins/sdk.sh
This change uses portage-stable and coreos-overlay from the local SDK chroot (from /var/lib/gentoo/repos) in the stage 1 SDK bootstrap build. This is part 2 of the SDK bootstrap stage 1 fix (part 1 is covered in #123 ), which ensures stage 1 does
not introduce any changes in its ebuilds over the seed SDK.
The change also introduces an option to consciously divert from the above enforcement (i.e. **do** introduce a change in the stage1 ebuilds) by use of command line parameters:
```
--stage1_overlay_ref <gitref> will check out coreos-overlay and use <gitref> for stage 1 instead of the
local SDK's /var/lib/gentoo/repos/coreos-overlay
--stage1_portage_ref <gitref> will check out portage-stable and use <gitref> for stage 1 instead of the
local SDK's /var/lib/gentoo/repos/gentoo
```
If any of …
> bootstrap_sdk: use local SDK ebuilds for stage1 (part 2)

- build_docker_aci
- build_image
- build_library/build_image_util.sh
- build_library/vm_image_util.sh
- build_oem_aci
- build_packages
- common.sh
- image_to_vm.sh
- rebuild_packages
- setup_board
- update_chroot
The `--jobs` parameter that some scripts defined was not used anywhere
in jenkins or mantle. So the value of the parameter always ended up
being equal to `${NUM_JOBS}` set by `common.sh`. Also, even if the
`--jobs` parameter was used for some script, that script sometimes
didn't forward the jobs value to other scripts, so the other scripts
ended up using `${NUM_JOBS}` again. Also, the `${FLAGS_jobs}` variable
was used by some functions in the build library, and those functions
were sometimes invoked by scripts that didn't define the
`${FLAGS_jobs}` variable. It is tedious to track which script should
actually define the parameter, and where it should be forwarded.
Just get rid of this half-working pretense. If you want to affect how
many jobs `emerge` uses, export the `NUM_JOBS` …
> Drop `--jobs` parameter

- build_library/catalyst_toolchains.sh
This change removes 8 years old code from the toolchains build which tries to update SDK libraries for unknown reasons, breaking the toolchains build in the glibc-2.33 update since touching the SDK triggers a circular dependency otherwise unseen.
Signed-off-by: Thilo Fromm <thilo@kinvolk.io>
> catalyst_toolchains: don't touch the SDK

- jenkins/images.sh
- jenkins/kola/aws.sh
- jenkins/kola/azure.sh
- jenkins/kola/dev-container.sh
- jenkins/kola/do.sh
- jenkins/kola/gce.sh
- jenkins/kola/packet.sh
- jenkins/kola/qemu.sh
- jenkins/kola/qemu_uefi.sh
- jenkins/kola/vmware-esx.sh
- jenkins/manifest.sh
- jenkins/packages.sh
- jenkins/prerelease/aws.sh
- jenkins/prerelease/azure.sh
- jenkins/release.sh
- jenkins/sdk.sh
- jenkins/systemd-run-wrap.sh
- jenkins/toolchains.sh
- jenkins/vms.sh
The logic of the inline bash scripts of each job was sometimes
separated into the flatcar-scripts/jenkins/*.sh helpers but mostly
part of the Groovy file. This coupling had its advantages but also
downsides when special cases needed to be added for different release
versions. Other issues were that the inline scripts needed the
backslash character to be escaped twice and Jenkins was not good in
terminating the child processes when stopping a job. Having inline
bash scripts in Groovy also mandated the use of Jenkins to build and
release Flatcar Container Linux which hinders test builds in other CI
platforms.
Move the inline bash scripts fully to to the files in
flatcar-scripts/jenkins/ and create new ones for job that didn't have
a script there yet. Also invoke them through a systemd-run …
> jenkins: move all inline bash scripts to flatcar-scripts

- jenkins/systemd-run-wrap.sh
The timestamp alone was not enough to prevent unit name clashes.
Add a random suffix to greater reduce the chance of hitting a clash.
> jenkins/systemd-run-wrap.sh: randomize unit name suffix

- build_library/build_image_util.sh
- jenkins/kola/qemu.sh
- jenkins/kola/qemu_uefi.sh
The kola update tests need a dev-key-signed update payload. This was
lacking and caused the update tests to be skipped.
Generate the test update payload for both dev builds and release builds
and run the kola tests for both. The test update payload has a special
name to not confuse it with the real update payload for releases, and
we keep the previous behavior to sign releases. Therefore, the
generate_update function wasn't used but the extract_update function
extended with generating the additional test payload.
This replaces https://github.com/kinvolk/flatcar-scripts/pull/98
Depends on https://github.com/kinvolk/mantle/pull/187 and https://github.com/kinvolk/mantle/pull/189
In a follow-up PR I plan to add testing to update from the last release in addition.
*Note:* Should be picked for …
> Generate test update payload and run the kola update test

- build_library/qemu_template.sh
starting from qemu-6.0.0, options with short-form are deprecated.
```
$ ./flatcar_production_qemu.sh
qemu-system-x86_64: -fsdev local,id=conf,security_model=none,readonly,path=/tmp/flatcar-configdrive.gyqmdrQqfA: warning: short-form boolean option 'readonly' deprecated
Please use readonly=on instead
```
See this commit: https://github.com/qemu/qemu/commit/ccd3b3b8112b670fdccf8a392b8419b173ffccb4
Signed-off-by: Mathieu Tortuyaux <mathieu@kinvolk.io>
- tested with 
```
$ qlist -Ikv app-emulation/qemu
app-emulation/qemu-5.2.0-r2
app-emulation/qemu-6.0.0
```
> build_lib/qemu_tmpl: fix short-form warning

- build_library/disk_layout.json
The previously used partition uuid for the rootfs partition of the devcontainer is x86 specific.
Change the partition uuid to one that works for both arches.
```
./build_image --board=arm64-usr container
```
Ran the developer container on aarch64.
```
systemd-nspawn --image=flatcar_developer_container.bin
```
> disk_layout: devcontainer: use architecture agnostic part uuid

- bootstrap_sdk
Logs show that currently the seed tarball is used for building stage1 and then stage2 - so the output of stage1 is discarded. This PR fixes that and uses stage1 results for stage2.
`./bootstrap_sdk`
`./bootstrap_sdk`
Before:
```
26 Jul 2021 10:33:52 -00: NOTICE  : Emptying directory: /mnt/host/source/src/build/catalyst/tmp/flatcar-sdk/stage1-amd64-2021.07.26+dev-main-nightly-3124
26 Jul 2021 10:33:52 -00: NOTICE  : Starting auto from /mnt/host/source/src/build/catalyst/builds/seed/flatcar-sdk-amd64-2920.0.0.tar.bz2
26 Jul 2021 10:33:52 -00: NOTICE  : to /mnt/host/source/src/build/catalyst/tmp/flatcar-sdk/stage1-amd64-2021.07.26+dev-main-nightly-3124 (this may take some time) ..
...
26 Jul 2021 11:13:54 -00: NOTICE  : Emptying directory: …
```
> bootstrap_sdk: override seed path after building stage1

- build_library/build_image_util.sh
- build_library/disk_layout.json
- build_library/disk_util
- disk_util: support compressed btrfs filesystems
The limited /usr and OEM partiton size is a challenge when adding new
packages or updating a package. Since the disk layout can't be changed
for compatibility reasons when updating an existing instance, we can't
simply try out something without ensuring first that enough space is
there by removing something else. This situation can be relaxed by
leveraging btrfs compression. There was some support for btrfs but it
was a bit outdated and didn't allow to configure compression or setting
read-only flags.
Fix the btrfs support, allow to mark the default subvolume as read only
and add a compression variable that allows to select a compression
algorithm. Instead of enabling compression by setting the mount option,
we can set the filesystem …
> disk_util: support compressed btrfs filesystems, use btrfs for the OEM partition

- build_library/build_image_util.sh
- build_library/vm_image_util.sh
The vmlinuz kernel image gets installed to /usr/boot/ but isn't usable
for dm-verity until it gets copied over to /boot/flatcar/ and the hash
gets embedded at a particular offset. The file in /usr/boot/ uses space
while it's not having a real purpose as long as dm-verity is used.
Delete the vmlinuz file under /usr/boot/ to free up space.
Build an image and run all tests
→ 203 MB free on `/usr`
http://localhost:9091/job/os/job/manifest/3150/cldsv/
> build_image_util.sh: delete vmlinuz file from /usr partition

- build_library/disk_layout.json
Until https://github.com/kinvolk/Flatcar/issues/461 is resolved we should not switch the OEM partition to compression with btrfs yet.
Also see https://github.com/kinvolk/ignition/pull/22
This reverts commit bc97e15c3cd55f10cc11016578673744e3220ffc.
> Revert "disk_layout: use btrfs for the OEM partition"

- build_library/disk_layout.json
This reverts commit bb9ddfb08a83a456fc56962e62538bdfc0031a2f,
meaning that the planned change is now done and we switch the OEM
partition to btrfs. The reason for the revert is resolved in
https://github.com/kinvolk/ignition/pull/22
In the mentioned PR is was tested that there is no regression when using btrfs for the OEM partition with an existing Ignition config which refers to the OEM partition with ext4
> Revert "Revert "disk_layout: use btrfs for the OEM partition""

- bootstrap_sdk
- build_library/toolchain_util.sh
Some issues with lib(64) handling and rust were found during attempts to bootstrap the SDK on arm64. This PR resolves them.
Provision powerful arm64 machine.
Fetch kinvolk/coreos-overlay/pull/1130
Fetch stage4 from https://github.com/kinvolk/Flatcar/issues/319#issuecomment-881553797.
`./bootstrap_sdk --seed_tarball`
> bootstrap_sdk: enable arm64 sdk bootstrap

- bootstrap_sdk
Previously before https://github.com/kinvolk/flatcar-scripts/pull/134, `bootstrap_sdk` was looking at the wrong path (`/usr/lib/rust-*/rustlib/aarch64-unknown-linux-gnu` instead of
`/usr/lib/rustlib/aarch64-unknown-linux-gnu`).
As a result, Rust got always removed and rebuilt in `install_cross_rust`, which resulted in `flatcar-sdk/crossdev/dev-lang/rust/rust-1.54.0-1.xpak` being created.
Now legitimate changes of https://github.com/kinvolk/flatcar-scripts/pull/134 prevent the rebuild from happening.
The path already exists in a stage4 SDK build, because the seed stage already has cross-compilers so the Rust upgrade has all the right cross-paths.
That's why SDK builds with only stage4 failed when it tries uploading Rust packages like the following.
On the other hand, full SDK builds with …
> bootstrap_sdk: skip uploading non-existent directory to fix Rust builds

- build_torcx_store
This switches the default torcx build to docker-20 and removes older torcx packages. Older docker versions don't support cgroupv2 which is also enabled at the same time.
Pull this and kinvolk/coreos-overlay#931.
`./build_image`
Builds successfully. Still need to run the change through jenkins.
> switch default torcx build to docker-20

- build_library/build_image_util.sh
- build_library/generate_au_zip.py
To be able to support arm64 native SDK without cross builds, we should make `generate_au_zip` support both architectures, amd64 and arm64.
Without doing that, `build_image` fails with `ERROR : Required WHITE_LIST items ld-linux-x86-64.so.2 not found!!!`, because the script recognizes only amd64 libs in WHITE_LIST.
We should first determine the architecture in build_image, before running `generate_au_zip`, and pass the architecture, either amd64 or arm64.
Also add `allow_list` and `ld_linux` parameters to necessary functions.
Replace `black list` with `deny list`, `white list` with `allow list`.
```
...
./build_image
```
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/3281/cldsv
> build_library: support multi-arch in generate_au_zip

- build_library/disk_util
disk_util sometimes bails out during build with an ASCII conversion error:
```
Traceback (most recent call last):
File "/mnt/host/source/src/scripts/build_library/disk_util", line 1114, in <module>
main(sys.argv)
File "/mnt/host/source/src/scripts/build_library/disk_util", line 1110, in main
options.func(options)
File "/mnt/host/source/src/scripts/build_library/disk_util", line 779, in Verity
Tune2fsReadWrite(options, part, disable_rw=True)
File "/mnt/host/source/src/scripts/build_library/disk_util", line 716, in Tune2fsReadWrite
image.write(chr(flag_value))
UnicodeEncodeError: 'ascii' codec can't encode character '\xff' in position 0: ordinal not in range(128)
```
Curiously, the error does not reproduce every time (though the code leading to the error is straightforward), hinting at …
> build_library/disk_util: use byte array for conversion, not chr()

- jenkins/kola/qemu_common.sh
The update test runs first but if it fails, we still want to continue
with the regular test suite.
> jenkins/kola/qemu_common.sh: continue regular tests even if update test fails

- build_library/test_image_content.sh
Clean up following entries from the GLSA allow list.
* 201904-13: git 2.26.3, so not affected
* 201909-08: dbus 1.12.20, so not affected
* 201911-01: openssh 8.6, so not affected
* 202003-12: sudo 1.9.5, so not affected
* 202003-20: systemd 246+, so not affected
* 202003-24: file 5.39, so not affected
* 202003-30: git 2.26.3, so not affected
* 202003-31: gdb 9.2, so not affected
* 202003-52: samba 4.12.9, so not affected
* 202004-10: openssl 1.1.1l, so not affected
* 202004-13: git 2.26.3, so not affected
* 202005-02: qemu 5.2, so not affected
Add the following entries to the GLSA allow list.
* 202006-03: perl 5.26.2, only SDK, allowlist
* 202008-01: python 2.7.15 & 3.6.5, only SDK, allowlist
* 202101-18: python 2.7.15 & 3.6.5, only SDK, allowlist
* 202104-04: python 2.7.15 & 3.6.5, only …
> build_library: update allow list for GLSA checks 2021-09-03

- jenkins/kola/Dockerfile.kola-test-runner
- jenkins/kola/qemu_common.sh
- jenkins/kola/qemu_uefi.sh
- jenkins/kola/qemu_uefi_arm64.sh
This PR introduces a script that runs qemu_uefi arm64 tests through a docker container instead of in a Flatcar SDK. The entrypoint uses the jenins paramter 'NATIVE_ARM64' to select whether to use the normal path, or the docker path.
> jenkins: add script to run kola arm64 tests under docker

- build_library/build_image_util.sh
acct-user and acct-group categories aren't licensed too.
CI: http://localhost:9091/job/os/job/manifest/3693/cldsv/
> build_library: Ignore more categories in write_licenses

- jenkins/kola/packet.sh
The cl.basic and cl.internet tests are different tests which wasn't
clear before. Also, the grep process returns an exit code of 1 if it
didn't find a match, causing the job to cancel. The list of tests is
space separated and should not be quoted but on the other hand, we
do have to handle a literal *.
Look for the right test and handle the grep exit code, and disable
globs for the subshell for preserving a literal *.
Pick to all channels
Local execution of the command pipe with cl.internet as argument and without, and checking that it has a 0 exit code.
> jenkins/kola/packet.sh: fix check for skipping machine type tests

- build_library/board_options.sh
- build_library/release_util.sh
- build_torcx_store
- common.sh
- jenkins/images.sh
- jenkins/packages.sh
- jenkins/vms.sh
With the migration to bash 5.1, RETURN traps have been not functioning ideally. This PR majorly focuses on fixing those traps by emulating the same with EXIT trap inside a subshell.
```
emerge-amd64-usr app-shells/bash
```
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/3686/cldsv/
To be merged with https://github.com/flatcar-linux/coreos-overlay/pull/1313
> Fix the traps to align with bash 5.1 upgrade

- jenkins/manifest.sh
To be merged with https://github.com/kinvolk/jenkins-os/pull/166, we now use gsutil to download SDK version.
> jenkins/manifest: use gsutil to download SDK version

- jenkins/kola/packet.sh
Equinix Metal ARM server are not yet hourly available in the default `sv15` region
so we override the `PACKET_REGION` to `Dallas` since it's available in this region.
We do not override `PACKET_REGION` for both board on top level because we need to keep proximity
for PXE booting.
To be merged with https://github.com/flatcar-linux/mantle/pull/257
> kola/packet: override EM region for ARM64 server

- build_library/set_lsb_release
Flatcar is in the NIST CPE dictionary. Let's programmatically build the
`CPE_NAME` in the build process in order to be scanned.
`CPE_NAME` is part of `/etc/os-release` with the following manual entry:
```
CPE_NAME=
A CPE name for the operating system, in URI binding syntax, following the Common Platform Enumeration Specification[2] as proposed by the NIST.
This field is optional. Example: "CPE_NAME="cpe:/o:fedoraproject:fedora:17""
...
[^2]: Common Platform Enumeration Specification
http://scap.nist.gov/specifications/cpe/
```
Which indicates that the current version of CPE is 2.3.
Closes: https://github.com/flatcar-linux/Flatcar/issues/536
<hr>
CI: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/4230/cldsv/
Output …
> build_library/set_release: add CPE_NAME - v2.3

- jenkins/kola/packet.sh
We override `PARALLEL_TESTS`, because kola run with `PARALLEL_TESTS` >= 4 causes the tests to provision >= 12 ARM servers at the same time.
As the da11 region does not have that many free ARM servers, the whole tests will fail.
With `PARALLEL_TESTS=2` the total number of servers stays < 10.
In addition, we override `timeout` to 10 hours, because it takes more than 8 hours to run all tests only with 2 tests in parallel.
> jenkins: override PARALLEL_TESTS for ARM servers in da11

- changelog/bugfixes/2021-12-09-jenkins-arm64-beta.md
- jenkins/release.sh
Now that arm64 images are available for Beta channel, we need to also add arm64 to Beta boards.
See also https://github.com/flatcar-linux/Flatcar/issues/570 .
After merging the PR, we should actually run again `os/release` of Jenkins.
> jenkins: make release.sh publish arm64 for Beta

- changelog/bugfixes/2021-12-10-jenkins-arm64-stable.md
- jenkins/release.sh
From flatcar-3033 on, arm64 images are available for Stable channel, we need to also add arm64 to Stable boards.
> jenkins: make release.sh publish arm64 for Stable

- build_library/catalyst_sdk.sh
- build_library/update_chroot_util.sh
- changelog/changes/2021-12-10-python-update.md
- update_chroot
And set it to remove some old version of dev-python/setuptools_scm
package.
Also sets the default python interpreter to python3.
This should be merged together with with https://github.com/flatcar-linux/portage-stable/pull/214 and https://github.com/flatcar-linux/coreos-overlay/pull/1277.
CI: http://localhost:9091/job/os/job/manifest/4229/cldsv/
> Python transition: add a way to remove hard blockers and default to python3 interpreter

- bootstrap_sdk
- build_library/build_image_util.sh
- build_library/dev_container_util.sh
- changelog/bugfixes/2021-12-22-fix-dev-container.md
Stop relying on github redirects, they are a mixed blessing and using
them broke emerge-gitclone inside dev-container in silent way. The
script could not find a desired revision of portage-stable or
coreos-overlay, because it tried to pull from kinvolk instead of
flatcar-linux github org. The redirects seem to hinder fetching a
specific commit, so the script pulled something else (HEAD or main?).
CI: http://localhost:9091/job/os/job/manifest/4445/cldsv/
Fixes https://github.com/flatcar-linux/Flatcar/issues/577
> *: Replace kinvolk github org with flatcar-linux

- changelog/README.md
The changelog entries should be directly used for the release notes, thus they need to be short and hold only information relevant to the end user, and should be in the markdown bullet point format.
> changelog/README.md: describe purpose of the changelog entries

- build_packages
In 9fba5789f95bf79a393c5e35cb2346d3900e29ba we introduced  `--torcx_output_root` as an optional command line parameter and had it default to `${DEFAULT_BUILD_ROOT}`, inadvertently  diverging from the previous default, which was `${DEFAULT_BUILD_ROOT}/torcx`.
This change sets the correct default root `${DEFAULT_BUILD_ROOT}/torcx` to bring `build_packages` back into alignment with `build_image` (as well as the lower level `build_torcx_store`).
This change should be cherry-picked into the release branches flatcar-3033, flatcar-3066, and into the upcoming Alpha release branch.
> build_packages: fix default torcx output root

- run_sdk_container
`run_sdk_container` uses the sourcetree version to decide whether to re-use existing containers or create new ones. However, containers were not matched by exact name - instead, plain `--filter name="..."` was used, leading to prefix matching. This change updates `name="..."` to use regular expressions for exact matching.
This change should be cherry-picked into the release branches flatcar-3033, flatcar-3066, and into the upcoming Alpha release branch.
> run_sdk_container: use exact match for existing containers

- ci-automation/ci_automation_common.sh
For test builds the commit that updates the submodules can be free-
standing but for releases we need to push it to the branch and also
sign the tag.
Add optional arguments that are used by the tag-release script in
flatcar-build-scripts.
Port to all active branches (except flatcar-lts-2605)
None
> ci-automation: allow to optionally push and sign the commit

- sdk_lib/sdk_entry.sh
For execution of the compiled binaries in /build/arm64-usr we rely on
qemu-user binfmt emulation and have to tell it where the root is with
QEMU_LD_PREFIX because build systems don't chroot into /build/arm64-usr
themselves (which also works just by chance on amd64 because we have
similar glibc versions and so on). The env var setup was done in
/etc/profile.d/qemu-aarch64.sh but is now not read anymore since the
container runs the shell not as login shell.
Add the login options to the bash and su calls when starting the
container.
Check that `env` really prints out `QEMU_LD_PREFIX=/build/arm64-usr/`
Backport to all active branches
Manual edit of the file
> sdk_lib/sdk_entry.sh: use a login shell to source /etc/profile

- run_sdk_container
- sdk_lib/sdk_entry.sh
This change ensures the binpkg host is updated if the board (OS) version differs from the SDK version.
This is to ensure /build/[arch] uses the correct binary package cache.
The change aims to address an [issue](https://github.com/flatcar-linux/flatcar-docs/pull/195#discussion_r778978471) uncovered by @pothos while reviewing documentation changes.
Also, a minor one-line change in `run_sdk_container` reduces the shutdown time of the SDK container, fixing a 10s lag when exiting the SDK.
> sdk_entry.sh: ensure currect binpkg host

- build_sdk_container_image
- run_sdk_container
- sdk_lib/sdk_container_common.sh
When the docker wrapper script for Podman is used, we need to
explicitly create a root user container with "sudo podman".
Podman also has its own bridge for root user containers which we need
to detect.
Add a "$docker" variable that uses sudo as needed, and also check which
bridge interface to use.
Port to all active branches (except flatcar-lts-2605)
Used it for both regular container starts and the building of the SDK container (still running, though)
> run/build_sdk_container: support Podman

- sdk_lib/sdk_entry.sh
The creation of the target version file failed:
/home/sdk/sdk_entry.sh: line 32: /build/amd64-usr/etc/target-version.txt: Permission denied
Use root permissions to create the file.
Port to 3033 and 3066 branches
None
> sdk_lib/sdk_entry: handle permission error for target version file

- build_sdk_container_image
At least with Podman it's not possible to call "container rm" on a
running container without the force flag.
Add the force flag which is also used elsewhere already.
port to flatcar-3033 and 66
Manual removal worked with the flag
> build_sdk_container_image: force removal of running container

- sdk_lib/Dockerfile.sdk-import
- sdk_lib/sdk_entry.sh
In PR #201 we added a call to setup_board to the SDK entry point sdk_entry.sh. Since we make use of sdk_entry.sh during the SDK container build, this inadvertently led to setup_board being called before update_chroot ran.
This fix adds a check to sdk_entry.sh and only calls setup_board when `/build/...` exists. Additionally, it updates `sdk_lib/Dockerfile.sdk-import` to switch to the root user by default since `sdk_entry.sh` expects to be run as root.
Supersedes https://github.com/flatcar-linux/scripts/pull/204.
The fix should be cherry-picked to flatcar-3033 and flatcar-3066, too.
> fix sdk_entry.sh setup_board fallout

- jenkins/kola/azure.sh
Takes advantage of the new kola parameter `--azure-use-gallery`.
Manually for now.
Manual testing.
> jenkins/kola/azure: make use of --azure-use-gallery parameter

- checkout
Helper script to check out branches and tags and keeping submodules in sync.
Usage:
`./checkout <tag-or-branch>`
The tool will guess whether a tag or branch was specified, with tags taking preference over branches of the same name.
For branches, the tool will check out the branch in both submodules too, and by default pull / rebase changes from origin.
Tags will be checked put in `scripts` only, and submodules will be updated (i.e. a tag is expected to have the correct submodule pinnings).
This should be cherry-picked to flatcar-3033 and flatcar-3066, too.
> checkout: helper script for checking out branches and tags

- build_image
- build_library/toolchain_util.sh
- ci-automation/README.md
- ci-automation/garbage_collect.sh
- ci-automation/push_pkgs.sh
- common.sh
- set_version
- settings.env
This change adds a job for publishing binary packages to the build cache server to the ci automation.
Also, setup_board is updated to use the buildcache package cache if a nightly build version is detected.
I used the opportunity to also clean up the various references to mirror.release.flatcar-linux.net scattered across the scripts and put these into a centralised env file.
This change should also be cherry-picked to flatcar-3033 and flatcar-3066.
> ci-automation + setup_board: publish and use binpkgs

- ci-automation/garbage_collect.sh
`garbage_collect.sh` [was using 'docker_vernum'](https://github.com/flatcar-linux/scripts/blob/main/ci-automation/garbage_collect.sh#L92) where it should have been using 'vernum' (as [`push_pkgs.sh`](https://github.com/flatcar-linux/scripts/blob/main/ci-automation/push_pkgs.sh#L64) does).
Also, make sure release directories are removed, not just packages.
This fix should be cherry-picked to 3066 and 3033.
> ci-automation/garbage_collect: fix binpkg url

- checkout
The `checkout` helper erroneously checked for tags in submodules. This isn't necessary since tags are expected to pin submodules.
> checkout: omit checking for tags in submodules

- build_library/check_root
Ignore the broken '/usr/lib64/python3.9/site-packages/certifi-3021.3.16-py3.9.egg-info' symlink when building for GCE.
```
./build_image --board=amd64-usr
./image_to_vm.sh --format gce --board=amd64-usr
```
```
./build_image --board=amd64-usr
./image_to_vm.sh --format gce --board=amd64-usr
```
> build_library/check_root: ignore dangling '*egg-info' symlink

- ci-automation/garbage_collect.sh
- ci-automation/push_pkgs.sh
- settings.env
The original intention of the "binpkg" prefix in the CI binary package cache URL was to separate packages from other build artifacts like containers, images, and SDK tarballs. Motivation was to separate developer content (binary packages) from CI automation artifacts (everything else); since binary packages are not used by the CI.
This broke assumptions in scripts which use the binary host URL for other things than packages - e.g. SDK tarballs or images. These scripts would get a bincache URL with "binpkg/" prepended, while CI automation would *not* use that prefix.
This change removes the use of "binpkg/" altogether since it would not work as intended without more significant changes to build scripts.
This PR should be cherry-picked to all active release branches (likely flatcar-3033, …
> settings / ci-automation: remove "binpkg" prefix

- build_library/set_lsb_release
- changelog/changes/2022-01-11-etc-flatcar-update-conf.md
The default image group is already encoded in
/usr/share/flatcar/update.conf but it was written to
/etc/flatcar/update.conf as well. This can cause problems when the user
switches channels by forcing an update to a specific release from the
different channel (e.g., through the flatcar-update tool) as it leaves
the file under /etc/flatcar/update.conf out of sync with the new
channel version in /usr/share/flatcar/update.conf.
Since we don't really need to write a specific channel to /etc on new
images as we can rely on the value from /usr, we now leave any possible
overwriting of the value in /etc entirely to the user.
Scheduled test build and checked that the resulting image has the file missing as expected
> set_lsb_release: only set update-engine GROUP in /usr, not /etc

- build_library/toolchain_util.sh
- sdk_lib/sdk_entry.sh
This PR includes the remainder of changes necessary to use binary packages for nightly build tags, directly from the bincache server.
PR should be back-ported to flatcar-3033, flatcar-3066, and flatcar-3115. SDK containers for all 3 releases should be re-built and pushed to ghcr.io to make use of this change.
Tested locally with `beta-3066.1.0-nightly-20220112-0139`.
> SDK container: enable binpkg cache for nightly builds

- build_library/torcx_manifest.sh
- build_torcx_store
Packages installed inside a torcx package where missing from the final image package list file that we provide along with the image. Add torcx components to the image package list.
`./build_packages && ./build_image` and then inspect `flatcar_production_image_packages.txt`.
Checked that `app-emulation/containerd` shows up in `flatcar_production_image_packages.txt`.
> list torcx components in package list

- build_library/vm_image_util.sh
- changelog/changes/2022-02-01-azure-fixed-vhd.md
Azure requires disks to be fixed-size VHD files when uploading to blob storage
in order to create image/gallery objects from them. This is documented here[1].
To prevent mistakes from happening create disks in that format directly so that
any azure compatible tool can upload them, though azcopy is recommend because
it handles their sparseness best.
This has not been an issue for us so far because kola uses code from an older
utility that transparently handled the dynamic-to-fixed-size conversion for VHD
files (azure-vhd-utils). But people working with these things for the first
time fall into this trap.
[1]: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/create-upload-generic#resizing-vhds.
```./image_to_vm.sh --format=azure```
```
$  ls -lah …
```
> build_library: vm_image_util: create fixed-size VHDs for Azure

- jenkins/kola/dev-container.sh
The default branch of both repos, coreos-overlay and portage-stable, should be `main`.
If we checkout `master` branch, which contains invalid source code that was deprecated many years ago, the build could sometimes fail, e.g. when trying to build perl 5.26.2 with gcc 10.
Simply delete the code checking out branches, as the part is already being handled in `emerge-gitclone`.
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/4782/cldsv
-  Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update) - not needed as it is not an user-facing issue.
> jenkins: do not check out branches of coreos-overlay and portage-stable

- jenkins/kola/packet.sh
Follow-up of:
* https://github.com/flatcar-linux/mantle/pull/288
* https://github.com/flatcar-linux/Flatcar/issues/527
> jenkins/kola: use httpS URL for PXE boot

- jenkins/images.sh
Often a change results in unexpected effects on the image, e.g., when
a wrong package version gets chosen or the package installs files under
/etc, or binaries of library dependencies get pulled in. Besides
inspecting the image manually, the package-diff tool also gives
valuable insights.
Run the package-diff tool in a comparison to the last release and print
the image URL alongside for convenience.
Port to all channels
[Looked at Jenkins job output](http://jenkins.infra.kinvolk.io:8080/job/os/job/board/job/image-matrix/6931/console)
> jenkins/images: print out image diff report

- build_library/test_image_content.sh
- common.sh
Clean up following entries from the GLSA allow list.
* 201908-24: polkit 0.120-r2, so not affected
* 201909-01: perl 5.34.0, so not affected
* 202003-26: python 3.9.8, so not affected
* 202005-09: python 3.9.8, so not affected
* 202006-03: perl 5.34.0, so not affected
* 202008-01: python 3.9.8, so not affected
* 202101-18: python 3.9.8, so not affected
* 202104-04: python 3.9.8, so not affected
* 202105-34: bash 5.1_p8, so not affected
* 202107-31: polkit 0.120-r2, so not affected
* 202107-48: systemd 250.3, so not affected
Also replace `blacklist` with `denylist`, and `whitelist` with `allowlist`.
This PR should be merged together with https://github.com/flatcar-linux/portage-stable/pull/289.
CI passed: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/4867/cldsv
- Changelog …
> build_library: update allow list for GLSA checks 2022-02-16

- sdk_lib/Dockerfile.sdk-update
- sdk_lib/sdk_container_common.sh
- update_sdk_container_image
This change introduces update_sdk_container_image, a script to generate a new SDK container image based on an existing SDK container. The script is meant to be used for minor / patch level SDK changes (like test suite updates).
> update_sdk_container_image: New SDK container from existing image (minor / patch updates)

- ci-automation/garbage_collect.sh
- ci-automation/packages.sh
- ci-automation/test.sh
This change adds copying test results to the build cache server, and adds respective deletion to the garbage collector.
Also, the patch fixes an issue with torcx publishing (manifest publishing had arch hard-coded).
> ci-automation: publish test results, add to GC

- ci-automation/test_update_reruns.sh
Fixes `ci-automation/test_update_reruns.sh: line 25: version: unbound variable` observed in today's nightlies' containerised tests.
This PR should be cherry-picked to flatcar-3033, flatcar-3066, and flatcar-3139 after merge.
> ci-automation: fix test_update_reruns typo

- ci-automation/ci_automation_common.sh
- ci-automation/sdk_bootstrap.sh
This change has sdk_bootstrap push the branch to origin when run from the main branch, updating the SDK and OS version in 'main' for each SDK bootstrap build.
Release / maintenance branches have the SDK version set in the versionfile at release time. But main is never updated.
Updating the versionfile in main when a new SDK is built ensures that dev branches based on main will also use the correct SDK version (e.g.in subsequent CI builds). As an example, this PR makes changes like these: https://github.com/flatcar-linux/scripts/pull/235/files#diff-48b3a88e2d986f5123acefc4dd59b5e6ae86f45975cc28e105e3ed1b3815f420L4 unnecessary.
Note this change implies we'll have one automated commit each night in our main branch, from the nightly build.
As a (positive) side effect this will also update …
> ci-automation: SDK build updates version.txt in main branch

- ci-automation/vendor-testing/qemu_update.sh
- ci-automation: add missing update test
The kola update test was missing. It is performed as update from the
old image to the newly built payload to ensure that the new image is
compatible for old clients.
pick for stable/beta/alpha
[passed](http://jenkins.infra.kinvolk.io:8080/job/_testing_/job/container-test/job/test/71/console)
> ci-automation: add update test

- ci-automation/image.sh
- ci-automation/vendor-testing/qemu_update.sh
- jenkins/images.sh
- sdk_lib/sdk_container_common.sh
- jenkins/images: find channel from base channel variable  
Using the tags on the branch is not enough to find the channel we want
to be the dev build be related to.
Use the base channel variable which was introduced for this.
- ci-automation: set the channel from the git tag
For now we had only "developer" images in the new pipeline.
Based on the git tag like "alpha-1234.0.0" set the channel (group) for
the image and also use this logic when finding the channel in the QEMU
update test.
Port to all channels
The first change fixes the package-diff comparison that sometimes failed (for dev builds and for release builds). The second is for being able to build a release image in the new pipeline (a first step towards making releases from it). …
> Fix and improve channel handling

- build_library/build_image_util.sh
- build_library/dev_container_util.sh
- build_library/modify_image_util.sh
- build_library/prod_image_util.sh
- build_library/release_util.sh
- build_library/vm_image_util.sh
- changelog/changes/2022-02-22-configurable-image-compression.md
- jenkins/vms.sh
This change adds a new flag called --image_compression_format which allows us to output the final VM image as one of the supported formats: bz2 (default), gz, zip or none
If the compression format is "none" or "", the image will not be compressed.
This change also enables the CI to output OpenStack images using ```gzip``` compression instead of ```bz2```. 
Fixes https://github.com/flatcar-linux/Flatcar/issues/575
Simply add ```--image_compression_format=gz``` when calling ```image_to_vm.sh```. Leaving this option unset will preserve the current behavior.
These changes were tested by specifying all supported formats as well as arbitrary bogus strings. The results were as expected. Success on any of the supported formats, error on anything else. Image archive as well as legacy digest files …
> Make image compression format configurable

- ci-automation/tapfile_helper_lib.sh
Move the final db commit to inside the subshell. Since the while loop
runs inside a subshell, the SQL variable outside of the subshell is not
modified, and so the last contents of the SQL variable are dropped. This
shows up when the last couple test cases don't have an error message,
and simply append the transaction to 'SQL'. They are never written to
the db.
Before this commit: http://jenkins.infra.kinvolk.io:8080/job/_testing_/job/container-test/job/test/228/console. Notice that a single job failed in run 1, and is retried indefinitely because in all other runs because it produces no output.
With this commit: http://jenkins.infra.kinvolk.io:8080/job/_testing_/job/container-test/job/test/229/console
> ci-automation/tapfile_helper_lib: fix commiting last transaction

- ci-automation/tapfile_helper_lib.sh
This change removes all non-ASCII characters from test debug / error output when ingesting the output for inclusion in the TAP report. Jenkins TAP parser does not handle some unicode chars, leading to tap parser errors with e.g. Cilium output (which uses unicode).
Needs to be cherry-picked to flatcar-3033, flatcar-3139, and flatcar-3165.
> ci-automation/tapfile_helper_lib.sh: only ASCII chars

- ci-automation/test.sh
Pass PARALLEL_TESTS to the SDK container if it is set before running tests. Since the tests are started in the container, we need to make available the variable inside the container.
Needs to be cherry-picked to flatcar-3033, flatcar-3139, and flatcar-3165.
> automation/test.sh: pass PARALLEL_TESTS to container

- ci-automation/image.sh
The image needs to be set into official mode through a helper script
(see jenkins/images.sh) and the COREOS_OFFICIAL variable needs to be
set for prod_image_util.sh/build_image_util.sh/grub_install.sh.
Pick for alpha, beta, stable
[passed](http://jenkins.infra.kinvolk.io:8080/job/_testing_/job/container-test/job/packages/993/cldsv/) and `/usr/share/update_engine/update-payload-key.pub.pem` is present while `update-payload-key.key.pem` is absent on the image because coreos-au-key got rebuild in the image job with the flag "official"
> ci-automation: set images as official based on version

- jenkins/images.sh
Sometimes the Linux build system changes and results in unexpected
kernel config results.
Print changes in the kernel config as part of the image diff report.
See output at end of image matrix job
Pick for all channels
None
> jenkins/images: print kernel config changes

- jenkins/kola/aws.sh
- jenkins/kola/packet.sh
There was a regression for an instance type which could have been
prevented by testing.
Add the same extended test logic used for Equinix Metal to AWS.
Expected to fail due to https://github.com/flatcar-linux/Flatcar/issues/665
Port to all channels
[done](http://jenkins.infra.kinvolk.io:8080/job/os/job/kola/job/aws/1240/console)
> jenkins/kola/aws: run tests on additional instance types

- ci-automation/tapfile_helper_lib.sh
Jenkins TAP file parser does not process non-printable ASCII characters but bails out. This change removes all ASCII < 0x1F, so non-printable characters are not included in the TAP report.
Fixes
```
...
Caused by: unacceptable character '' (0x1B) special characters are not allowed
...
```
> ci-automation/tapfile_helper_lib.sh: remove non-printable ASCII

- run_sdk_container
In our CI most uses of run_sdk_container pass the '-C image' flag, which broke
with the last change, due to unbound docker_sdk_vernum variable. Skip fetching
the image when custom_image is passed.
Fixes #259
> run_sdk_container: skip fetching image if custom_image is requested

- build_library/check_root
- build_library/set_lsb_release
- jenkins/images.sh
together with https://github.com/flatcar-linux/coreos-overlay/pull/1713
see linked PR
↑ one in coreos-overlay
> Support split lib and lib64 layout

- ci-automation/test.sh
Export PARALLEL_TESTS in the container's .env file to ensure it is passed to the vendor script.
Should be cherry-picked to all release branches (3033, 3139, and 3165/3185).
> ci-automation/test.sh: export PARALLEL_TESTS

- bootstrap_sdk
This change updates the documentation at the top of the script, calling out the limitations of stage1 (no stage isolation) early to avoid confusion.
> bootstrap_sdk: improve stage1 description

- ci-automation/ci-config.env
- ci-automation/test.sh
Remove passing of `PARALLEL_TESTS` because it really should be done by the CI. Add documentation in `ci-config.env` on how to pass variables into the SDK container.
Should be cherry-picked to 3033, 3139, 3185.
> ci-automation/test.sh: remove PARALLEL_TESTS passing (move to CI)

- ci-automation/README.md
- ci-automation/ci_automation_common.sh
- ci-automation/garbage_collect.sh
- ci-automation/packages.sh
- ci-automation/sdk_bootstrap.sh
The pipeline created two tags if an SDK was built, one for the SDK and
one for the OS build (which was a free-standing tag or a local state
that was equivalent to the existing tag of the same name). The
nightlies created update commits on the main branch, even if no change
was done, and on the release branches we lacked these commits.
Create the release tag in the nightly SDK bootstrap already and reuse
it for the nightly OS build. Instead of local state, checkout the
existing tags explicitly. Extend the nightly update commit logic to
cover release branches and detect if we can skip building because no
changes were done.
Needs Jenkins change to pass the regular version to the packages downstream job
Port to Stable/Beta/Alpha channels
Test case 1: simulating a nightly build of main with an …
> ci-automation: use a single git tag and skip nightlies with no changes

- jenkins/kola/gce.sh
GCP Pro is failing because hostname is > 63 char:
```
Apr  5 19:52:27.522820 kubelet[1762]: E0405 19:52:27.522513    1762 kubelet_node_status.go:93] "Unable to register node with API server" err="Node \"jenkins-gce-pro-5-91a967ef5450cb932bc5.c.flatcar-212911.internal\" is invalid: metadata.labels: Invalid value: \"jenkins-gce-pro-5-91a967ef5450cb932bc5.c.flatcar-212911.internal\": must be no more than 63 characters" node="jenkins-gce-pro-5-91a967ef5450cb932bc5.c.flatcar-212911.internal"
```
Let's remove `jenkins` and `gce` from the hostname, these
information are not critical for debugging purposes.
Hostname should now looks like
"basic-5-91a967ef5450cb932bc5.c.flatcar-212911.internal" or
"pro-5-91a967ef5450cb932bc5.c.flatcar-212911.internal"
Signed-off-by: Mathieu Tortuyaux …
> kola/gce: shrink hostname to be lower than 63 char

- ci-automation/vms.sh
this is required to keep "packet" in the SDK linguo while the user can
use "equinix_metal" term.
> ci-automation/vms: rename equinix_metal to packet

- jenkins/formats-arm64-usr.txt
Azure ARM64 instances entered preview, so produce images for them regularly
with every release now. Flatcar has supported Azure ARM64 since the first
release with the 5.15 kernel, which was something like 3139.0.0.
> jenkins: add azure_gen2 to arm64 formats

- .github/workflows/mantle-releases-main.yml
- ci-automation/ci_automation_common.sh
- ci-automation/test.sh
- sdk_container/.repo/manifests/mantle-container
The SDK container does not exist for arm64 and is quite heavy. We
currently also resort to a unconditional rebuilding of mantle inside
the SDK.
Use the new mantle container image to run kola tests, and pin its
version through a text file that gets updated by GitHub Actions.
Port to flatcar-3139, flatcar-3185, flatcar-3200
- GitHub Action PRs were created as expected: https://github.com/pothos/scripts/pulls
- arm64 qemu(_update) tests passed on the arm64 Jenkins build executor
- amd64 qemu(_update) tests passed
↑ not needed
> Run CI container pipeline kola tests with the new mantle image

- ci-automation/test.sh
We are not using SDK container for running the tests any more - it was
replaced with mantle container. Update the docs accordingly.
> ci-automation: Update test.sh script docs

- jenkins/images.sh
- jenkins/kola/dev-container.sh
- jenkins/packages.sh
- jenkins/sdk.sh
- jenkins/toolchains.sh
- jenkins/vms.sh
These scripts happened to use the copy of gangue in the SDK which isn't
expected because it should use the binaries complied by Jenkins.
pick for all channels
Goes with https://github.com/flatcar-linux/coreos-overlay/pull/1827
see linked PR
↑ not needed
> Use gangue compiled from Jenkins

- jenkins/kola/qemu.sh
This ports a similar change from "main" to create the directory for
amd64 if it doesn't exist because mantle is not installed in the SDK.
[started](http://192.168.42.7:8080/job/os/job/manifest/5510/cldsv/)
> jenkins/kola/qemu.sh: create missing folders

- ci-automation/garbage_collect.sh
- ci-automation/garbage_collect_cloud.sh
The garbage collect job should also clean up kola resources if a test
job failed to do so due to forced terminator or misbehavior. The
cleanup is done by "ore" which needs credentials like kola.
Run ore from the mantle container image. Unfortunately Docker does not
support Podman's --env-host option and the env vars had to be passed
explicitly. While --env-file=<(env) would work it contains a lot of
variables that cause the container to behave a bit weird.
[here](http://192.168.42.7:8080/job/container/job/garbage_collect/33/console)
↑ not needed
> ci-automation/garbage_collect: clean up kola cloud resources

- build_library/vm_image_util.sh
- jenkins/formats-amd64-usr.txt
There is no difference anymore between the regular and Pro images.
Remove the definitions and stop building extra images.
Backport down to flatcar-3033
none
↑ not needed because the images weren't consumed directly but through the Marketplace offers which use the regular image now
> Remove unused image variants

- jenkins/kola/packet.sh
With the limit of 2 parallel tests, meaning 6 machines, the test time
is ~10 hours which is longer than the GC time. It seems that the
regional capacity is not so limited at the moment and we can try to
increase the number of machines.
Adjust the timeout to reflect the GC time and increase the parallel
tests to 3, meaning 9 machines.
pick for all channels
none
> jenkins/kola/packet: try to reduce test time by increasing parallelism

- ci-automation/ci-config.env
- ci-automation/vendor-testing/gce.sh
- ci-automation: add GCE image test
The GCE image test runs on a single instance type for now. In the
future it would be good to test the new NIC type with the cl.internet
test.
PR for ore gc invocation in garbage collection job is here: https://github.com/flatcar-linux/scripts/pull/306
Requires https://github.com/flatcar-linux/mantle/pull/328
Backport to all channels (incl. 3033)
Closes: https://github.com/flatcar-linux/Flatcar/issues/670
[here](http://192.168.42.7:8080/job/container/job/test/246/console)
> ci-automation: add GCE image test

- .github/workflows/mantle-releases-main.yml
The new LTS release will use the mantle container image.
Add automation to keep it up to date.
Merge when LTS 2022 is released
> .github: Update LTS mantle reference

- ci-automation/test.sh
- ci-automation/vendor-testing/equinix_metal.sh
- ci-automation/vendor-testing/gce.sh
- ci-automation/vendor-testing/qemu.sh
- ci-automation/vendor-testing/qemu_update.sh
- ci-automation/vendor_test.sh
~Move the common setup to the test_vendor.sh script, which will then
source the vendor script.~
Move the common setup to the vendor_test.sh script, which will be
sourced by the vendor scripts.
With this PR I'm trying to fix the following issues:
- Stop repeating the same code in every vendor test (taking the parameters, creating the directory, entering it, calling `basename $0` to get the test script name, and so on). With this PR, the vendor scripts can assume being in the expected directory already and can use the provided variables instead of hardcoding them (like `../torcx-manifest.json`).
- Make channel information reliably available (so it works in my git-worktree based setup too).
- Drop unnecessary noglob settings.
- Drop unnecessary sudo before calling kola.
Tested with qemu. …
> ci-automation: Reduce boilerplate in vendor tests

- ci-automation/ci-config.env
- ci-automation/vendor-testing/vmware.sh
This is to close https://github.com/flatcar-linux/Flatcar/issues/672.
~Does not work, feel free to pick it up.~ To test:
- Prepare the config file for kola. It's the secret sauce. It looks more or less like the following:
```json
{
"default": {
"user": "USERNAME",
"password": "PASSWORD",
"server": "IP_ADDRESS",
"static_ips": NUMBER,
"first_static_ip": "IP_ADDRESS",
"first_static_ip_private": "IP_ADDRESS",
"gateway": "IP_ADDRESS",
"gateway_private": "IP_ADDRESS",
"subnet_size": NUMBER
}
}
```
- Encode the config file with base64 and put it into `sdk_container/.env` (like `export VMWARE_ESX_CREDS=<BASE64_ENCODED_CONFIG>`).
- From `<SCRIPTS_REPO>` directory do:
- `bash` (this is to avoid losing a bash session and a tab in terminal emulator due to any failure and exit because of `set -e` done …
> [WIP] Vendor test for VMware

- build_library/toolchain_util.sh
This was already being done for gcc but not for binutils. Binutils is
also slotted and when we run the sdk (stage3/stage4) job in the CI, the
seed sdk already contains crossdev packages that we may want to update.
Test together with coreos-overlay#1838, requires at least a stage4 bootstrap.
Still testing.
> build_library/toolchain_util: set binutils to the latest version

- ci-automation/vendor_test.sh
We forgot to clear the array with instance tests to rerun, so the list
grew from one iteration to another when going over all the instance
types. I did not spot it before, because I tested it with only one
extra instance.
> ci-automation: Do not rerun tests on unrelated instances

- jenkins/prerelease/azure.sh
- jenkins/vms.sh
The LTS and Pro feature no longer requires the private bucket
hence we can remove the --private argument to upload
> The LTS and Pro feature no longer requires the private bucket

- ci-automation/ci-config.env
- ci-automation/vendor-testing/azure.sh
WIP PR
To test, I pass the Azure creds via the sdk_container/.env file, and current it fails with the issue
```
2022-04-19T10:10:15Z kola: creating flight for RunTests failed: Uploading blob failed: Parse footer field 'Cookie' failed: Invalid footer cookie data [0 0 0 0 0 0 0 0]
```
> ci-automation/azure: Add initial container tests infra for Azure

- ci-automation/vendor-testing/azure.sh
- jenkins/kola/azure.sh
- jenkins/kola/packet.sh
- jenkins/kola/azure.sh: Align the timeout with the GC duration
The kola test run time shouldn't be longer than the GC duration to
prevent failing tests caused by GC interference.
Align the Azure kola timeout with the GC duration.
- jenkins/kola/packet.sh: Remove hardcoded arm64 parallel test limit
The arm64 tests on EM sometimes hit the timeout.
Remove the hardcoded limit of 3 tests to default to 4 and otherwise
use the overwritten parameter.
- ci-automation/vendor-testing/azure.sh: Align timeout with GC duration
The kola test run time shouldn't be longer than the GC duration to
prevent failing tests caused by GC interference.
Align the Azure kola timeout with the GC duration.
Pick for all channels
None
> jenkins/kola/azure|packet.sh: Remove hardcoded arm64 parallel test limit and align the timeout with the GC duration

- ci-automation/ci_automation_common.sh
- ci-automation/garbage_collect.sh
- ci-automation/gpg_setup.sh
- ci-automation/image.sh
- ci-automation/packages.sh
- ci-automation/push_pkgs.sh
- ci-automation/sdk_bootstrap.sh
- ci-automation/sdk_container.sh
- ci-automation/tapfile_helper_lib.sh
- ci-automation/test.sh
- ci-automation/vms.sh
- sdk_lib/90_env_keep
- sdk_lib/sdk_container_common.sh
For now it relies on the SIGNER environment variable not being empty
to perform the signing.
Comes together with https://github.com/kinvolk/jenkins-os/pull/229.
> ci-automation: Sign the artifacts

- build_library/qemu_template.sh
Line 14; The nproc command is only available on systems with GNU coreutils installed. The getconf _NPROCESSORS_ONLN alternative will work on a wider range of UNIX systems.
Line 114; The mktemp syntax used is not standaard and will only work with the GNU version of mktemp.
Line 159; added hvf (macOS) and tcg (no acceleration) options as a fallback. By doing this qemu-system-x86_64 will try to use kvm, but when it fails try hvf, and when that fails switch to the tcg accelerator.
The proposed change should not change anything on systems where this script already worked, but is should now also work on macOS x86_64 and M1 systems using a recent version of qemu 
Changes tested on MacPro 5.1 running macOS 12.3.1 and QEMU emulator version 6.2.0 and 7.0.0
Also tested on a MacBook Pro 16-inch 2021 …
> Make qemu_template.sh work on macOS

- .github/workflows/ci.yaml
- ci-automation/ci-config.env
Currently the flatcar CI is not publicly viewable. this adds some friction for external contributors, as we rely on someone with access to jenkins, to shuttle information from the CI, into the PR.
This change adds a new workflow, that builds packages, the image and VM images, then uploads the resulting artifacts to github.
This is the first step in creating a set of workflows that are on par with what already exists in Jenkins. Next steps will include:
* Create a workflow that pulls the artifacts that were built, and tests them using Kola
* Create workflows in dependency repos (portage-stable, coreos-overlay), that will trigger a build in this repository with the proposed changes to the dependencies.
The current "glue" CI scripts were used as a base fr this workflow. Initially, this …
> Add CI workflow

- .github/workflows/ci.yaml
Building for the branch push event causes two builds per PR and is not
needed anyway (we have nightly builds for the main branch).
Only consider PR events to trigger the CI build.
> .github: Run CI workflow only for PR events

- ci-automation/vms.sh
In jenkins/vms.sh the Digital Ocean and OpenStack images get also
compressed as gzip.
Do so for the new pipeline, too.
[done here](http://192.168.42.7:8080/job/container/job/packages/680/cldsv/) and checked that the additional gzip images get created for openstack/digitalocean (and get uploaded in https://bincache.flatcar-linux.net/images/amd64/9999.1.2+compression-formats-kai/)
> ci-automation: align VM image compression with existing pipeline

- .github/workflows/ci.yaml
This change will prompt the CI workflow to cancel a currently running job for a PR, if a new push is sent to that PR while the job is till running. This should prevent duplicate jobs running for the same PR simultaneously.
Signed-off-by: Gabriel Adrian Samfira <gsamfira@cloudbasesolutions.com>
> Add concurency setting to CI workflow

- .github/workflows/ci.yaml
- .github/workflows/dispatch-kola-tests.yaml
- .github/workflows/run-kola-tests.yaml
- ci-automation/ci-config.env
- ci-automation/test.sh
- ci-automation/vendor-testing/qemu.sh
- ci-automation/vendor-testing/qemu_update.sh
* Adds a reusable workflow that can run tests
* Adapts the ci.yaml to use reusable workflow
* Creates a new workflow that helps trigger tests using an arbitrary workflow run.
In this PR, the artifact download action is from my own fork, because it includes a fix that streams the artifact directly to disk. The upstream action downloads to memory and also un-archives the artifact in memory, which leads to huge memory usage in our case. I created a PR for this with the upstream project here:
https://github.com/dawidd6/action-download-artifact/pull/175
Signed-off-by: Gabriel Adrian Samfira <gsamfira@cloudbasesolutions.com>
> Make the kola test workflow reusable

- ci-automation/image.sh
- ci-automation/python-bin/python3
The image comparison was done against the old release in the channel
we release to instead of the previous release with the same major
version. This means when a channel transition happens we see a large
diff instead of the diff against the previous release. While not bad
for finding problems, this is normally not needed. However, we want
to have two changelogs generated, one against the old release in the
channel we relese to and one against the previous release with the same
major version when a transition happens. There was no changelog
printing yet, and this is added now.
backport
(when doing https://github.com/flatcar-linux/Flatcar/issues/794 this whole code block should gets its own function)
output is available in the [image …
> ci-automation: Show changes by finding the previous channel

- .github/workflows/ci.yaml
When the specified remote contains a same-named branch as origin,
the checkout fails with "fatal: 'X' matched multiple (Y) remote
tracking branches".
Add the remote name as prefix to make the reference unambiguous.
backport 
Trigger a build manually with a coreos-overlay reference. I guess we have to merge this first and then just verify if we don't want to test on a fork.
> .github: Specify remote when checking out c-o/p-s ref in workflow

- ci-automation/README.md
- ci-automation/packages-tag.sh
- ci-automation/packages.sh
When the build system runs the packages jobs for both architectures in
parallel and has to create a new tag, tagging fails due to the race in
the tagging.
Move the git tagging to its own script that is run from a new top-level
job that starts the packages jobs for both architectures.
backport
I've started a build in Jenkins and it created the `main-9999.0.0-kai-tag-in-packages-all-arch` tag with the desired submodules pinned.
> ci-automation: Move git tagging into own script

- build_library/prod_image_util.sh
This made no difference back when lib was a symlink to lib64, but now that they are separate,
libs belongs in /usr/lib64. This mostly doesn't show up because ldconfig configures the ld.so cache
to include both locations, but when updating from an older release ld.so.cache is out of date.
Unfortunately ld.so.cache does not get updated until after multipathd, which causes
multipathd to dump core. This may also affect other packages that need access to
libgcc early.
See also: https://github.com/flatcar-linux/Flatcar/issues/809
> prod_image_util: extract gcc libs to /usr/lib64

- build_library/build_image_util.sh
- build_library/prod_image_util.sh
Since v0.51.0 syft supports generating parsing the gentoo package
database. This is a first go at integrating that into our image build
process. This doesn't yet include packages inside torcx packages, or the
kernel, or initramfs-only packages.
```
./build_image --board=amd64-usr
ls -la ~/trunk/src/build/image/amd64-usr/latest/flatcar_production_image_sbom.json
```
> add SPDX SBOM generation using syft

- ci-automation/ci-config.env
Recently we changed the region from DA (Dallas) to DC (Washington),
because there are more ARM64 servers available. Reflect this change in
the new pipeline too.
> ci-automation: Sync used EquinixMetal region to use for ARM64 servers

- build_library/build_image_util.sh
- build_library/prod_image_util.sh
- build_library/toolchain_util.sh
- build_toolchains
- setup_board
Enable SLSA provenance report generation by default for board packages (including toolchains). SLSA provenance generation happens through a profile.bashrc file in profiles/coreos/base, it is enabled by defining GENERATE_SLSA_PROVENANCE=true in make.conf (or environment).
Digging deeper, provenance generation is enabled during `./build_packages` but also during `./build_toolchains`, because that is where we get binpkgs for board glibc/gcc and their dependencies (some 23 packages) from. An alternative way is available: `./setup_board --nousepkg --nogetbinpkg --board=amd64-usr` has been revived and can be used to skip `./build_toolchains`.
Build a full image starting from toolchains (or sdk in case of container pipeline).
http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/6068/cldsv/
> generate SLSA provenance by default

- build_library/toolchain_util.sh
This is fixed in crossdev now.
It's a part of toolchain update.
CI passed: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/204/cldsv/
Needs to be merged together with https://github.com/flatcar-linux/portage-stable/pull/351 and https://github.com/flatcar-linux/coreos-overlay/pull/2111.
> build_library/toolchain_util: Drop workaround for building stable gdb

- ci-automation/ci-config.env
- jenkins/kola/packet.sh
The new m3.small instance does not have official Flatcar support yet
but we can already cover it in our PXE boot release tests.
The c3.small instances are legacy and m3.small is the new smallest
type.
- Test that it works
- Backport
started something [here](http://192.168.42.7:8080/job/container/job/test/2076/console)
> Cover Equinix Metal m3.small.x86 instances in release test

- build_packages
- build_torcx_store
- ci-automation/packages.sh
- ci-automation/test.sh
Torcx manifest may contain paths and URLs as locations of
packages. There are two kinds of packages - vendored and
extra. Vendored packages normally have two locations - path to the
directory inside the image where the package is (which is why it's
called vendored), and a URL to the package on some remote
server. Extra packages only have a URL. But the URLs are added only
when we tell the build_torcx_store script to upload the packages at
the same time, which is what the old build pipeline was doing. With
the new pipeline, the upload happens as a separate step, thus the
upload is disabled when invoking build_torcx_store, and so the
packages are not getting URLs set. This change went unnoticed, because
a kola test checking the generated torcx manifest was only checking if
there is at least …
> *: Allow specifying extra URLs for torcx packages

- bootstrap_sdk_container
It should happen after we had a chance of processing input parameters, otherwise we were always operating on empty values which resulted in always having an unofficial build.
> bootstrap_sdk_container: Fix a check for an official build

- .github/workflows/mantle-releases-main.yml
- .gitmodules
- README.md
- bootstrap_sdk
- build_library/build_image_util.sh
- build_library/dev_container_util.sh
- build_library/grub.cfg
- build_library/set_lsb_release
- changelog/README.md
- ci-automation/README.md
- ci-automation/ci-config.env
- ci-automation/image_changes.sh
- ci-automation/packages-tag.sh
- ci-automation/packages.sh
- ci-automation/release.sh
- ci-automation/sdk_bootstrap.sh
- contrib/create-coreos-vdi
- sdk_container/.repo/manifests/mantle-container
- sdk_container/.repo/manifests/os-release
- sdk_lib/sdk_container_common.sh
- sdk_lib/sdk_init_selfcontained.sh
The "flatcar-linux" org will be renamed to "flatcar". For renames, there are no redirections in place and we have to update all links.
I've also found references to the old website domain and broken docs links which I also fixed.
Merge when org rename is done.
(The links in the changelog files are not changed, these must be fixed in the website data, not here because it would trigger them to be included in the next release)
> Prepare github org rename to flatcar

- ci-automation/ci_automation_common.sh
I made a mistake and wrote a version like main-3363-0.0-stuff (note a dash instead of a dot after the first number). Surprisingly the build chugged along just fine almost until the end of the image job - it detected invalid version string when the job wanted to create a version.txt file:
```
ERROR   build_image: script called: build_image '--board=amd64-usr' '--group=developer' '--output_root=/home/sdk/build/images' '--only_store_compressed' '--torcx_root=/home/sdk/build/torcx' 'prodtar' 'container'
ERROR   build_image: Backtrace:  (most recent call is last)
ERROR   build_image:   file build_image, line 196, called: split_ver '3363' 'SPLIT'
ERROR   build_image:   file common.sh, line 192, called: die 'Invalid version string '3363''
ERROR   build_image:
ERROR   build_image: Error was: …
```
> ci-automation: Implement a stricter image version check

- ci-automation/ci_automation_common.sh
- ci-automation/release.sh
The mantle plume tool has two steps, pre-release is the mere upload and release is the publication. In the past this was used to run the tests inbetween but we don't do this anymore.
Run plume pre-release and release in a single job. Since plume can't push to GCS in our case, we upload the files to bincache. Also do the cloudformation update which was previously done in flatcar-build-scripts but could only be run after the sync to Origin. It requires the "aws" tool in the mantle container until we implement this in plume directly.
Fixes https://github.com/flatcar/Flatcar/issues/838
Add the `aws` tool to the mantle container. Add the new credentials to jenkins.
Maybe we can cut a dummy Alpha release and test the pipeline with it? The git tag for the Alpha would have to use this branch.
→ …
> ci-automation/release.sh: Run plume to release cloud images

- ci-automation/ci_automation_common.sh
- ci-automation/packages-tag.sh
- ci-automation/sdk_bootstrap.sh
- sdk_lib/sdk_container_common.sh
Currently we skip the nightly build if there are no changes. This
didn't work well because a new run doesn't fix any failure because the
rerun became a no-op.
Check if the main artifacts we expect from a step are found, as simple
heuristic on whether a rerun is needed.
backport
None
> ci-automation: Don't skip nightly build when the previous one failed

- ci-automation/sdk_bootstrap.sh
FLATCAR_VERSION and FLATCAR_SDK_VERSION are defined in the version
file, so it should be sourced before trying to use those. Here we try
to do it in a limited scope.
Also, SDK container link should use the dockerized version in a
directory name.
Should fix an issue that appeared during nightly:
```
Your branch is up to date with 'origin/main'.
/home/build/workspace/workspace/container/sdk/scripts
jenkins/systemd-run-wrap.sh: line 110: FLATCAR_SDK_VERSION: unbound variable
Finished with result: exit-code
Main processes terminated with: code=exited/status=1
```
> ci-automation: Fix unbound variable errors

- .github/workflows/mantle-releases-main.yml
We can use lts-info to optionally update mantle container in old LTS branch too.
> .github: Use lts-info

- sdk_lib/sdk_util.sh
The bootstrap downloads the previous SDK currently only from bincache but bincache isn't backed up and may be cleaned of old releases. The SDK tar ball is also available on the mirror and allows the bootstrap to succeed without copying the seed SDK to bincache first.
Backport
None
> sdk_lib: Also look at the mirror to download the SDK tar ball

- ci-automation/ci_automation_common.sh
When there is no SDK container image in the registry, the fallback looks at bincache but bincache isn't backed up and may be cleaned of old releases. While this won't be the regular case, the container image registry may be unavailable (or renamed as happened now), or people would like to rerun the image job which relies on the packages container.
None
> ci-automation: Fallback also to the mirror for container download

- ci-automation/ci_automation_common.sh
- run_sdk_container
The container image was only created if it didn't exist locally. This
would result in fixes not being in a downstream job that is scheduled
to a different worker node on Jenkins that has a stale copy.
For the build automation we will now always download the latest
container tar ball based on comparing the image ID from a new artifact,
and for registry images we pull the container image to make sure that
we don't use a stale copy when we rebuild.
Backport
[started](http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/292/cldsv/)
> ci-automation: Ensure to use latest container image

- ci-automation/ci-config.env
- ci-automation/garbage_collect_cloud.sh
- ci-automation/vendor-testing/openstack.sh
Missing link to enable the tests in the Flatcar test suite.
<hr>
Closes: https://github.com/flatcar/Flatcar/issues/785
CI :green_circle: : http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/412/cldsv/
Requires:
- https://github.com/flatcar/mantle/pull/382
> ci-automation: add openstack to tested vendors

- ci-automation/release.sh
A release includes an SDK if its SDK version is the release version. Only then we need to upload a new SDK container image.
CC @tormath1 
Backport (to avoid unnecessary tar ball import, the upload gets skipped anyway)
none
> ci-automation/release: Only upload SDK if a new one was built

- ci-automation/gpg_setup.sh
Add `--batch` to `gpg --import` invocation to unblock arm64 sdk bootstrap job. Without this change, the job fails with:
```
gpg: cannot open '/dev/tty': No such device or address
```
because it wants to print a warning/suggestion to the tty.
Run container/arm64_sdk_bootstrap job.
Successfully ran container/arm64_sdk_boostrap job.
> ci-automation: use --batch when importing gpg key

- ci-automation/vendor-testing/vmware.sh
This gets triggered when the test is rerun and an existing image is reused.
Spotted here: http://jenkins.infra.kinvolk.io:8080/job/container/job/test/3376/console
> ci-automation/vendor-testing/vmware.sh: Fix unbound variable use

- ci-automation/README.md
- ci-automation/ci_automation_common.sh
- ci-automation/image.sh
- ci-automation/packages-tag.sh
- ci-automation/packages.sh
- ci-automation/sdk_bootstrap.sh
- ci-automation/vms.sh
For embargoed releases it is useful to apply patches locally to build with them before they are public. This allows to push the same patches to the repo during the Flatcar release at the embargo lift. The result is the same (as long as the scripts patches did not change parts of the setup logic that was running before they got applied), we can just build earlier and thus do the Flatcar release directly on the embargo lift instead of having to wait with the build because it would require the patches to be in the repos.
Backport to all channels.
Used with the same Jenkins parameters that we used in the old pipeline.
Verified with:
[0001-Test-patch-for-scripts.patch.txt](https://github.com/flatcar/scripts/files/9870461/0001-Test-patch-for-scripts.patch.txt) …
> ci-automation: Support local patches

- ci-automation/vendor-testing/aws.sh
Recently we ran into sporadic corruption issues for AWS EC2 AMIs. We use the streamOptimized VMDK format and it seems to cause problems at the AWS side, regardless if created by qemu-img or vmdk-convert. Switch to using the plain AMI images for uploading as workaround.
If it helps, backport to all branches, retag the new releases
Verified that the Alpha arm64 issue goes away when this patch is used (prepared git ref `kai/aws-ami-plain-test`, [rebuild link](http://jenkins.infra.kinvolk.io:8080/job/container/job/test/3975/console)).
> ci-automation: Use plain AMI image for uploads

- ci-automation/ci-config.env
- ci-automation/ci_automation_common.sh
- ci-automation/packages-tag.sh
- ci-automation/sdk_bootstrap.sh
This will be used for the "run all tests" days in Jenkins. So even if no changes happened since last nightly build, a build will be done and the tests will be run.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/nightly/168/cldsv/
Made on [my test branch with some extra changes for testing](https://github.com/flatcar/scripts/tree/flatcar-999999).
Changes made for testing:
- limited nightly builds to alpha (because today is Tuesday and "run all tests" day today is for alpha channel),
- hardcoded flatcar-999999 scripts branch (can't be krnowak/flatcar-3374-test, for example, this gets checked),
- no packages job gets launched, just a message is printed
- packages tag script returns before modifying versionfile and pushing a new tag
> ci-automation: Add an environment variable to skip build shortcuts

- sdk_lib/sdk_container_common.sh
USE, FEATURES and PORTAGE_NAME were missing. The list is formatted so
to follow the list in 90_env_keep file.
> SDK container: Sync the forwarded env vars

- build_library/build_image_util.sh
- build_packages
- common.sh
We need to fix another symlink created by gcc-config, so extend the function that was doing it for some other links and rename it - it's not about only liblto any more.
Needs to be merged together with https://github.com/flatcar/portage-stable/pull/380 and https://github.com/flatcar/coreos-overlay/pull/2266.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/387/cldsv
> common: Extend liblto link fixup function

- .github/workflows/mantle-releases-main.yml
This is to avoid warnings about deprecated node 12 actions and deprecated save-state and set-output commands.
> .github: Modernize mantle update action

- .github/workflows/mantle-releases-main.yml
The variable is actually lowercase. Not sure how I ended up having uppercase variant of it.
Tested on my fork:
- action run (failed for other branches as I cloned only the main branch): https://github.com/krnowak/scripts/actions/runs/3497360325
- PR: https://github.com/krnowak/scripts/pull/1
> .github: Fix mantle update action

- build_library/test_image_content.sh
Flatcar has `net-fs/samba` 4.15.4-r3, greater than 4.13.8, so it is not necessary to keep GLSA 202105-22 in `GLSA_ALLOWLIST`.
Allow 202209-12 for now, as update to grub 2.06 is still in progress.
This PR should be merged together with https://github.com/flatcar/portage-stable/pull/387.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/422/cldsv/
- Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update) (not needed)
- Inspected CI output for image differences: `/boot` and `/usr` size, packages, list files for any missing binaries, kernel modules, config files, kernel modules, etc. (not needed)
> build_library: add 202209-12 to GLSA_ALLOWLIST

- build_library/catalyst.sh
- setup_board
- update_chroot
When setting up portage configuration, we set up a symlink in `${ROOT}/etc/portage/patches` that points to the coreos/user-patches directory inside the coreos-overlay. That way, we can add our custom patches to coreos-overlay without the need for moving the packages from portage-stable to coreos-overlay only to apply an extra patch.
Should be merged together with https://github.com/flatcar/coreos-overlay/pull/2335.
Tested in the build http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/458. The build itself failed during image generation for unrelated reasons (based on my portage move branch), but it managed to build the SDK with a user patch for gentoolkit. I was able to confirm that my patch was actually applied.
> *: Allow applying user patches

- build_library/catalyst.sh
- build_library/dev_container_util.sh
- update_chroot
Should be merged together with https://github.com/flatcar/portage-stable/pull/398 and https://github.com/flatcar/coreos-overlay/pull/2325.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/513/cldsv/
The "disabled" option was a Flatcar customization in sys-apps/portage. We are trying to move to vanilla portage, so let's see if this will work.
> update_chroot, build_library: Drop repos.conf customization

- build_library/build_image_util.sh
- build_library/check_root
- build_packages
- common.sh
It is not necessary - we carry a patch for gcc-config that makes gcc-config to create proper, relative links. The patch is upstreamed, so it will be eventually dropped.
Should be merged together with https://github.com/flatcar/coreos-overlay/pull/2380.
CI passed: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/525/cldsv/
> Drop a symlink-fixing hack

- build_library/catalyst.sh
- setup_board
- update_chroot
Normally `ln -sf path/to/target at/name` will create a symlink at `at/name` that points to `path/to/target`. But if `at/name` already exists and is a directory or a symlink to some other directory, then this command will create a symlink at `at/name/target` pointing to `path/to/target`. There is an ambiguity between 1st and 3rd form of `ln` (please refer to `man ln` for the available invocation forms). It can be disambiguated by using the `-T` flag to force the 1st form.
In our case, if `/etc/portage/patches` symlink already existed and was pointing to `<coreos-overlay>/coreos/user-patches`, we ended up with a useless symlink at `<coreos-overlay>/coreos/user-patches/user-patches` pointing to `<coreos-overlay>/coreos/user-patches`.
Nothing was really broken, just a useless and harmless …
> *: Fix user-patches setup

- build_library/build_image_util.sh
- build_library/dev_container_util.sh
- build_library/extract-initramfs-from-vmlinuz.sh
- build_library/prod_image_util.sh
This PR makes image job to generate some new report files:
- a "wtd" variant of contents files - these don't have timestamps nor user information, but they have information about device ID and inode, so this will make it easier for the file size accounting scripts to avoid hardlinks as they contribute little to the image size.
- contents files for initrd, both old and wtd variants, so we can use them to show changes inside the initrd. May come in handy when we update toolchain, dracut, bootengine or else.
- disk usage file for production image, so we can replace the size calculation done by package-diff
In order to generate the contents for initrd, I copied the script from flatcar-build-scripts.
Also moved the generation of the report files to the bottom of the `finish_image` function, …
> Update report generation

- ci-automation/image_changes.sh
Tested it locally with #634 and https://github.com/flatcar/flatcar-build-scripts/pull/134.
Will want to backport it to LTS, stable, beta and alpha.
Note that the new functionality is going to work only after we create new releases for the respective branches, so for now, all we will get is some error messages about some files not being found.
> Report file and file size changes in production image and initrd

- ci-automation/vms.sh
Getting the contents of the directory in the buildcache involves using rsync with some ssh invocation to log in as a bincache user. It's not a thing that will work locally unless the user gets ahold of the SSH key allowing the user to log in to buildcache as a bincache user.
Replace it by downloading two files that are actually needed for building vms: an image file and the version file. This just uses curl and is accessible for everyone.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1239/cldsv
Will backport it to other channels.
> ci-automation: Get two files to build vms instead of a whole directory

- ci-automation/release.sh
- ci-automation/test.sh
The get_git_channel function failed to work which resulted in the Alpha release job skipping the AWS publishing for the Alpha channel because it defaulted to the developer channel as fallback when git rejected to work on the directory owned by the build user while running as root user. A new version of git caused this behavior change and also prints an error message that explains to have to set safe.directory.
Set the git config entry safe.directory for the /work path when entering the mantle container where git runs as root while working on the directory owned by the build user.
Either test it by creating a new Alpha release tag that has this change and then rerun the release job from that git tag, or merge, cherry-pick the change, and retag Alpha and rerun the release job from that git …
> ci-automation: Allow git to work on directory owned by other user

- bootstrap_sdk
- build_library/build_image_util.sh
- build_library/catalyst.sh
- build_library/grub_install.sh
- build_library/prod_image_util.sh
- build_library/test_oem_pkgs
- build_library/toolchain_util.sh
- build_library/update_chroot_util.sh
- build_library/vm_image_util.sh
- build_packages
- build_torcx_store
- rebuild_packages
- set_official
- setup_board
- update_chroot
I'd like to see emerge to print the report about what's going to be done and the use flags being enabled/disabled.
There are also some cleanups:
- expand the flags for emerge and catalyst
- even if the long flags for emerge are also quite cryptic, the short ones are still even more so
- changed variables that were used as unquoted strings to arrays
Needs https://github.com/flatcar/portage-stable/pull/416 to be merged first.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/632/cldsv
> Make emerge and catalyst verbose by default

- build_library/dev_container_util.sh
- build_library/toolchain_util.sh
- setup_board
- update_chroot
We were getting a lot of repeated warnings like listed below. It would be nice to quiet them down.
```
WARNING: 'portageq envvar PORTDIR' is deprecated. Use any of 'get_repos, get_repo_path, repos_config' instead.
WARNING: 'portageq envvar PORTDIR_OVERLAY' is deprecated. Use any of 'get_repos, get_repo_path, repos_config' instead.
```
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/649/cldsv/
> *: Try to silence the warnings

- build_library/build_image_util.sh
The existing tmpfile logic took care of folders that the ebuild keepdir directive wanted to exist on the OS. However, files and symlinks were not created, causing them to be missing if we didn't explicitly modify the ebuild files in coreos-overlay to use tmpfiles or patching of paths to be in /usr. We need a logic to provide /etc files from the current /usr partition without getting stale. This can be done best with an overlay mount which requires to keep the original /etc files under /usr.
Move the final /etc folder of the image build to /usr/share/flatcar/etc to serve as lower layer in the overlay. Also remove any state from the rootfs to make sure that we don't rely on it when testing our images before the release. What we get with an overlay mount is essentially a similar behavior to …
> Ship /etc from /usr through an overlay mount

- bootstrap_sdk
Sometimes the modification to stage1 repos is necessary. For example we will need to update baselayout package in stage1, so we get the cleaned up handling of PATH and ROOTPATH, which will allow a newer portage to succeed in calculating dependencies in stage2.
Needed by https://github.com/flatcar/coreos-overlay/pull/2490 and https://github.com/flatcar/portage-stable/pull/423.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/680/console
> bootstrap_sdk: Allow running hooks to modify stage1 repos

- sdk_lib/sdk_util.sh
This seems to be the only place where we are using wget for downloading anything - all other places use curl. Thus switch to curl here too. This also makes the job output much shorter as previously it was spammed with progress reporting.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/714/ (I short-circuited it to stop after the successful download)
> sdk_lib: Use curl for downloading SDK tarballs

- .github/workflows/run-kola-tests.yaml
- ci-automation/ci-config.env
- ci-automation/vendor-testing/qemu.sh
- ci-automation/vendor-testing/qemu_update.sh
For the GitHub CI we have to use --qemu-skip-mangle because the LXC
containers don't have access to loop devices. Running with
--qemu-skip-mangle means that the serial console does not get captured
completely because systemd and dracut messages are missing, and thus we
don't catch these errors in kola.
Make the skipping conditional and use it in Jenkins at least for the
nightlies and releases.
Fixes https://github.com/flatcar/Flatcar/issues/980
Checked that the PR CI uses skip-mangle and Jenkins doesn't.
Test for PR CI here: https://github.com/flatcar/scripts/actions/runs/4511305236/jobs/7943425165
and for Jenkins here: http://jenkins.infra.kinvolk.io:8080/job/container/job/test/8842/console
http://jenkins.infra.kinvolk.io:8080/job/container/job/test/8844/console
> Run kola without --qemu-skip-mangle on Jenkins

- .github/workflows/ci.yaml
- .github/workflows/dispatch-kola-tests.yaml
- .github/workflows/run-kola-tests.yaml
- ci-automation/ci-config.env
- ci-automation/tapfile_helper_lib.sh
- ci-automation/test.sh
- ci-automation/test_update_reruns.sh
- ci-automation/vendor-testing/qemu.sh
- ci-automation/vendor-testing/qemu_update.sh
This PR streamlines Github actions CI builds and makes build steps re-use the build container, saving some build time.
It also adds previously missing artifacts required by the tests. It makes artifact upload more granular, so build logs, images, dev container, and torcx packages can be downloaded individually. It exports torcx tarball and binary packages for successive re-use in the kola tests.
The change also updates the github actions kola test runner workflow to use the new, separated artifacts produced by ci.yaml.
Further, it adds a fix for the devcontainer tests. Devcontainer and bin packages used in the devcontainer tests are now served from a local temporary web server.
The change also adds the qemu_update test and provides the respective update payload.
Also, the tests now use a …
> Github Actions CI: streamline build, export all artifacts required by testing, improve testing

- build_library/build_image_util.sh
We already drop tmpfile rules that we don't need because we ship the files through our /etc overlay. However, some rules weren't dropped because they used tabs and not spaces (/etc/selinux/, /etc/iscsi and /etc/ssl/*).
Also drop rule lines for /etc that use tabs.
Backport to Alpha
[CI](http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1588/cldsv/) passed
Ran `grep -R -P '[CLd][ \t]*/etc/'  /usr/lib/tmpfiles.d/` and saw that it is empty.
`/etc` contents are now reduced to
```
-rw-------.  1 root root  144 Mar 30 13:57 .ignition-result.json
-rw-------.  1 root root    0 Mar 30 12:37 .pwd.lock
-rw-r--r--.  1 root root  208 Mar 30 12:33 .updated
drwxr-x---.  2 root root 4.0K Mar 30 13:57 audit
drwxr-xr-x.  3 root root 4.0K Mar 30 13:57 cni
-rwxr-xr-x.  1 root root …
```
> Drop more tmpfiles rules that cause /etc upcopies

- .github/workflows/run-kola-tests.yaml
This is a one-line fix for the "post test results to PR as a comment" CI feature.
The path of the markdown file to be posted to the PR was wrong.
Should be cherry-picked to to flatcar-3033, flatcar-3549, flatcar-3510, flatcar-3374.
> run-kola-tests.yaml: fix path of PR comment file

- ci-automation/sdk_bootstrap.sh
The two-phase nightly builds create an intermediate tag first, which didn't match the main nightly tag regexp before. Because of that, the commit was not pushed to the main branch. The following final SDK build had a version that matched the regexp, but the last commit (with the intermediate tag on it) wasn't in main, and thus was also not pushed.
Tested the regexp change locally:
```
$ version='main-3581.0.0-nightly-20230421-2100-INTERMEDIATE'
$ [[ "${version}" =~ ^main-[0-9.]+-nightly-[-0-9]+(-INTERMEDIATE)?$ ]] && echo true
true
$ version='main-3581.0.0-nightly-20230421-2100'
$ [[ "${version}" =~ ^main-[0-9.]+-nightly-[-0-9]+(-INTERMEDIATE)?$ ]] && echo true
true
```
I can cherry-pick it to other branches, but not sure if there's a point as it only affects the builds from the main …
> sdk_bootstrap: Push a branch also for two-phase SDK nightly builds

- .github/workflows/cacerts-release.yaml
- .github/workflows/ci.yaml
- .github/workflows/containerd-release-main.yaml
- .github/workflows/docker-release-main.yaml
- .github/workflows/firmware-release-main.yaml
- .github/workflows/go-release-main.yaml
- .github/workflows/kernel-release.yaml
- .github/workflows/mantle-releases-main.yml
- .github/workflows/runc-release-main.yaml
- .github/workflows/rust-release-main.yaml
- .github/workflows/update-metadata-glsa.yaml
- .github/workflows/vmware-release-main.yaml
Build and CI tests should run automatically whenever a pull request is opened, reopened or updated.
On the other hand, it is not necessary to run build and CI tests on the events `ready_for_review` and `review_requested`.
That could already work out of the box for `reopened` and `synchronized` events.
To do that especially for the `opened` event, however, it is necessary to use a dedicated personal access token `BOT_PR_TOKEN` for bot PRs instead of the default `GITHUB_TOKEN`. It is needed for triggering another workflow from pull requests created by Github Actions. The default `GITHUB_TOKEN` is by design not able to trigger another workflow.
See also https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow.
tested via my fork repo
> .github: get build and CI triggered by opened, synchronize

- .github/workflows/cacerts-apply-patch.sh
- .github/workflows/cacerts-release.yaml
- .github/workflows/ci.yaml
- .github/workflows/common.sh
- .github/workflows/containerd-apply-patch.sh
- .github/workflows/containerd-release-main.yaml
- .github/workflows/docker-apply-patch.sh
- .github/workflows/docker-release-main.yaml
- .github/workflows/firmware-apply-patch.sh
- .github/workflows/firmware-release-main.yaml
- .github/workflows/go-apply-patch.sh
- .github/workflows/go-release-main.yaml
- .github/workflows/kernel-apply-patch.sh
- .github/workflows/kernel-release.yaml
- .github/workflows/runc-apply-patch.sh
- .github/workflows/runc-release-main.yaml
- .github/workflows/rust-apply-patch.sh
- .github/workflows/rust-release-main.yaml
- .github/workflows/vmware-apply-patch.sh
- .github/workflows/vmware-release-main.yaml
To avoid noise of touching existing PRs, check first if the remote branch already exists. If that exists, skip creating or updating the PR.
In case of a draft PR created first, no CI gets triggered at the time. So we should trigger CI afterwards when it is being set to a ready_for_review state.
Changelog directory is now located under flatcar scripts, not under coreos-overlay. Fix the location to add correct changelog to the git commit.
Tested via my fork repo
> .github: check remote branch, add correct changelog

- .github/workflows/common.sh
`git show-ref` in `check_remote_branch` is not working at all, because the GitHub Actions checkout fetches a git repo with only depth 1 by default. That means only main branch is available, not any other remote branches. As a result, `git show-ref` always fails.
Fix that by checking for remote branches by `git ls-remote`.
Fixes bugs resulted from https://github.com/flatcar/scripts/pull/784.
tested via my fork
> .github: check for remote branches with git ls-remote

- changelog/security/2023-05-04-openssl-3.0.8-r4.md
- sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/openssl-3.0.8-CVE-2023-0464.patch
- sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/openssl-3.0.8-CVE-2023-0465.patch
- sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/openssl-3.0.8-CVE-2023-0466.patch
- sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/openssl-3.0.8-CVE-2023-1255.patch
- sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/openssl-3.0.8-mips-cflags.patch
- sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/files/openssl.conf
- sdk_container/src/third_party/coreos-overlay/dev-libs/openssl/openssl-3.0.8-r4.ebuild
Update `dev-libs/openssl` to 3.0.8-r4, mainly to address the following security issues:
* [CVE-2023-0464](https://nvd.nist.gov/vuln/detail/CVE-2023-0464)
* [CVE-2023-0465](https://nvd.nist.gov/vuln/detail/CVE-2023-0465)
* [CVE-2023-0466](https://nvd.nist.gov/vuln/detail/CVE-2023-0466)
* [CVE-2023-1255](https://nvd.nist.gov/vuln/detail/CVE-2023-1255)
Based on Gentoo commit [bebe8fa4ec3e](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=bebe8fa4ec3ef6b87551157f4e13755956936aa3).
Flatcar changes are based on [9cd2474a4950](https://github.com/flatcar/scripts/commit/9cd2474a49507794ef5fdcf053fbe82716bba0f0).
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/788/cldsv/
> dev-libs/openssl: update to 3.0.8-r4

- changelog/changes/2023-05-12-coreos-cloudinit.md
- sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-cloudinit/coreos-cloudinit-9999.ebuild
Upgrade ```coreos-cloudinit``` to [89319292b9bca85a7a1f5f8a47c459dd45a8cc7a](https://github.com/flatcar/coreos-cloudinit/commit/89319292b9bca85a7a1f5f8a47c459dd45a8cc7a)
This change adds the short form of the hostname retrieved from metadata.
Deployed a VM on OpenStack and inspected ```/etc/hostname```. The hostname was set to the short form instead of the FQDN.
> coreos-base/coreos-cloudinit: Update to latest commit

- .github/workflows/ci.yaml
- .github/workflows/pr-comment-build-dispatcher.yaml
- .github/workflows/update-sdk.yaml
- ci-automation/garbage_collect.sh
- ci-automation/garbage_collect_github_ci_sdk.sh
- update_sdk_container_image
This change adds a github actions workflow to trigger SDK and OS image builds from PR comments. It verifies whether the commenter is a member of the [Flatcar Maintainers](https://github.com/orgs/flatcar/teams/flatcar-maintainers) team before commencing the build.
The PR comment commands are:
- `/build-sdk` - builds SDK and OS image, runs tests
- `/build-image` - builds OS image and runs tests
The previous semantics of triggering builds from PR changes ("ready to review", "synchronised") is removed. **This implies builds now need to be explicitly started using one of the above commands.**
Further, a new workflow is added to create a new SDK container based on an existing SDK container. The new container image is published to bincache. This can be used for CI testing intrusive changes that …
> Trigger build workflow via PR comment instead of PR state; add a workflow to build an updated SDK container, 

- .github/workflows/pr-comment-build-dispatcher.yaml
- .github/workflows/run-kola-tests.yaml
This change includes 2 unrelated small fixes to the "PR comment command" build+test feature:
1. The concurrency group now contains the PR number, ensuring that builds for multiple PRs can run in parallel. This addresses an issue in which starting a build on a PR would cancel a running build of another PR.
2. Post test results to the PR where the build command was issued on. The add-pr-comment step's condition was not updated when switching to PR comment commands for starting builds, so the step would only run if the action was triggered by a PR change event. Since we now trigger on issue_comment, the step never ran.
Additionally, the PR from which a run was triggered will now receive a comment with a link to the workflow run.
Fixes [#1046](https://github.com/flatcar/Flatcar/issues/1046).
> workflows/pr-comment,run-kola: fix concurrency + results comment

- .github/workflows/ci.yaml
- .github/workflows/pr-comment-build-dispatcher.yaml
- .github/workflows/pr-workflows.yaml
- .github/workflows/run-kola-tests.yaml
- .github/workflows/update-sdk.yaml
This replaces #860 
This change adds a workflow that is triggered on every PR. This workflow is started in the ```development``` environment and required manual approval from the flatcar-maintainers team before it runs.
Once approved, the workflow runs as usual.
When opening a new PR, add the following string anywhere in the **PR summary**:
/update-sdk
This will be parsed by the workflow and signal the ```update_sdk``` job to run. 
Note, the workflows will probably be active for this PR and will try to update the SDK and then build the image. If we don't want to do that, we can simply not approve the run.
The command based PR runs have also been updated and *should* work the same way. If we want to trigger just the image build, it should be enough to specify:
/build-image
anywhere in the …
> Add on pr workflow

- build_library/vm_image_util.sh
The initial MVP of the OEM sysext usage we release won't have updates for the sysext image and, therefore, it is not bound to the OS version. The special name suffix instead of the version hints bootengine at using it if no matching version is found. The name will also be used at hint for update-engine to clean it up when versioned sysext images arrive.
Tested with [Jenkins](http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1968/cldsv/) and checked the filename on the qemu OEM image.
> build_library: For now don't use a version for the OEM sysext image

- changelog/changes/2023-06-15-containerd-service
- sdk_container/src/third_party/coreos-overlay/app-containers/containerd/files/containerd.service
Race condition arises when the containerd service unit assumes services are ready as soon as they start running, rather than when they can actually accept socket requests. To rectify this, changing the unit to Type=notify is required, utilizing the existing containerd support for sd_notify call after socket setup.
References:
- https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type=
- https://github.com/flatcar/Flatcar/issues/203
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1993/cldsv/
> Migrate to Type=notify

- ci-automation/vendor-testing/azure.sh
The instance type used for the NVIDIA test is amd64-only.
> ci-automation: Add NVIDIA instance type only for amd64

- sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-cloudinit/coreos-cloudinit-9999.ebuild
This pulls in
https://github.com/flatcar/coreos-cloudinit/pull/22 to prevent using the configdrive on DigitalOcean.
Backport to `flatcar-3637`
Tested on [Jenkins](http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/2021/cldsv/)
> coreos-base/coreos-cloudinit: Don't use configdrive on DigitalOcean

- build_library/disk_util
- changelog/changes/2023-06-22-ext4-inode-size.md
Inode sizes smaller than 256:
- don't support extended metadata (nanosecond timestamp resolution)
- cannot handle dates beyond 2038
- are deprecated
Change the default from 128 to 256. There is no way to apply this change on a mounted filesystem so this change will only apply to new deployments.
Fixes: flatcar/flatcar#1082
```
./build_image
<run flatcar>
tune2fs -l /dev/vda9
```
No testing done.
> Switch default ext4 inode size to 256 bytes

- build_library/oem_sysext_util.sh
- ci-automation/ci-config.env
- ci-automation/image.sh
- ci-automation/packages.sh
This fixes the issue of sysext creating running out of disk space after we changed the ext4 inode size to 256 bytes.
```
./build_image
./image_to_vm.sh --format=azure
```
Performed the step in `how to use` - successfully.
> oem_sysext_util: Mount overlay on top of /usr before installing sysext

- changelog/bugfixes/2023-06-28-sssd-var-log.md
- sdk_container/src/third_party/coreos-overlay/sys-auth/sssd/files/tmpfiles.d/sssd.conf
The folders are not created through "keepdir" which results in tmpfiles rules but an explict tmpfiles file. This is error prone and we should try to move to "keepdir" instead but for the backport, just add the missing line.
Backport to Beta
Checked that the folder is there. With the default config, `sssd.service` can't start but the error message is different.
> sys-auth/sssd: Add missing /var/log/sssd tmpfiles entry

- sdk_container/src/third_party/portage-stable/acct-group/docker/docker-0-r1.ebuild
- sdk_container/src/third_party/portage-stable/acct-group/docker/metadata.xml
Add acct-group/docker to portage-stable. Looks like an omission from our side when syncing the docker ebuilds with Gentoo.
Dependency to be able to successfully ``emerge app-containers/docker``
With this patch (adding acct-group/docker to portage-stable) I am able to emerge app-containers/docker
> [acct-group/docker] Add acct-group/docker to portage-stable

- .github/workflows/ci.yaml
- .github/workflows/run-kola-tests.yaml
- .github/workflows/setup-flatcar-sdk.sh
- .github/workflows/update-sdk.yaml
- ci-automation/ci-config.env
- ci-automation/ci_automation_common.sh
This PR switches to using zstd for compressing/decompressing container images. Zstd tarballs are a bit smaller and compression/decompression is significantly faster gzip (even with pigz). Zstd can handle decompressing gzip payloads, so introduce a fallback to fetch gzip payloads so that we can still consume nightly sdks produced before this commit.
`./run_sdk_container -t` or in CI.
running: http://192.168.42.7:8080/job/container/job/packages_all_arches/2066/cldsv/
/update-sdk
> Use zstd for sdk container images

- build_library/prod_image_util.sh
- build_sysext
Included a script to enable generating systemd-sysexts. Successfully tested sysext generation (manually; script refinement in progress) with a fresh Flatcar image (e.g., Python and Neofetch system extension). Part of my internship work.
Link to the related issue: [Flatcar Issue #1052](https://github.com/flatcar/Flatcar/issues/1052).
The current OS images we provide are not OK as base for flatcar specific sysext images: it lacks the package metadata and portage configuration, in order to keep end user OS image clean. This script retains this information and allows you to produce systemd-sysexts to extend the system. This script can be used to build a Flatcar sysext image. Recommended to run from image build folder.
```
sudo build_sysext --board=amd64-usr command-extras package_1 package_2 …
```
> Build_sysext script to enable sysext builds in the OS image build process

- sdk_container/src/third_party/coreos-overlay/sys-kernel/bootengine/bootengine-9999.ebuild
This pulls in
https://github.com/flatcar/bootengine/pull/66
to add a workaround for missing DNS resolve retry.
see linked PR
> sys-kernel/bootengine: Add DNS retry waiter for OEM sysext fallback

- build_library/vm_image_util.sh
- build_sysext
This change improves `build_sysext` by sourcing a missing lib dependency, adding a number of comfort / quality-of-life options, and updating the output of `--help` accordingly.
The OEM sysext finction in `build_library/vm_image_util.sh` is also updated to use new command line format.
1. Include missing dependency `toolchain_util.sh` to fix an error in `board_options.sh` when `--board` was not specified (`get_board_arch` undefined).
2. Use positional parameters for mandatory arguments:  `sysext_name` and `binary_package` are positional arguments now; the latter can be omitted if `--metapkgs` was specified.
3. `--squashfs_base` is now guessed better and will use the most recent build by default.
4. `--image_builddir` is now guessed and defaults to a `sysext` sub-directory in the directory …
> build_sysext: bugfixes, QoL changes, help updated

- sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/profile.bashrc
`sys.version` returns `3.10.12 (main, Jul  6 2023, 22:54:08) [GCC 12.2.1 20230428]`.
The previous expression (sys.version[:3])) truncates 3.10 to 3.1 leading to build failures in some ebuilds that depend on python (like zfs).
Don't know which ebuilds (other than sys-fs/zfs) use this but the problem is obvious.
Built zfs sysext.
> profiles/coreos: Account for python versions with minor > 10

- .gitignore
- ci-automation/vms.sh
The official release variable is used to decide whether a build ID gets
appended to the FLATCAR_VERSION (or VERSION in os-release) or not. It
was set for the image job but not for the vms job, causing the
build_sysext script to get the build ID appended to the FLATCAR_VERSION
which causes a mismatch with the one from the image job.
Set the official release variable in the vms job as well.
Needed for the branched Alpha
In the workspace of the vms job I ran this:
```
sdk@flatcar-sdk-all-3665_0_0_os-alpha-3665_0_0 ~/trunk/src/scripts $ COREOS_OFFICIAL=1 sh -c 'source ./common.sh ; echo "$FLATCAR_VERSION"'
3665.0.0
sdk@flatcar-sdk-all-3665_0_0_os-alpha-3665_0_0 ~/trunk/src/scripts $ COREOS_OFFICIAL=0 sh -c 'source ./common.sh ; echo "$FLATCAR_VERSION"'
3665.0.0+2023-07-17-1517
```
> ci-automation/vms: Export official release variable

- build_library/toolchain_util.sh
- update_chroot
Hi. When running the build_packages script, one can encounter an error such as 'Error fetching binhost package info from.' This pertains to SDK packages (not board packages). Since we have transitioned to the SDK container, the SDK packages are no longer published independently from the container image.
@jepio encouraged me to submit a pull request (PR) for the same
> Check the url in get_sdk_binhost before echoing

- changelog/changes/2023-08-08-change-nvidia-oneshot.md
- sdk_container/src/third_party/coreos-overlay/x11-drivers/nvidia-drivers/files/units/nvidia.service
When changed to oneshot, the subsequent services wiill actually wait for the nvidia.service to finish, i.e. wait for drivers to be installed. The subsequent services can be configured to wait for nvidia.service. This needs to be coupled with 
RemainAfterExit=yes to ensure it doesn't get kicked-off automatically again.
Solves : https://github.com/flatcar/Flatcar/issues/1136
> Changes to nvidia.service to allow ordering on the subsequent services

- .github/workflows/ci.yaml
- ci-automation/image_changes.sh
> .github: Add image change reports to CI workflow

- ci-automation/ci_automation_common.sh
Since https://github.com/flatcar/scripts/pull/950 was merged, tarball files `flatcar-{packages,sdk}-*.tar.zst` have been created with mode 0600 instead of 0644.
As a result, the files with mode 0600 were uploaded to bincache, but afterwards `copy-to-origin.sh` that in turn runs rsync from bincache to the origin server could not read the tarballs.
To fix that, it is necessary to chmod from 0600 to 0644 to make it readable by rsync during the release process.
All of that happens because zstd sets the mode of the output file to 0600 in case of temporary files to avoid race condition.
See also https://github.com/facebook/zstd/pull/1644, https://github.com/facebook/zstd/pull/3432.
/update-sdk
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/985/cldsv/
- Changelog entries added in …
> ci-automation: explicitly make packages tarballs readable

- changelog/updates/2023-08-11-openldap-2.6.3.md
- sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.mask
Now that Alpha 3689.0.0 was released with openldap 2.5.14, we do not need to mask openldap >= 2.6.
Drop the mask, to update openldap to 2.6.3-r7.
/update-sdk
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/994/cldsv/
> net-nds/openldap: update to 2.6.3

- changelog/security/2023-09-22-glibc-2.37-r5.md
- sdk_container/src/third_party/coreos-overlay/sys-libs/glibc/glibc-2.37-r5.ebuild
Sync to upstream 2.37-rc5 and apply Flatcar specific patches.
Closes https://github.com/flatcar/Flatcar/issues/1179.
> sys-libs/glibc: update to patchlevel 2.37-rc5

- .github/workflows/ci.yaml
- ci-automation/image_changes.sh
2 issues needed fixing:
- truncated leading output stemming from redirecting standard output to /dev/stdout, which is no-worky on Jenkins, apparently.
- a bug in show-changes resulting in no changelog differences being printed
Fix tested in http://jenkins.infra.kinvolk.io:8080/job/container/job/image_changes/2999/console
> Fix garbled output in image changes reports

- ci-automation/ci_automation_common.sh
- ci-automation/packages-tag.sh
- ci-automation/sdk_bootstrap.sh
We push a commit with the nightly SDK tag to the main branch if the SDK was built from the main branch. Which is what happens when we build the nightly intermediate SDK. The final nightly SDK is not built from the main branch, but rather from the nightly intermediate SDK tag. Both of them point to the exactly same commit, but the difference is in what `git rev-parse --abbrev-ref HEAD` returns for each of those. When the main branch is checked out, the command will return "main". When the nightly intermediate SDK tag is checked out, the command will return "HEAD". So when nightly final SDK is being built, the command returns a string different than "main" and thus decides not to push the commit with the final nightly SDK tag to the main branch. Rework it to assume that if `git rev-parse …
> ci-automation: Follow-up fix for 2-phase nightly SDK build tags

- sdk_container/src/third_party/prefix-overlay/skel/etc/portage/package.mask/cross
Back when SDK prefix builds were introduced, the SDK shipped with gcc-12. As prefix uses experimental packages during bootstrapping of the staging area, this lead to (the SDK's) gcc-12 being used to build an experimental (prefix staging area)  gcc-13 - which led to build breakage. Therefore, gcc-13 was explicitly masked in the prefix overlay.
Now that the SDK ships gcc-13 this mask can be removed. More specifically it _must_ be removed in order for prefix bootstrapping to work, because trying to build gcc-12 with gcc-13 breaks the bootstrap build.
Relevant discussion in the original prefix PR: https://github.com/flatcar/scripts/pull/1158#discussion_r1341097924
This is a minimal, non-intrusive change that only affects the prefix overlay. Neither SDK nor OS image are affected.
> prefix: remove gcc-13 mask as the SDK now uses gcc-13

- changelog/bugfixes/2023-09-29-ignition-partition.md
- sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/files/0022-sgdisk-Run-partprobe-after-partition-changes.patch
- sdk_container/src/third_party/coreos-overlay/sys-apps/ignition/ignition-9999.ebuild
- sdk_container/src/third_party/coreos-overlay/sys-kernel/bootengine/bootengine-9999.ebuild
This adds https://github.com/coreos/ignition/pull/1717 as downstream patch to fix https://github.com/flatcar/Flatcar/issues/1194
This is a backport. I wanted a new PR to make sure it builds.
[Jenkins](http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/2668/cldsv/) and manually with a Butane config as in the original PR
> Run partprobe after Ignition partition changes

- changelog/bugfixes/2023-10-09-docker-go-1.19.md
- sdk_container/src/third_party/coreos-overlay/app-emulation/docker-cli/docker-cli-20.10.24.ebuild
- sdk_container/src/third_party/coreos-overlay/app-emulation/docker-proxy/docker-proxy-9999.ebuild
- sdk_container/src/third_party/coreos-overlay/app-emulation/docker-runc/docker-runc-1.1.7.ebuild
- sdk_container/src/third_party/coreos-overlay/app-emulation/docker/docker-20.10.24.ebuild
Docker 20.10.24 expects to be built with go 1.19 and if it isn't certain unix level functionality is broken. We already bumped to building with go 1.19 for alpha-3619.0.0, so this change it present in beta/alpha/main.
Fixes a regression in stable https://github.com/flatcar/Flatcar/issues/1203.
> Build docker with go 1.19

- changelog/changes/2023-10-09-kubernetes-usr-libexec.md
- sdk_container/src/third_party/coreos-overlay/coreos-base/misc-files/misc-files-0-r2.ebuild
In the past user had to customize Kubernetes or use a bind mount to make writing the default /usr/libexec/kubernetes/ path work. With systemd-sysext on by default the bind mount doesn't work anymore because it can get lost. A newer workaround is to use a systemd-sysext image that creates a symlink in /usr/libexec/... to redirect to somewhere under /var/.
Instead of relying on workarounds, make Kubernetes work by default on Flatcar by having the symlink be part of the generic image. The target folder will be created through a tmpfiles rule.
(The same paths are used as in https://github.com/flatcar/sysext-bakery/pull/28)
Backport to Stable and maybe even LTS?
[Done](http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/2690/cldsv/):
Checked that the symlink exists under …
> coreos-base/misc-files: Make Kubernetes work by default through symlink

- ci-automation/garbage_collect_cloud.sh
- ci-automation/vendor-testing/azure.sh
Switch to using a managed identity instead of file based credentials for running kola/ore (not plume). This covers our test subscription, but not our publishing subscription.
(removed the issue template because this is only a change to ci)
Depends on this PR being merged first (and the reference in this repo being updated):
- https://github.com/flatcar/mantle/pull/456
> ci-automation: Switch to managed identity on azure

- ci-automation/sdk_bootstrap.sh
We have switched to zst for SDK container tarballs.
> ci-automation: Update the SDK container extension in check

- sdk_lib/Dockerfile.sdk-import
Just do stuff as root for now.
The workaround can be removed when our builders pick up a stable release with a fix.
CI: (weekly package updates using this commit): http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/1103/cldsv/
> sdk_lib: Workaround docker issue with missing ownership preservation

- build_library/grub_install.sh
Apparently successful `[[ -b "${LOOP_DEV}p1" ]]` check is not enough - the mount can still fail. So instead of doing those checks, try mounting and reprobing in the loop with some small exponential backoffs.
Tested in http://jenkins.infra.kinvolk.io:8080/job/container/job/image/3905/
```
09:08:56  INFO    grub_install.sh: Installing GRUB arm64-efi in flatcar_production_image.bin
09:08:56  mount: /tmp/tmp.zIJJtMzPZe: special device /dev/loop0p1 does not exist.
09:08:56         dmesg(1) may have more information after failed mount system call.
09:08:56  WARNING grub_install.sh: loopback device node /dev/loop0p1 still missing, reprobing...
09:08:56  INFO    grub_install.sh: Compressing modules in flatcar/grub/arm64-efi
09:08:58  INFO    grub_install.sh: Generating …
```
> build_library/grub_install: Try mounting ESP directory in a loop

- changelog/security/2023-10-13-curl-backport.md
- sdk_container/src/third_party/coreos-overlay/coreos/user-patches/net-misc/curl/CVE-2023-38545_7.87.0.patch
- sdk_container/src/third_party/coreos-overlay/coreos/user-patches/net-misc/curl/CVE-2023-38546.patch
> Backport curl CVE fixes to stable

- changelog/security/2023-10-16-2023-10-16-curl-backports.md.md
- sdk_container/src/third_party/coreos-overlay/coreos/user-patches/net-misc/curl/0001-curl-7.87.0-CVE-2023-38545.patch
- sdk_container/src/third_party/coreos-overlay/coreos/user-patches/net-misc/curl/0002-curl-7.87.0-CVE-2023-38546.patch
backport curl CVE to flatcar-3510 (LTS-2023)
CVEs for which patches are added
- CVE-2023-38545
- CVE-2023-38546
> backport curl CVE to flatcar-3510 (LTS-2023)

- build_packages
This change removes "curl" from the USE flags to be removed to build systemd in the cyclic deps resolver step of build_packages. Excluding curl from systemd's USE flags leads to build breakage:
```
09:06:25  !!! The ebuild selected to satisfy "sys-apps/systemd" for /build/amd64-usr/ has unmet requirements. 09:06:25  - sys-apps/systemd-252.11-r1::coreos USE="audit dns-over-tls elfutils gcrypt gnuefi http idn importd iptables kmod lz4 lzma openssl pam pcre policykit resolvconf seccomp selinux (sysv-utils) (vanilla) zstd -acl -apparmor -cgroup-hybrid -cryptsetup -curl -fido2 -gnutls -homed -pkcs11 -pwquality -qrcode (-split-usr) -test -tpm -xkb" 09:06:25
09:06:25    The following REQUIRED_USE flag constraints are unsatisfied:
09:06:25      importd? ( curl )
09:06:25
09:06:25    The above …
```
> build_packages: fix systemd cyclic deps resolver

- build_library/disk_layout.json
The compression feature of btrfs allows us to store more in the size-limited /usr and OEM partitions. The size should of course still be monitored to not bloat the image but more headroom helps to try things out quickly without hitting the hard limit which fails the build.
Use btrfs with zstd compression for the /usr partition. While for ext2 a hack exists to force read-only mounts by manipulating some bytes of the filesystem, on btrfs we can use the subvolume read-only flag instead which also works for the default top level subvolume. However, it also makes also sense to mount the filesystem with the "norecovery" mount option to prevent any write attempts even when the "ro" option is set (not needed when using dm-verity in read-only mode but when directly mounting without dm-verity). A …
> disk_layout: use btrfs for the /usr partition

- run_sdk_container
- sdk_lib/sdk_container_common.sh
Cleanups:
- Make cosmetic fixes in help output.
- There is usually no need for putting variables inside quotes in
assignments.
- Use [[ ]] to avoid putting everything into strings.
- Use arrays instead of relying on strings to be split on whitespace
as it was the case for invoking docker and getting GPG volume flags
for docker.
- Make sure that some cleanup and trap strings quote variables
properly.
- Add a "call_docker" function to avoid dealing with "docker" and a
new "docker_a" variables when willing to invoke docker. The "docker"
variable rather shouldn't be used, but it is still there in case
some other scripts were using it.
Adds `-m <src>:<dest>` flag to mount host directories inside SDK container.
> run_sdk_container: Clean up a bit and add mounting of custom volumes

- build_library/test_image_content.sh
We updated grub to >=2.06 and thus 202209-12 can be removed from the GLSA allowlist.
A GLSA check is run during `build_packages` so if the grub GLSA would still apply then the CI build would fail.
> test_image_content.sh: remove 202209-12 exception (grub)

- run_local_tests.sh
This one-line change un-quotes the list of user supplied tests so it actually arrives as a list to the test script instead of a single string. We simply unquote instead of using `${test@Q}` because the latter breaks a neat little hack in which users can pass parameters like `--log-level=DEBUG`  to kola.
> run_local_tests.sh: unquote tests var so lists and kola options can pass

- build_library/sysext_prod_builder
We see occasional failures due to a read-only filesystem on GitHub Action runners:
mkdir: cannot create directory ‘/home/sdk/trunk/src/scripts/artifacts/amd64-usr/developer-3790.0.0+nightly-20231116-2100-5-g49eb1a4c07-a1/rootfs/usr/share/flatcar/sysext’: Read-only file system
Add commands for a debug output.
> build_library/sysext_prod_builder: Add debug output

- changelog/changes/2023-10-19-torcx-removal.md
- changelog/changes/2023-10-25-docker-gentoo-upstream.md
During the release of Alpha-3794.0.0 we further improved changelog messages for the docker 24 upgrade and the torcx removal. This PR updates the respective changelog entries in the repository.
See release announcement here:
https://hackmd.io/nG2pd4iKQ9GTazucHH5U9Q?view#New-Alpha-Release-379400
**Cherry-pick** to flatcar-3794 after approval.
> changelog: improved messaging for torcx removal and docker 24 upgrade

- ci-automation/image_changes.sh
This script will be eventually (in couple years) run to get image changes for the old LTS channel, so make sure that it will fetch the last release of the old LTS channel, instead of a new LTS one.
> ci-automation/image-changes: Get proper last release version for LTS channels

- changelog/changes/2023-09-20-slsa.md
- sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/profile.bashrc.slsa-provenance
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/2543/cldsv
- Update to slsa 1.0. This is only partially done, as we still need to provide a proper build type. Maybe we could reuse the Github Actions Workflow (https://slsa-framework.github.io/github-actions-buildtypes/workflow/v1).
- Stop using portageq - its use in ebuilds is banned, so eventually it would stop working. Replace it with our hack.
- Stop trying to get a commit hash of coreos-overlay or portage-stable as if they were submodules. This setup is long gone, so a commit hash of toplevel scripts repo is enough.
- Use zstd for compressing generated JSON files.
--
> overlay profiles: Fix a couple of issues with SLSA provenance stuff

- build_dev_binpkgs
- build_packages
- ci-automation/push_pkgs.sh
This change introduces `build_dev_binpkgs`, a script to build binary packages for all dependencies of the devcontainer. This works around an issue with `build_packages`, which doesn't - leading to build issues with the devcontainer later on. This particularly happens for more complex builds with the devcontainer.
Additionally, a call to `build_dev_binpkgs` has been added to the package publishing step in ci-automation before binary packages are published.
Lastly, this change adds a command line option to `build_packages` to stop execution of the script after breaking circular dependencies (i.e. before board packages are built). This option was very helpful while working on `build_dev_binpkgs` and is likely to be similarly useful for other package build related development.
Fixes …
> T lo/build dev packages

- build_dev_binpkgs
- build_packages
- ci-automation/push_pkgs.sh
This is PR https://github.com/flatcar/scripts/pull/1491 back-ported to flatcar-3033. Some manual conflict resolution was required for `build_packages`.
> flatcar-3033: backport build dev packages

- build_dev_binpkgs
- build_packages
- ci-automation/push_pkgs.sh
This is PR https://github.com/flatcar/scripts/pull/1491 back-ported to flatcar-3510. Some manual conflict resolution was required for `build_packages`.
> flatcar-3510: backport build dev packages

- sdk_lib/sdk_init_selfcontained.sh
This change fixes access rights / file ownership changes in the self-contained SDK init script.
> sdk_lib/sdk_init_selfcontained.sh: fix access rights

- sdk_container/src/third_party/coreos-overlay/coreos-base/common-oem-files/common-oem-files-0-r5.ebuild
We are not building gce OEM images for arm64 at all, so gce being in common OEM ID list resulted in arm64 image reports printing errors for it.
Example run with errors: http://jenkins.infra.kinvolk.io:8080/job/container/job/image_changes/4008/consoleFull (search for "gce").
> overlay coreos-base/common-oem-files: Move gce to amd64-only OEMID list

- changelog/security/2024-01-05-openssh-update.md
- changelog/security/2024-01-05-weekly-updates.md
- sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
The PR adds missing CVE entries for openssh, drops an irrelevant one and drop a duplicated accept keywords entry. The last two items ought to be a part of the weekly updates PR - I made the changes locally, but forgot to push before merging the PR. Meh.
Closes https://github.com/flatcar/Flatcar/issues/1310
> Changelog and accept keywords fixes

- sdk_container/src/third_party/coreos-overlay/coreos-base/ue-rs/ue-rs-9999.ebuild
This pulls in
https://github.com/flatcar/ue-rs/pull/50
to remove an option that we don't need anymore.
Only manual. The option is also not used in the postinst hook.
> coreos-base/ue-rs: Remove -v/--print-progress option

- changelog/bugfixes/2024-01-24-update-proxy-setup.md
- sdk_container/src/third_party/coreos-overlay/coreos-base/update_engine/update_engine-9999.ebuild
This pulls in https://github.com/flatcar/update_engine/pull/37 to forward the proxy env vars for curl and ue-rs download_sysext (Flatcar Stable currently uses curl, Alpha uses ue-rs).
Backport to Stable and LTS.
see PR
> coreos-base/update_engine: Forward proxy env for postinstall script

- ci-automation/garbage_collect.sh
- ci-automation/garbage_collect_github_ci_sdk.sh
This change improves the build cache garbage collector to remove orphaned artifact directories - i.e. directories to which no version tag exists in the scripts repo.
SDK containers built by Github actions (using update_sdk_container) are igored by this change because these are handled in a separate garbage collection script.
Also, a new command line parameter has been added to remove artifacts older than the specified number of days (defaulting to 14):
- If neither number of builds nor max age is specified, the script defaults to 50 builds to keep, and a max age of 14 days. The max age overrides the number of builds to keep, so more than 50 builds may be kept.
- If only the number of builds to keep is specified, the max age is set to "0" (i.e. today).
- If both are specified, max age …
> ci-automation/garbage_collect.sh: Add min age, remove orphan directories

- changelog/changes/2024-01-25-flatcar-update-oem.md
- sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in https://github.com/flatcar/init/pull/114 to support a flag to skip providing OEM payloads, with the goal of easing downgrades to non-sysext-OEM releases or, when backported to LTS with the default behavior switched, to opt-in to OEM payloads for airgapped updates that can't use the fallback download.
Backport to all channels (with backport branches for the init repo to only pick the flatcar-update changes, and its dependencies, but not changes for the rest of the init repo)
see PR
> coreos-base/coreos-init: Add flatcar-update flag to skip OEM payloads

- build_dev_binpkgs
- sdk_container/src/third_party/portage-stable/dev-util/glib-utils/glib-utils-2.74.4.ebuild
The format of emerge output differs a bit, as it is missing the repo name (which came after `::`).
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/3426/cldsv/
> Fix publishing of dev binpkgs

- changelog/bugfixes/2024-02-08-airgapped-updates.md
- sdk_container/src/third_party/coreos-overlay/coreos-base/update_engine/update_engine-9999.ebuild
This pulls in https://github.com/flatcar/update_engine/pull/38 with two workarounds to read out proxy env vars from the service unit and to read out the XML response from the journal logs, because the XML passing and the passing of proxy env vars is not present in old clients.
Backport to Stable
See PR
> coreos-base/update_engine: Support updating old airgapped clients

- sdk_container/src/third_party/coreos-overlay/sys-kernel/bootengine/bootengine-9999.ebuild
This pulls in https://github.com/flatcar/bootengine/pull/86 to fix the previous rework that only created /run/ignition.env on the first boot while we rely on it to run cloud-init on every boot when no Ignition config was provided.
Backport to flatcar-3874
See PR
Changelog depends on whether we can rebuild alpha with this today
> sys-kernel/bootengine: Ensure /run/ignition.env exists on every boot

- core_sign_update
The sdk user in the container might rejected by the pcscd on the host. Work around that by running the openssl command as root.
Used for current release
> core_sign_update: Work with a mapped pcscd socket

- changelog/bugfixes/2024-02-13-fix-kmod-static-nodes-creation.md
- sdk_container/src/third_party/coreos-overlay/sys-kernel/bootengine/bootengine-9999.ebuild
Update the bootengine commit id to use the fix from: https://github.com/flatcar/bootengine/pull/85
Fixes: https://github.com/flatcar/Flatcar/issues/1336
> bootengine: fix kmod-static-nodes

- ci-automation/ci-config.env
- ci-automation/garbage_collect.sh
- ci-automation/garbage_collect_github_ci_sdk.sh
- ci-automation/garbage_collect_releases.sh
This PR extends the garbage collector for the build cache server to remove cached release artifacts. Release artifacts are copied to the official mirrors and do not need to remain on the build cache after a release was published.
By default, the 10 latest releases per channel (including LTS and previous LTS) are kept.
Also excluded from garbage collection are:
- Emerging new major releases (i.e. major number larger than the latest Alpha release)
- channel progressions (major number exists in the lists of releases to keep but minor is bigger than any release)
- patch releases (major and minor exist in list of releases to keep but patch level is newer than in any release)
- SDKs (tarballs and containers) of any release in the list of releases to keep; i.e. the SDK in <MAJOR>.0.0 for any …
> ci-automation: improve bincache garbage collection, cover cached release artifacts

- .github/workflows/cacerts-release.yaml
- .github/workflows/ci.yaml
- .github/workflows/containerd-release-main.yaml
- .github/workflows/firmware-release-main.yaml
- .github/workflows/go-release-main.yaml
- .github/workflows/kernel-release.yaml
- .github/workflows/mantle-releases-main.yml
- .github/workflows/run-kola-tests.yaml
- .github/workflows/rust-release-main.yaml
- .github/workflows/update-metadata-glsa.yaml
- .github/workflows/update-portage-stable-packages-from-list.yaml
- .github/workflows/update-sdk.yaml
- .github/workflows/vmware-release-main.yaml
Some actions bumped their version when switching to the newer version of nodejs. `mshick/add-pr-comment@v2` was an exception - it stayed at `v2`.
> .github: Some action version bumps to avoid deprecation warnings

- sdk_container/src/third_party/coreos-overlay/sys-kernel/dracut/dracut-053-r1.ebuild
- sdk_container/src/third_party/coreos-overlay/sys-kernel/dracut/files/059-systemd-executor.patch
Without the systemd-executor binary, the upgrade to systemd 255 is not possible,
as it leads to a failure during the initramfs stage - executable not found systemd-executor.
Upgrade of dracut will be left for the future: https://github.com/flatcar/scripts/pull/1665, as dracut has to be upgraded after systemd 255 has been already upgraded, because of these two commits that will break bootengine and the CI:
https://github.com/dracutdevs/dracut/commit/7528d84de84d9c1fb7d5f54712c692600e21b044
https://github.com/dracutdevs/dracut/commit/5912f4fbc036cc36b9507c16dddef1ded1556572
> sys-kernel/dracut: add systemd-executor binary

- build_sysext
This one-line change enables building OEM images from releases without rebuilding all board packages.
It adds an option to the `emerge` command in `build_sysext` that allows emerge to download binary packages. Since we publish binpkgs for each release, the change allows users to build OEM images based on the generic OS image and sysext squashfs of a release.
Without this change, OEM builds require a full OS packages build locally, even for releases.
Tested for the Azure OEM image. Cloned the SDK, checked out a release, downloaded generic image and sysext quashfs, ran `image_to_vm.sh`:
```bash
git clone https://github.com/flatcar/scripts.git
cd scripts
git checkout stable-3815.2.0
wget https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_image.bin.bz2
wget …
```
> build_sysext: enable build of OEM images for releases

- build_library/sysext_prod_builder
To prevent mksquashfs from spamming the console about btrfs.compression.
SDK only change.
> build_library: Ignore btrfs xattrs

- sdk_container/src/third_party/coreos-overlay/coreos/config/env/app-admin/setools
- sdk_container/src/third_party/coreos-overlay/coreos/config/env/app-emulation/xen
- sdk_container/src/third_party/coreos-overlay/coreos/config/env/app-emulation/xen-tools
- sdk_container/src/third_party/coreos-overlay/coreos/config/env/sys-apps/busybox
- sdk_container/src/third_party/coreos-overlay/coreos/config/env/sys-apps/efunctions
Just cleaning some unused files I spotted.
> overlay coreos/config: Drop overrides for packages we do not have

- sdk_container/src/third_party/coreos-overlay/sys-boot/shim/files/0001-Fix-parallel-build-of-gnu-efi.patch
- sdk_container/src/third_party/coreos-overlay/sys-boot/shim/shim-15.8-r1.ebuild
The bundled gnu-efi build is implemented in a buggy way that can break when built in parallel. We've hit this in the nightly sdk build. Add a patch for it.
The patch has been posted upstream at https://github.com/rhboot/shim/pull/643.
> sys-boot/shim: Fix parallel build

- .github/workflows/ci.yaml
- .github/workflows/pr-comment-build-dispatcher.yaml
- .github/workflows/pr-workflows.yaml
- changelog/bugfixes/2024-02-27-pxe-oem-initrd.md
- sdk_container/src/third_party/coreos-overlay/sys-kernel/bootengine/bootengine-9999.ebuild
This pulls in https://github.com/flatcar/bootengine/pull/88 to restore looking at the documented /usr/share/oem path in a custom PXE OEM initrd instead of /oem.
Backport to Stable
```
tree initrd/
initrd/
└── usr
└── share
└── oem
└── config.ign
(cd initrd; find . -print0 | cpio --null --create --verbose --format=newc > ../merged.cpio )
zcat flatcar_production_pxe_image.cpio.gz >> merged.cpio
gzip merged.cpio
./flatcar_production_pxe.sh -- -append 'flatcar.first_boot=1' -initrd ../merged.cpio.gz
```
> sys-kernel/bootengine: Restore support for custom PXE OEM contents

- build_sysext
- changelog/bugfixes/2024-03-05-ensure-sysext-contents-merge.md
The Flatcar extension images built with build_sysext created directories in the overlay in a way that masked contents from other layers. Instead of fixing the way we create directories, make use of postprocessing to avoid any similar problems show up again in the future.
Backport
Fixes https://github.com/flatcar/sysext-bakery/issues/50
Tested that the squashfs has no opaque markers:
```
sudo systemd-dissect --with oem-azure.raw find usr/ -xdev -type d -exec sh -c 'if [ "$(attr -R -q -g overlay.opaque {} 2>/dev/null)" = y ]; then echo {}; fi' \;
```
Tested that the Azure OEM extension works with the Kubernetes extension such that `/usr/lib/systemd/system/multi-user.target.d` has the containerd and kubernetes entries.
Jenkins: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_a …
> build_sysext: Remove any opaque directory markers

- build_library/build_image_util.sh
- build_library/prod_image_util.sh
- build_library/vm_image_util.sh
- ci-automation/test.sh
- sdk_container/src/third_party/coreos-overlay/coreos/config/env/sys-libs/ncurses
- install terminfo files for tmux
- slightly speed up `./build_image` by using lbzip2 instead of bzip2 when decompressing gcc.tbz2
- 
> Small fixes

- sdk_container/src/third_party/coreos-overlay/sys-kernel/bootengine/bootengine-9999.ebuild
Bumps bootengine to version in [this PR](https://github.com/flatcar/bootengine/pull/90) in flatcar/bootengine. Once merged, I'll change the `CROS_WORKON_PROJECT` and `CROS_WORKON_COMMIT` in this PR to point to the `flatcar-master`.
See [this PR](https://github.com/flatcar/bootengine/pull/90). 
See [this PR](https://github.com/flatcar/bootengine/pull/90).
> sys-kernel/bootengine: Bump commit for root unlocking service

- changelog/bugfixes/2024-03-25-disable-user-configdrive-on-openstack.md
- sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-cloudinit/coreos-cloudinit-9999.ebuild
This change disables user-configdrive.service on OpenStack, as coreos-cloudinit.service already runs on OpenStack when the system is not configured via ignition.
Deploy a virtual machine on OpenStack with config drive, verify that the unit is disabled.
Built a fresh flatcar image and deployed it on a local OpenStack. Checked that `user-configdrive.service` was not started.
/build-image
> Update coreos-cloudinit to latest main branch

- sdk_container/src/third_party/coreos-overlay/coreos/config/env/sys-apps/zram-generator
- sdk_container/src/third_party/coreos-overlay/coreos/config/env/sys-block/thin-provisioning-tools
- sdk_container/src/third_party/coreos-overlay/eclass/coreos-cargo.eclass
Ebuilds in portage-stable that use cargo.eclass don't cross-compile cleanly. Arm64 builds produce host binaries. Modify coreos-cargo.eclass slightly to allow it to be sourced from cros hooks, which allows us to override src_unpack cleanly. This is equivalent to injecting coreos-cargo.eclass into unmodified ebuilds.
Tested that with this change `zram-generator` and `thin-provisioning-tools` now produce arm64 binaries. This resolves the following `build_image` warning from arm64 builds:
```
[2024-03-21T03:45:55.114Z] sys-block/thin-provisioning-tools-1.0.10 is missing libraries:
[2024-03-21T03:45:55.114Z] 	x86_64: libc.so.6
[2024-03-21T03:45:55.114Z] 	x86_64: ld-linux-x86-64.so.2
[2024-03-21T03:45:55.114Z] 	x86_64: libgcc_s.so.1
[2024-03-21T03:45:55.114Z] 	x86_64: libm.so.6
```
[ describe …
> Allow injecting coreos-cargo.eclass into portage-stable ebuilds

- build_library/qemu_template.sh
- build_library/vm_image_util.sh
- changelog/changes/2024-04-03-qemu-script.md
- qemu_template.sh: Add support for attaching a software TPM
For testing TPM2-backed rootfs encryption it is handy to have a software
TPM option for the qemu script.
Add a flag for a software TPM with swtpm like kola also does. The user
has to specify a folder for the secret state and this won't be removed
because the same store should be able to be passed when booting the VM
again after shutdown.
- vm_image_util.sh: Bump default VM memory to 2 GB
While Flatcar itself runs fine with 1 GB, many workloads do not and
having to debug this is time consuming when one forgets to bump the VM
memory, e.g., in the Qemu script.
Default to 2 GB as known-good setting for things like Kubernetes or
setting up LUKS devices.
- qemu_template.sh: Allow parameters for VM image and memory
When testing …
> qemu_template.sh: Add support for attaching a software TPM

- build_library/release_util.sh
- build_library/vm_image_util.sh
- changelog/changes/2024-03-26-hyperv-vhdx-images.md
Add support for Gen 2 Hyper-V VMs.
See: https://github.com/flatcar/Flatcar/issues/1009
`./image_to_vm` tool has now a new supported format: `hyperv_vhdx`, that produces .vhdx dynamic disks.
```
./image_to_vm.sh --from ../build/images/amd64-usr/developer-latest/ --format hyperv_vhdx
```
> image_to_vm: add support for hyperv_vhdx format

- .github/workflows/ci.yaml
- build_library/release_util.sh
- build_library/vm_image_util.sh
- changelog/changes/2024-04-08-unify-qemu-images.md
- ci-automation/vms.sh
The qemu and qemu_uefi_secure images have the same contents as the qemu_uefi image which wastes space on the release server. A similar case is the PXE vmlinuz which is the same as the regular one, too.
Set up symlinks for same images, and also detect this when compressing to set up symlinks there as well. To reduce complexity, the qemu and qemu_uefi_secure images are not supported anymore and the Jenkins or GitHub CI will skip over them if specified. Users that build their own images need to adapt, though.
Backport
We could also set up symlinks in Origin but it's a bit tricky because the digest files would need to be regenerated for the compressed files.
The [images](https://bincache.flatcar-linux.net/images/amd64/9999.9.9+kai-unify-qemu/) on …
> Set up symlinks for same image artifacts to remove qemu/qemu_uefi_secure

- build_library/vm_image_util.sh
We didn't generate this before and don't need it.
When backporting we should also disable the uefi_secure arm64 image because this is not working on older branches.
> Skip non-UEFI qemu image symlink/script for arm64

- build_library/grub_install.sh
- changelog/changes/2024-04-09-grub-tpm.md
For binding a secret to the OS we need TPM PCRs that measure the kernel and boot configuration. Used for:
https://github.com/flatcar/flatcar-website/pull/317
Backport to Alpha
When booting with the UEFI script the first boot has PCR 8 and 9 set without any `grub.cfg` customization.
> build_library/grub.cfg: Enable TPM module by default

- .github/workflows/ci.yaml
- .github/workflows/run-kola-tests.yaml
The GitHub Action artifacts are compressed zip files which include bz2 files which are either the raw .bin images that have many zero bytes in the rootfs but the main data in /usr is using zstd compression, or they are the qcow2 .img images which are compressed themselves (and of course have the same /usr compression). The bz2 compression doesn't help in our case.
Remove the bz2 compression layer. If in the future non-zip artifacts are supported we can add it back for the .bin image only by using explicit calls only for that file instead of the
--image_compression_formats= flag for all images.
Backporting if possible, otherwise fine if not
```
$ wzip "https://…amd64-generic-image.zip"
2024-04-10 13:18:40    4756340736     515297761 D flatcar_production_image.bin
2024-04-10 13:18:40 …
```
> .github: Remove bz2 compression layer from zip artifacts

- changelog/changes/2024-04-11-openstack-autologin.md
- sdk_container/src/third_party/coreos-overlay/coreos-base/common-oem-files/files/openstack/grub.cfg.frag
So far the console in OpenStack (or Brightbox which shares the image) was not usable well until one issues a reboot to add the autologin in the GRUB menu.
Add it by default so that one doesn't need this reboot trick.
```$ cat grub.cfg 
set oem_id="openstack"
set linux_append="flatcar.autologin"
```
> coreos-base/common-oem-files: Enable flatcar.autologin for OpenStack

- changelog/changes/2024-04-11-hyperv-images-compression.md
- ci-automation/vms.sh
On Windows, the .bz2 compression format is not supported by native tooling and external tools like 7zip need to be installed.
Switching to .zip compression, there will be no need for the extra step of having external tools.
See: https://github.com/flatcar/Flatcar/issues/1009
> ci-automation/vms: provide Hyper-V images with .zip compression

- sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-init/coreos-init-9999.ebuild
This pulls in https://github.com/flatcar/init/pull/119 just to have the latest commit ref. The change is not needed on new Flatcar versions but for those that download the flatcar-update script from git as raw file.
See linked PR
↓ Not needed
> coreos-base/coreos-init: Update to latest ref

- .github/workflows/image_changes.sh
The "set -x" bash debug output is very noisy and one doesn't even see the actual output in this noise.
> .github: Disable debug output for image-changes

- build_library/vm_image_util.sh
The move to symlinking to the qemu-uefi image also resulted in the qemu-uefi image being referenced in the qemu-bios and qemu-uefi-secure scripts instead of referencing the image symlinks. Same for the VM name shown in the qemu window title.
When generating the qemu scripts, use the original qemu image name and VM name.
Backport
GitHub Actions and [Jenkins](http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/3861/cldsv/)
```
curl -fsSL https://bincache.flatcar-linux.net/images/amd64/9999.9.9+kai-qemu-script-img-name/flatcar_production_qemu_uefi_secure.sh|grep -m2 -P "(VM_NAME|VM_IMAGE)"
VM_NAME='flatcar_production_qemu_uefi_secure-9999-9-9-kai-qemu-script-img-name'
VM_IMAGE='flatcar_production_qemu_uefi_secure_image.img'
curl -fsSL …
```
> build_library: Use original qemu image name in qemu script

- ci-automation/vms.sh
After making flatcar_production_pxe.vmlinuz a symlink to flatcar_production_image.vmlinuz the signature creation didn't work because the target could not be found.
As we do with the generic image, download the kernel from bincache, too, before starting the VM image build.
Backport
[Jenkins](http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/3873/cldsv/)
Digest/signature files are present now: http://bincache.flatcar-linux.net/images/arm64/9999.9.9+kai-pxe-vmlinuz-sign/flatcar_production_pxe.vmlinuz.DIGESTS
> ci-automation/vms: Download vmlinuz file before building VM images

- build_library/grub_install.sh
These changes are not user visible but slightly improve our grub configuration:
- pass a useful hint to the memdisk grub config so that it searches the most likely boot partition path first
- include btrfs grub module in CORE_MODULES, since btrfs is used by the oem partition
> grub cfg tweaks

- ci-automation/garbage_collect.sh
- ci-automation/garbage_collect_cloud.sh
- jenkins/README.md
The deletion of old release AMIs was still relying on the previous Jenkins setup. Move this to the ci-automation folder.
It worked on a manual run in Jenkins: `Pruning complete: {total:508 kept:42 skipped:420 recentlyUsed:4 softDeleted:42 deleted:0}` and similar showed up 8 times.
> Migrate release AMI gc to ci-automation

- build_library/vm_image_util.sh
- changelog/changes/2024-04-29-kubevirt-images.md
- sdk_container/src/third_party/coreos-overlay/coreos-base/afterburn/files/coreos-metadata.service
- sdk_container/src/third_party/coreos-overlay/coreos-base/common-oem-files/common-oem-files-0-r8.ebuild
- sdk_container/src/third_party/coreos-overlay/coreos-base/oem-kubevirt/metadata.xml
- sdk_container/src/third_party/coreos-overlay/coreos-base/oem-kubevirt/oem-kubevirt-0.ebuild
- sdk_container/src/third_party/coreos-overlay/sys-kernel/bootengine/bootengine-9999.ebuild
As Ignition supports KubeVirt, add a custom oem for it and also the required parts to be able to build an image in .qcow2 format and .gz compression.
Fixes: https://github.com/flatcar/Flatcar/issues/1358
> image: add kubevirt image build

- .github/workflows/ci.yaml
The Flatcar extensions get built by the GitHub PR CI but only their content files get archived. Add the .raw image itself so that one can copy it into the image (downloading it at boot time won't work because this uses bincache - so one could get an extension image in case the but version happens to match but it won't be the one that was built in the GitHub CI).
For testing PRs like https://github.com/flatcar/scripts/pull/1964
Checked that `flatcar-zfs.raw` is part of `amd64-vm-images.zip`
> .github: Add Flatcar extensions to vm-images artifact

- sdk_container/src/third_party/coreos-overlay/app-emulation/wa-linux-agent/files/0001-flatcar-changes.patch
The if-up-down to trigger the DHCP request causes problems. It's better
to directly ask systemd-networkd to issue the request. It seems that
one needs to use "reconfigure" instead of "forcerenew", so I went with
only that instead of somehow trying to see if "forcerenew" has an
effect.
For this comment https://github.com/flatcar/scripts/pull/1950#issuecomment-2092741939
Used `flatcar-update -P … -E …` to switch to the built image, and checked that waagent triggers the DHCP renewal:
```
May 03 14:06:56 newname systemd-hostnamed[2482]: Hostname set to <newname> (static)
May 03 14:06:56 newname systemd-resolved[1538]: System hostname changed to 'newname'.
May 03 14:06:56 newname sudo[2479]: pam_unix(sudo:session): session closed for user root
May 03 14:07:06 newname waagent[2401]: …
```
> app-emulation/wa-linux-agent: Use networkctl to propagate hostname

- ci-automation/vms.sh
As the .qcow2 is already compressed, there is no need to provide a .bz2 compression on top.
Also, the cdi importer for KubeVirt does only support gz or xz compression.
> ci-automation/vm: do not compress KubeVirt images

- sdk_container/src/third_party/coreos-overlay/coreos-devel/fero-client/fero-client-9999.ebuild
- sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.accept_keywords
- fero-client was previously keyworded but a revbump due to a dependency change resulted in the keyword not matching any longer
- ccid is a new dep that is still marked ~arm64 in the Gentoo tree.
Testing with bootstrap_sdk when starting from dev container tarball as seed. These missing keywords show up in stage4.
> coreos-overlay/profiles: Add keywords for arm64 sdk

- build_library/grub_install.sh
- build_library/vm_image_util.sh
- changelog/changes/2024-06-21-remove-unused-grub-files.md
Remove grub modules from disk that are assembled into the grub executable.
Remove grub executables that are copies that are not used in the boot path.
This should have no user visible impact.
> Shrink /boot by removing duplicate and unused grub binaries/modules

- ci-automation/release.sh
Add the support to run the pre-release and the release jobs via managed idenities
to be merged with https://github.com/flatcar/mantle/pull/535
> ci-automation/release: add support for Managed idenities

- build_library/sysext_prod_builder
This change fixes a version mismatch of `FLATCAR_BUILD_ID` when performing a dev build of an existing release tag. The build ID is part of the version string of dev builds, separated by a `+` from the main version. If common.sh detects a dev build (`COREOS_OFFICIAL` != 1) and `FLATCAR_BUILD_ID` is empty, `common.sh` will generate a new ID based on a timestamp. This is usually desired behaviour to prevent accidentally marking a dev build non-dev (which would cause breakage much later when signature checks fail).
For official releases, `FLATCAR_BUILD_ID` is not set in version.txt. A dev build of a release tag would make `common.sh` generate a new ID each time it is sourced by different processes. build_image sources `common.sh` first, and writes the resulting version string the OS image's …
> sysext_prod_builder: fix build id mismatch

- flatcar_workon
- update_chroot
The `update_chroot` calls `flatcar_workon` to get a list of workon packages to rebuild on SDK. But not passing `--board` flag to `flatcar_workon` means using default board (`amd64-usr`), so it really gets a list of packages from the board. But the script failed for me during the sdk_container job, because no board was set up that point.
So this PR adds back the `--host` flag to `flatcar_workon` (which used to be here in `cros_workon`) and makes `update_chroot` pass the new flag to the script.
Changes tested as a part of [sdk-container job for merged-usr changes](http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk_container/1148/consoleFull).
There are also [logs for the failing job](http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk_container/1146/consoleText), search for …
> Fixes for flatcar-workon

- ci-automation/garbage_collect_cloud.sh
- ci-automation/release.sh
- ci-automation/vendor-testing/azure.sh
- sdk_container/.repo/manifests/mantle-container
These changes will be necessary after we merge https://github.com/flatcar/mantle/pull/532.
Needs to be backported to all the channels.
> Pull in latest mantle, drop obsolete auth flags

- ci-automation/ci-config.env
- ci-automation/vendor-testing/azure.sh
This adds support for providing a value for the newly introduced --azure-kola-vnet kola parameter through the environment. This parameter is meant to indicate that kola is running inside of a vnet in Azure and the kola created storage account will be restricted to being accessed from that vnet. This lets us disable public access to storage accounts.
Needs a corresponding change to jenkins jobs, because we have no way of determining what vnet a worker node is connected to programmatically. So it needs to be defined by the job.
Run kola in Azure, in the same subscription that kola has access to and pass `--azure-kola-vnet`.
> ci-automation/vendor-testing/azure: Allow passing kola vnet

- update_distfiles
This was broken by the Catalyst upgrade, which renamed coreos to coreos-overlay. It isn't worth renaming the directory used on the mirror, and the Portage configuration still points to the old name.
Run `./update_distfiles --dry_run` in the SDK.
As well as `--dry_run`, I also tested `--upload` and `--download` by sticking `echo` in front of the lines that do anything.
> Fix distfiles mirror by writing to coreos as before, not coreos-overlay

- sdk_container/src/third_party/coreos-overlay/app-misc/ca-certificates/ca-certificates-3.102.1.ebuild
Ftp access appears to have been decommissioned (access times out) so switch to the https mirror that Mozilla provides.
See: flatcar/flatcar#1504
Rebuild as usual always.
```bash
$ GENTOO_MIRRORS="" emerge --fetchonly ca-certificates
These are the packages that would be fetched, in order:
Calculating dependencies... done!
Dependency resolution took 0.96 s (backtrack: 0/20).
[ebuild     U  ] app-misc/ca-certificates-3.102.1::coreos-overlay [3.102::coreos-overlay] 74669 KiB
Total: 1 package (1 upgrade), Size of downloads: 74669 KiB
>>> Fetching (1 of 1) app-misc/ca-certificates-3.102.1::coreos-overlay
>>> Downloading 'https://archive.mozilla.org/pub/security/nss/releases/NSS_3_102_1_RTM/src/nss-3.102.1.tar.gz'
--2024-07-29 08:37:41-- …
```
> app-misc/ca-certificates: Switch to https protocol in SRC_URI

- .github/workflows/portage-stable-packages-list
- bootstrap_sdk
- build_library/catalyst.sh
- sdk_container/src/third_party/portage-stable/scripts/bootstrap.sh
From https://wiki.gentoo.org/wiki/Catalyst/Stage_Creation#Build_Stage3:
> It is not necessary to build stage2 in order to build stage3. Gentoo
> release engineering does not build stage2, and you should not need to
> unless you're intentionally building a stage2 as your goal.
We can now sync portage-stable/scripts with upstream because bootstrap.sh is only used during stage2, and the changes we had are no longer relevant. It seems likely the changes were already redundant anyway.
Apart from making things simpler, judging by a glance at Jenkins, it knocks about half an hour off the build time.
Build the SDK with `./bootstrap_sdk` as usual.
A two-phase Jenkins build was successful. No notable changes were reported.
> Skip Catalyst stage2 as recommended by upstream Gentoo

- build_library/qemu_template.sh
- changelog/bugfixes/2024-08-16-qemu-launcher-initrd-option.md
It was `-R`, but this was already taken by the read-only pflash option, so use `-r` instead.
Try the PXE version of the script with the `-r` option. You can pass a renamed copy of flatcar_production_pxe_image.cpio.gz and check the process listing to see what was passed to QEMU.
I manually applied this change to the existing PXE script and tried the `-r` option. I don't think anything in CI covers this.
> Fix the initrd option in the QEMU launcher script

- build_library/sysext_prod_builder
- build_sysext
build_sysext uses a base squashfs (basically a full snapshot of the Flatcar OS image) to build custom sysexts on top. Before building it ensures the base image actualy matches the OS version in the repository root.
The version string includes a BUILD_ID which might be auto-generated (by including common.sh) if it is not present in the version file - e.g. when the version is an official release (tag). This build ID auto-generation causes issues with the version check when image build and sysext build scripts run independently - each will generate its own build ID, and this will cause build_sysext's version check to fail.
build_sysext will now use the build id from the base squashfs when it is not set in the source tree's version.txt to work around that issue. This is a more general …
> build_sysext: Detect dev rebuild of release tag, fix build ID issue

- sdk_container/src/third_party/coreos-overlay/coreos/config/env/sys-fs/zfs-kmod
This change sets `SKIP_KERNEL_BINPKG_ENV_RESET` in the zfs-kmod env so linux-info.eclass keeps kernel env variables. This resolves an issue with installing zfs-kmod as a binpkg when the kernel was not yet installed. In a pure binpkg install the zfs-kmod package might be installed before the kernel, leading to the kmod's kernel version detection to fail.
The original issue may be reproduced by running a rebuild of a release tag (which will use binpkgs from our mirrors). Note that the reproduction is flaky because the issue is caused by a race condition between installing the kernel binpkg and zfs-kmod.
- Reproduce by rebuilding a recent release tag
```
git clone https://github.com/flatcar/scripts.git
cd scripts
git checkout alpha-4054.0.0
./run_sdk_container -t
```
As …
> config/env/sys-fs/zfs-kmod: un-break zfs-kmod binpkg install

- ci-automation/image_changes.sh
Currently we generate three extra sysext images (podman, zfs and python). Make sure we get the reports for those too.
~Needs https://github.com/flatcar/flatcar-build-scripts/pull/162 first.~
CI: Tested together with #2230.
> Add image changes reports for extra sysexts

- sdk_container/src/third_party/coreos-overlay/coreos/user-patches/sec-policy/selinux-policykit
So the rules built for this module are consistent with rules built for other modules.
> overlay coreos/user-patches: Add a symlink for selinux-policykit

- sdk_container/src/third_party/coreos-overlay/coreos-devel/board-packages/board-packages-0.0.1.ebuild
This change adds the Azure and HyperV OEM "hv-daemons" to board-packages so build_packages.sh will actually build these. This un-breaks a build issue with the Azure and HyperV images.
It's a one-line change to un-break the nightly build and Azure testing.
Needs to be cherry-picked to flatcar-3975, flatcar-4054, flatcar-4081.
> board-packages: add hyperv hv-daemons

- .github/workflows/kernel-apply-patch.sh
LTS channel has no such package, so the action for finding the kernel update was failing. Fix it by updating the package only if it exists.
> .github: Handle missing app-emulation/hv-daemons

- .github/workflows/run-kola-tests.yaml
- build_library/grub.cfg
- changelog/changes/2024-09-10-kernel-lockdown.md
- ci-automation/ci-config.env
- ci-automation/vendor-testing/qemu.sh
- ci-automation/vendor-testing/qemu_update.sh
- run_local_tests.sh
- sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-modules/files/commonconfig-6.6
- sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/coreos-sources-6.6.51.ebuild
- sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.6/z0004-efi-Add-an-EFI_SECURE_BOOT-flag-to-indicate-secure-b.patch
- sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.6/z0005-efi-Lock-down-the-kernel-if-booted-in-secure-boot-mo.patch
- sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.6/z0006-mtd-phram-slram-Disable-when-the-kernel-is-locked-do.patch
- sdk_container/src/third_party/coreos-overlay/sys-kernel/coreos-sources/files/6.6/z0007-arm64-add-kernel-config-option-to-lock-down-when-in-.patch
* import secureboot lockdown kernel patches. These are required by the upstream shim community. The alternative is to either always force lockdown (bad - no unsigned kernel modules) or do so through a kernel cmdline parameter in grub (frowned upon and harder to fix later). I took and rebased the patches from debian: https://sources.debian.org/src/linux/6.6.13-1~bpo12%2B1/debian/patches/features/all/lockdown/.
* enable grub fallback. this can be triggered if the kernel signature fails verification, and will go through gptprio selection and eventually fallback to the previous slot. fallback only supports numerical menuentry ids (source: https://github.com/coreos/grub/blob/2.02-coreos/grub-core/normal/menu.c#L350).
* CI: changes from @sayanchowdhury for use with …
> secure boot: lockdown, grub fallback, CI

- sdk_lib/Dockerfile.sdk-build
This change builds all packages required to break circular dependencies in the "build SDK container" stage and includes these in the SDK image. This way, emerge-<arch> can be used right away and build_packages only builds packages with production USE flags.
The change significantly reduces the build time at the cost of a larger SDK image and longer SDK container build time. Uncompressed:
|              |  Size before   |    Size after |
| ------------|--------------|------------|
| all arches    |   7.75GB    |         9.29GB |
| arm64       |     5.7GB        |      6.58GB |
| amd64     |       5.64GB       |      6.45GB |
- Clone the repo, check out this branch
- Fetch a recent SDK tarball to build the container image from, e.g. …
> SDK container: include circular dependency breaking packages in SDK container

- sdk_container/src/third_party/coreos-overlay/coreos/config/env/sys-boot/grub
We will bump this every time we or Gentoo change patches that modify parts of GRUB that are installed to the boot partition. We will reset the version back to 1 when the upstream GRUB version changes.
Without this, we are bound by Gentoo's PVR string, which we cannot change when we need to make changes to our own patches. The shim review wants to know the full version number of our GRUB build, and it would look bad to make such changes without changing the version.
This suffix is also applied to the Flatcar entry in the SBAT, which is especially important for the shim review.
The published binary package will still be labelled with the Gentoo PVR, but that seems less important given that end users cannot update individual packages on Flatcar installations.
Boot the image from CI and see …
> sys-boot/grub: Adjust version string to include flatcar1 suffix

- .github/workflows/portage-stable-packages-list
- sdk_container/src/third_party/portage-stable/eclass/usr-ldscript.eclass
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/1781/cldsv/
--
It couldn't be added before to automation, because the eclass in Gentoo would introduce have unwanted side-effects into our built images. But the Gentoo version of the eclass is essentially a no-op when USE=split-usr is disabled. We have recently moved to use Gentoo profiles that disable USE=split-usr altogether, and with this move, we can now safely put the eclass into automation.
This marks the point where the entirety of the portage-stable is under automation.
Closes https://github.com/flatcar/Flatcar/issues/645.
Closes https://github.com/flatcar/Flatcar/issues/646.
--
> Add eclass/usr-ldscript.eclass to package automation

- build_dev_binpkgs
- build_library/build_image_util.sh
- build_library/prefix_util.sh
- build_library/toolchain_util.sh
- build_library/vm_image_util.sh
- build_sysext
- changelog/updates/2024-11-12-portage.md
- sdk_container/src/third_party/portage-stable/sys-apps/portage/portage-3.0.66.1-r1.ebuild
- setup_board
`--root-deps` used to install build dependencies to ROOT instead of /. `--root-deps=rdeps` used to drop all build dependencies entirely. These never made much sense, so both options were rendered ineffective from EAPI 7. The number of ebuilds with older EAPIs has since dwindled to nothing.
Portage 3.0.66 (included in this PR) has made `--root-deps` now install build dependencies to ROOT as well as / because this can actually be useful and doesn't cause breakage.
However, it does make us more prone to cyclic dependencies when initially populating the board roots. There is no reason for us to use this option though because its main purpose is to ensure the target environment has everything it needs to rebuild itself. Given that the option didn't do anything recently, we evidently don't even …
> Drop --root-deps and --root-deps=rdeps emerge options

- build_library/grub_install.sh
- changelog/changes/2024-11-18-grub-modules.md
- sdk_container/src/third_party/coreos-overlay/coreos/config/env/sys-boot/grub
Secure Boot prevents you from loading additional GRUB modules so remove them from supported targets to save space. These modules could be useful for debugging with Secure Boot disabled, but manually copying the modules with debug symbols is even more useful and not that difficult.
Compress the GRUB modules with xz instead of gzip to save space. Giving the `--best` or `-9` option results in a heavier decompression cost with no gain on such small files. Note that this required [a Kola test to be dropped](https://github.com/flatcar/mantle/pull/565).
Prevent the developer test GRUB modules from being built. These are normally always installed, even by `grub-install`, but they have no use outside of testing and take up valuable space in /boot. Apologies for the use of awk here, but sed didn't …
> Free up /boot space with some GRUB module changes

- build_library/build_image_util.sh
We were supposed to collect allowed users and allowed groups into separate arrays. Due to the copy-paste mistake, we overwrote allowed users array with allowed groups while leaving the array for allowed groups empty, so we ended up passing only allowed groups instead of both.
Fixes nothing in particular, just spotted it when figuring out how to update sys-auth/sssd.
> build_library/build_image_util.sh: Fix copy-pasta

- build_library/build_image_util.sh
Apparently `local -x FOO` does not locally export an already existing variable, but rather does some whole weird lot of nothing - it shadows an existing variable with a new unset one, but it won't export it until it gets assigned.
> build_library/build_image_util: Fix local exporting

- build_library/prod_image_util.sh
We would normally remove these for an official build so that the signed versions can be uploaded later. However, we are not doing that signing until we pass the shim review.
Do a release!
I ran shellcheck. We'll do a release to see whether this works now.
> prod_image_util.sh: Temporarily nobble removing unsigned kernel and GRUB

- build_image
- build_library/build_image_util.sh
- ci-automation/sbsign_image.sh
- sbsign_image
The update payload needs the kernel, which isn't signed during the image job. Secure Boot is not currently enabled for update tests, but we may as well do this properly. The production update upload is generated manually at the end after everything has already been signed.
However, we need to temporarily nobble part of the above change until we have actually passed the shim review.
This also fixes a container name clash in the sbsign_image job.
Nothing to do.
I have run Jenkins for [amd64](http://jenkins.infra.kinvolk.io:8080/job/container/job/sbsign_image/15/cldsv/) and [arm64](http://jenkins.infra.kinvolk.io:8080/job/container/job/sbsign_image/16/cldsv/). The qemu_update tests passed. I also checked the timestamps of files on the bincache to ensure the right files were uploaded when …
> Delay generating test update payload in official builds

- run_sdk_container
The script would pass unknown flags further as a container command. This normally is not desired, but in case it actually is, the user can use the newly added `--` parameter to stop parameter handling and pass the following parameters as the container command.
I was tripped by using -u instead of -U and I got a rather confusing error message suggesting something going wrong inside the container.
> run_sdk_container: Bail out on unknown flags

- sdk_container/src/third_party/coreos-overlay/x11-drivers/nvidia-drivers/files/bin/setup-nvidia
Since we added CONFIG_I915 to our amd64 kernel (#2349), CONFIG_ACPI_VIDEO=m is enabled and causes the nvidia driver to compile-in some code that depends on it. Since we need to insmod the nvidia module (we don't have depmod information) - manually load the required module. The '|| true' lets this line pass on arm64.
Changelog is not required because this fixes a bug that hasn't been released yet.
Run azure testing, which will execute GPU tests.
> setup-nvidia: Modprobe video.ko for amd64

- changelog/bugfixes/2025-02-28-walinuxagent-ignition.md
- sdk_container/src/third_party/coreos-overlay/app-emulation/wa-linux-agent/files/0002-prevent-ssh-public-key-override.patch
- sdk_container/src/third_party/coreos-overlay/app-emulation/wa-linux-agent/wa-linux-agent-2.9.1.1-r3.ebuild
Apply patch to fix an issue when overriding ssh public key from ignition configuration. Since the fix is not available in releases of wa-linux-agent, we should apply a separate patch.
See also https://github.com/Azure/WALinuxAgent/pull/3309.
See also https://github.com/flatcar/Flatcar/issues/1661.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/5465/cldsv/ passed
> overlay wa-linux-agent: apply patch to fix ssh public key override issue (stable, beta)

- ci-automation/vendor-testing/aws.sh
- ci-automation/vendor-testing/azure.sh
- ci-automation/vendor-testing/brightbox.sh
- ci-automation/vendor-testing/digitalocean.sh
- ci-automation/vendor-testing/equinix_metal.sh
- ci-automation/vendor-testing/gce.sh
- ci-automation/vendor-testing/hetzner.sh
- ci-automation/vendor-testing/openstack.sh
- ci-automation/vendor-testing/qemu.sh
- ci-automation/vendor-testing/qemu_update.sh
- ci-automation/vendor-testing/vmware.sh
- sdk_container/.repo/manifests/mantle-container
The SELinux denial checking in kola is conditionally disabled - if the Flatcar image version is too old, then it's disabled for all the tests. For kola to decide whether to disable or enable the checking, it needs to know the version of the image. It can be done in two ways - either we pass the version to kola through a flag, or kola itself spins a temporary cluster with one machine and figures out the version from os-release file. The latter is obviously very slow, to a point that kola was skipping this step if the tests didn't need the version information. Now the version information is needed always, and our ci-automation already knows the version of the image, so we can pass it to kola to skip creating the temporary cluster.
Requires https://github.com/flatcar/mantle/pull/572. Will …
> Pass image version to kola

- build_library/extract-initramfs-from-vmlinuz.sh
On Linux >= 6.10, the first rootfs is an extra ghost rootfs of 336K, that has a corrupted CPIO.
To overcome this issue, do not fail on `cpio --extract`.
> cpio: do not fail on ghost rootfs

- build_library/qemu_template.sh
- build_library/vm_image_util.sh
- changelog/bugfixes/2025-04-07-qemu-script-paths.md
I couldn't take it anymore! The launcher script could not handle paths outside the script's own directory, and it was driving me crazy. Now only the default values are relative to the script's directory. Given paths are relative to the current directory and absolute paths work as you would expect.
You don't need to grab any new images, just the .sh files from [bincache](https://bincache.flatcar-linux.net/images/amd64/9999.0.0+qemu-script-paths-2/).
I ran [CI](http://jenkins.infra.kinvolk.io:8080/job/container/job/packages/9100/cldsv/) but without the tests because they don't use this script. I grabbed the new .sh files, compared them against the old ones, and tried them out with different paths.
> build_library: Fix path handling in QEMU launcher script

- build_library/qemu_template.sh
How disk and network devices are set up for the machine need not to be arch-specific any more. We can use virtio-blk-pci and virtio-net-pci on both arches.
This PR also adds two options:
- `-D` or `-image-disk-opts` for adding options to primary disk (I used it mostly to add "serial=foo", so primary disk is available under `/dev/disk/by-id/virtio-foo` and its partitions as `/dev/disk/by-id/virtio-foo-partN`)
- `-d` or `-disk` for adding extra disks - you can do `qemu-img create -f qcow2 extradisk 1G`, and then invoke the script with `-d extradisk,serial=my-extra-disk` to have it available under `/dev/disk/by-id/virtio-my-extra-disk`
Tested locally on both amd64 and arm64.
> Simplify and improve flatcar_production_qemu*.sh script

- build_library/dev_container_util.sh
- build_library/toolchain_util.sh
- build_packages
- set_version
- settings.env
- setup_board
I got very confused while looking into how the dev container is built. This code didn't help. I think it can be dropped.
N/A
I have run [amd64 and arm64 builds](http://jenkins.infra.kinvolk.io:8080/job/container/job/packages/9267/cldsv/) with the qemu_* tests. They passed successfully.
> Drop confusing and obsolete binpkg-related code

- pkg_auto/impl/pkg_auto_lib.sh
They were showing up as "docker" or "containerd" in the reports, which is confusing. "sysext-docker" or "sysext-containerd" makes it clear.
A follow-up to https://github.com/flatcar/scripts/pull/2860#discussion_r2068150326.
> pkg-auto: Mark in-rootfs sysexts as sysexts in reports

- build_library/extract-initramfs-from-vmlinuz.sh
- build_library/reports_util.sh
I thought cpio was always creating the output directory automatically, but it was silently failing. It would only extract the next rootfs when run a subsequent time. I must admit that I don't know why it was apparently still working in CI, but it was definitely failing for me locally.
While fixing the above, I also decided to sort the content listings for more consistent output.
N/A
Examples of the new initrd contents can be seen [here](https://bincache.flatcar-linux.net/images/arm64/9999.0.0+chewi-misc-1/flatcar_production_image_initrd_contents.txt) and [here](https://bincache.flatcar-linux.net/images/arm64/9999.0.0+chewi-misc-1/flatcar_production_image_initrd_contents_wtd.txt). The [image_changes output](http://jenkins.infra.kinvolk.io:8080/job/container/job/image_changes/10080/console) …
> build_library: Fix extraction script and sort content listings

- pkg_auto/impl/pkg_auto_lib.sh
Occurences file shows where the package name shows up in the repository. It tries to be smart, so that checking for sys-devel/gcc will not be showing sys-devel/gcc-config. But the smart check was flawed as it ignored the forms like sys-devel/gcc-${PV}. Noticed when trying to check occurences for sys-libs/libsepol and there were not enough occurences shown.
> pkg-auto: Fix occurences generation

- PREFIX.md
- ci-automation/README.md
- sdk_container/src/third_party/coreos-overlay/app-admin/toolbox/toolbox-9999.ebuild
- sdk_container/src/third_party/coreos-overlay/coreos-base/update-ssh-keys/update-ssh-keys-9999.ebuild
- sdk_container/src/third_party/coreos-overlay/sys-libs/nss-usrfiles/nss-usrfiles-9999.ebuild
This pull request updates references from the `flatcar-master` branch to the `main` branch across various files and documentation. The changes ensure consistency with the updated branch naming convention.
* Updated the link to `kola` in `PREFIX.md` to reference the `main` branch instead of `flatcar-master`.
* Updated the link to `kola` in `ci-automation/README.md` to reference the `main` branch instead of `flatcar-master`.
* Changed the `EGIT_COMMIT` comment in `toolbox-9999.ebuild` to reference `main` instead of `flatcar-master`.
* Changed the `EGIT_COMMIT` comment in `update-ssh-keys-9999.ebuild` to reference `main` instead of `flatcar-master`.
* Changed the `EGIT_COMMIT` comment in `nss-usrfiles-9999.ebuild` to reference `main` instead of `flatcar-master`.
This is in reference to this …
> Update documentation and ebuilds to reference `main` branch instead `flatcar-master`

- README.md
This pull request updates the `README.md` to include instructions for working with forks of the scripts repository. The new section explains how to fetch upstream tags to ensure proper version detection when using the SDK. 
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R105-R115): Added a new section titled "Working with forks" to guide users on fetching upstream tags when working with a fork of the scripts repository. This ensures compatibility with the SDK's version detection mechanism using `git describe --tags`.
Fixes: https://github.com/flatcar/Flatcar/issues/1705
> docs: add instructions for working with forks and fetching upstream tags

- sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.mask
This multi-line comment accidentally only has a # prefix on the first line, which leads to this warning during the build:
--- Invalid atom in /mnt/host/source/src/third_party/coreos-overlay/profiles/coreos/base/package.mask: mask a specific version in hope that the future update may be smaller,
--- Invalid atom in /mnt/host/source/src/third_party/coreos-overlay/profiles/coreos/base/package.mask: who knows.
Add missing prefixes to lines 2 and 3.
Check build log to see that those lines no longer show up.
> profiles: Prefix comment with # in package.mask

- ci-automation/image_changes.sh
`show_changes_params` is not available in this lexical scope, we should have been using `show_changes_params_ref`. This has worked so far only because all the callers of the functions were passing `show_changes_params` to be referenced by
`show_changes_params_ref`. Just a lucky happenstance.
Spotted by Chewi.
> ci-automation: Use a valid reference

- ci-automation/ci_automation_common.sh
- ci-automation/packages-tag.sh
- ci-automation/sdk_bootstrap.sh
- test-nightly-tagging.sh
The issue was that in Jenkins we clone and checkout a specific branch in a peculiar way. We do `git fetch origin "${branch}"`, then we do `git checkout FETCH_HEAD` instead of `git checkout "${branch}"`. I don't remember what was the reason for doing this, but I decided against changing it.
So this way of checking out a branch caused `git rev-parse --abbrev-ref HEAD` to return `HEAD` instead of `${branch}` and the code deciding about pushing the commit with the nightly tag to the branch did so only when the returned value was `${branch}`. I'm not really sure if it was always broken and I did insufficient testing back when I added this code or it was some update of git changing behavior.
I replaced the check with comparing `git rev-parse HEAD` to `git rev-parse origin/${branch}`. This …
> Fix nightly tag pushing

- sdk_container/src/third_party/coreos-overlay/sys-kernel/bootengine/bootengine-9999.ebuild
This pulls in https://github.com/flatcar/bootengine/pull/106 to fix bugs in sysusr-usr.mount and
initrd-setup-root-after-ignition.service
> sys-kernel/bootengine: Pull in fix for error path and warnings

- build_library/extra_sysexts.sh
- changelog/changes/2025-07-25-overlaybd.md
- sdk_container/src/third_party/coreos-overlay/app-containers/accelerated-container-image/accelerated-container-image-1.3.0.ebuild
- sdk_container/src/third_party/coreos-overlay/app-containers/accelerated-container-image/accelerated-container-image-9999.ebuild
- sdk_container/src/third_party/coreos-overlay/app-containers/accelerated-container-image/files/10-overlaybd-snapshotter.conf
- sdk_container/src/third_party/coreos-overlay/app-containers/accelerated-container-image/metadata.xml
- sdk_container/src/third_party/coreos-overlay/sys-fs/overlaybd/files/10-overlaybd.conf
- sdk_container/src/third_party/coreos-overlay/sys-fs/overlaybd/files/overlaybd-cross.patch
- sdk_container/src/third_party/coreos-overlay/sys-fs/overlaybd/files/photon-cross.patch
- sdk_container/src/third_party/coreos-overlay/sys-fs/overlaybd/files/tcmu-fix.patch
- sdk_container/src/third_party/coreos-overlay/sys-fs/overlaybd/metadata.xml
- sdk_container/src/third_party/coreos-overlay/sys-fs/overlaybd/overlaybd-1.0.15.ebuild
- sdk_container/src/third_party/coreos-overlay/sys-fs/overlaybd/overlaybd-9999.ebuild
This adds overlaybd, a user space container-optimised block device implementing a novel layering block-level image format, which is designed for containers, with security and performance in mind.
Documentation is available at https://containerd.github.io/overlaybd/.
**sys-fs/overlaybd** ships the low-level user space block device (https://github.com/containerd/overlaybd) as well as low-level tooling for operating it.
**app-containers/accelerated-container-image** (https://github.com/containerd/accelerated-container-image) ships integration with containerd.
Both are part of the Containerd CNCF project.
1. Check out this branch
```sh
git checkout t-lo/containerd-overlaybd
```
2. Start the SDK
```sh
./run_sdk_container -t
```
3. Build packages and image
```sh
./build_image …
```
> Add overlaybd sysext

- build_library/build_image_util.sh
- build_library/dev_container_util.sh
- build_library/prod_image_util.sh
- build_library/sysext_prod_builder
- build_library/vm_image_util.sh
- build_sysext
- sdk_container/src/third_party/coreos-overlay/coreos/config/env/dev-libs/glib
- sdk_container/src/third_party/coreos-overlay/coreos/config/env/net-misc/openssh
- sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/profile.bashrc
- sdk_container/src/third_party/coreos-overlay/profiles/coreos/targets/generic/make.defaults
- sdk_container/src/third_party/coreos-overlay/profiles/coreos/targets/sdk/make.defaults
CI: http://localhost:8080/job/container/job/sdk/2210/cldsv/
This adds a function `flatcar_target` that replaces the earlier `cros_target`. The function returns a string that tells where the package will end up (prod image, dev container, sysexts, sdk, etc.) This is something I wanted to use for the selinux work, where I need to enable some python stuff for the production image. But since we don't want neither python interpreter nor selinux tools written in python in the production image, I need to mask them during installation. But these things may be still useful for other images we build (some sysext or dev container).
One thing to note is that the way we build packages, normally the target will be `generic-board` during source-based installation (from ebuild) - this step also produces …
> Add a more detailed way of determining the package target

- sdk_container/src/third_party/coreos-overlay/coreos-base/update_engine/update_engine-9999.ebuild
This pulls in https://github.com/flatcar/update_engine/pull/50 to fix a corner case when the extension file exists on old nodes that don't yet support extensions but should pull them on their update.
See https://github.com/flatcar/update_engine/pull/50
> update_engine: postinst: Make sure Flatcar extension folder exists

- nano/Readme.md
This adds the missing step of starting the SDK container and using parallelism for one flatcar nano specific emerge
Follow the instructions in the readme, they should be working now :)
> Flatcar nano: Minor README improvements

- sdk_container/src/third_party/coreos-overlay/coreos-base/flatcar-nano/flatcar-nano-0.0.1.ebuild
- sdk_container/src/third_party/coreos-overlay/profiles/coreos/base/package.use
- sdk_container/src/third_party/coreos-overlay/profiles/coreos/targets/generic/package.use
This makes nano now ~1/3 smaller than a regular flatcar release.
I think we can try to reduce this further, though.
Compile following the readme in the nano folder.
Doom in wasm as a container works fine. For a hackathon, this is all the testing done :-D
> Flatcar nano: remove ~14 more packages

- build_library/qemu_template.sh
- changelog/bugfixes/2025-10-08-macos-hvf-accel.md
Modified the qemu_template.sh script to include accel for macOS
```
arm64-usr+aarch64|arm64-usr+arm64)
set -- -machine virt,accel=kvm:hvf:tcg,gic-version=3 -cpu host -smp "${VM_NCPUS}" -nographic "$@" ;;
```
> Add hvf acceleration support for macOS
